[package]
name = "sha256"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
sha2 = { version = "0.10.6", features = ["compress"] }
proptest = "1.2.0"
noir-runner = { git = "https://github.com/noir-lang/noir-runner", branch = "main" }
