[package]
name = "sig_check_rsa"
type = "lib"
authors = ["Theo Madzou"]
compiler_version = ">=1.0.0"

[dependencies]
rsa = { path = "../../../../noir_rsa" }
bignum = { path = "../../../../noir-bignum" }
utils = { path = "../../utils" }
common = { path = "../common" }
