[package]
name = "sig_check_rsa"
type = "lib"
authors = ["Theo Madzou"]
compiler_version = ">=1.0.0"

[dependencies]
rsa = { git = "https://github.com/zkpassport/noir_rsa", tag = "v0.7.0-1" }
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.6.1"}
utils = { path = "../../utils" }
common = { path = "../common" }
