[package]
name = "integrity_to_disclosure_commitment"
type = "lib"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
utils = { path = "../../utils" }
common = { path = "../common" }
