[package]
name = "provekit-groth16"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ark-bn254 = { version = "0.5.0", default-features = false, features = ["curve"] }
ark-ff = { workspace = true }
ark-ec = { version = "0.5", features = ["parallel"] }
ark-poly = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { version = "0.5", features = ["std"] }
rayon = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true, features = ["derive"] }
provekit-common = { workspace = true }

[lints]
workspace = true
