[package]
name = "t_add_dsc_1850"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
sig_check_rsa = { path = "../../utils/sig-check/rsa" }
utils = { path = "../../utils/utils" }
commitment = { path = "../../utils/commitment/common" }
poseidon = { tag = "v0.3.0", git = "https://github.com/noir-lang/poseidon" }
