//! WASM32 SIMD implementations of Montgomery multiplication
//!
//! This module provides WASM-optimized Montgomery multiplication functions
//! with the same interface as the ARM64 assembly implementations.
//!
//! The implementations are **GENERATED** by the HLA (High-Level Assembly) framework
//! at build time. The code generator produces optimized Rust with:
//! - Instruction interleaving (scalar + SIMD operations interleaved for latency hiding)
//! - Optimal variable lifetimes (from register allocation)
//! - Portable SIMD operations (std::simd) that compile to WASM v128 instructions
//!
//! The generated code includes the full Montgomery multiplication algorithm:
//! - u256 → u260 transformation with 52-bit limbs
//! - Floating-point biasing for accurate multiplication (C1, C2 constants)
//! - Montgomery reduction using RHO constants
//! - Carry propagation and modular inverse computation
//!
//! # Generated Files
//!
//! The following files are generated by `build.rs` using `hla::builder::build_rust_simd()`:
//! - `montgomery_interleaved_3.rs`
//! - `montgomery_interleaved_4.rs`
//! - `montgomery_square_interleaved_3.rs`
//! - `montgomery_square_interleaved_4.rs`
//! - `montgomery_square_log_interleaved_3.rs`
//! - `montgomery_square_log_interleaved_4.rs`

// Imports needed by all generated files
use {
    core::simd::Simd,
    fp_rounding::{RoundingGuard, Zero},
};

// Include generated implementations
// These files are created by build.rs when building for wasm32 target

include!("montgomery_interleaved_3.rs");
include!("montgomery_interleaved_4.rs");
include!("montgomery_square_interleaved_3.rs");
include!("montgomery_square_interleaved_4.rs");
include!("montgomery_square_log_interleaved_3.rs");
include!("montgomery_square_log_interleaved_4.rs");

#[cfg(test)]
mod tests {
    use super::*;
    use {crate::{scalar_mul, scalar_sqr}, core::simd::Simd, fp_rounding::{with_rounding_mode, Zero}};

    #[test]
    fn test_montgomery_interleaved_3_vs_scalar() {
        unsafe {
            with_rounding_mode((), |guard, ()| {
                let a = [1u64, 2, 3, 4];
                let b = [5u64, 6, 7, 8];
                let c = [9u64, 10, 11, 12];
                let d = [13u64, 14, 15, 16];

                let av = [
                    Simd::from_array([c[0], d[0]]),
                    Simd::from_array([c[1], d[1]]),
                    Simd::from_array([c[2], d[2]]),
                    Simd::from_array([c[3], d[3]]),
                ];

                let bv = [
                    Simd::from_array([c[0], d[0]]),
                    Simd::from_array([c[1], d[1]]),
                    Simd::from_array([c[2], d[2]]),
                    Simd::from_array([c[3], d[3]]),
                ];

                let (a_res, _av_res) = montgomery_interleaved_3(guard, a, b, av, bv);
                let a_scalar = scalar_mul(a, b);

                // Verify scalar path matches
                assert_eq!(a_res, a_scalar);
            });
        }
    }

    #[test]
    fn test_montgomery_square_interleaved_3_vs_scalar() {
        unsafe {
            with_rounding_mode((), |guard, ()| {
                let a = [1u64, 2, 3, 4];
                let b = [5u64, 6, 7, 8];
                let c = [9u64, 10, 11, 12];
                let av = [
                    Simd::from_array([b[0], c[0]]),
                    Simd::from_array([b[1], c[1]]),
                    Simd::from_array([b[2], c[2]]),
                    Simd::from_array([b[3], c[3]]),
                ];

                let (a_res, _av_res) = montgomery_square_interleaved_3(guard, a, av);
                let a_scalar = scalar_sqr(a);

                // Verify scalar path matches
                assert_eq!(a_res, a_scalar);
            });
        }
    }

    #[test]
    fn test_montgomery_square_log_interleaved_3_vs_scalar() {
        unsafe {
            with_rounding_mode((), |guard, ()| {
                let a = [1u64, 2, 3, 4];
                let b = [5u64, 6, 7, 8];
                let c = [9u64, 10, 11, 12];
                let av = [
                    Simd::from_array([b[0], c[0]]),
                    Simd::from_array([b[1], c[1]]),
                    Simd::from_array([b[2], c[2]]),
                    Simd::from_array([b[3], c[3]]),
                ];

                let (a_res, _av_res) = montgomery_square_log_interleaved_3(guard, a, av);
                let a_scalar = scalar_sqr(a);

                // Verify scalar path matches
                assert_eq!(a_res, a_scalar);
            });
        }
    }
}
