// GENERATED FILE, DO NOT EDIT!
// Generated by HLA framework for WASM SIMD optimization
// Note: Imports are in the parent module (mod.rs)

#[inline(always)]
pub fn montgomery_square_interleaved_4(
    _guard: &RoundingGuard<Zero>,
    a: [u64; 4],
    a1: [u64; 4],
    av: [Simd<u64, 2>; 4]
) -> ([u64; 4], [u64; 4], [Simd<u64, 2>; 4]) {
    let a_0 = a[0];
    let a_1 = a[1];
    let a_2 = a[2];
    let a_3 = a[3];
    let a1_0 = a1[0];
    let a1_1 = a1[1];
    let a1_2 = a1[2];
    let a1_3 = a1[3];
    let av_0 = av[0];
    let av_1 = av[1];
    let av_2 = av[2];
    let av_3 = av[3];

    let t0 = 4503599627370495;
    let t1 = av_0.wrapping_mul(av_0);
    // TODO: Unsupported instruction: dup.2d v4, x8
    let t2 = (((av_0 as u128) * (av_0 as u128)) >> 64) as u64;
    let t3 = 5075556780046548992;
    let t4 = av_0.wrapping_mul(av_1);
    // TODO: Unsupported instruction: dup.2d v5, x11
    let t3 = 1;
    let t5 = (((av_0 as u128) * (av_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x11, #18032, lsl 48
    let (t2, _carry) = t4.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x14, x13, hs
    // TODO: Unsupported instruction: dup.2d v6, x11
    let t3 = av_0.wrapping_mul(av_2);
    // TODO: Unsupported instruction: shl.2d v7, v1, #14
    // TODO: Unsupported instruction: shl.2d v8, v2, #26
    let t7 = (((av_0 as u128) * (av_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: shl.2d v9, v3, #38
    let (t6, _carry) = t3.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x16, x15, hs
    // TODO: Unsupported instruction: ushr.2d v3, v3, #14
    let t9 = av_0.wrapping_mul(av_3);
    // TODO: Unsupported instruction: shl.2d v10, v0, #2
    // TODO: Unsupported instruction: usra.2d v7, v0, #50
    let av_0 = (((av_0 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: usra.2d v8, v1, #38
    let (t8, _carry) = t9.overflowing_add(t8);
    // TODO: Unsupported instruction: cinc x20, x0, hs
    // TODO: Unsupported instruction: usra.2d v9, v2, #26
    let (t2, _carry) = t4.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x12, x13, hs
    // TODO: Unsupported instruction: and.16b v0, v10, v4
    // TODO: Unsupported instruction: and.16b v1, v7, v4
    let t5 = av_1.wrapping_mul(av_1);
    // TODO: Unsupported instruction: and.16b v2, v8, v4
    let t11 = (((av_1 as u128) * (av_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: and.16b v7, v9, v4
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x13, x21, hs
    let t11 = 13605374474286268416;
    let (t4, _carry) = t4.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    // TODO: Unsupported instruction: dup.2d v8, x21
    let t6 = 6440147467139809280;
    let t11 = av_1.wrapping_mul(av_2);
    // TODO: Unsupported instruction: dup.2d v9, x14
    let t6 = (((av_1 as u128) * (av_2 as u128)) >> 64) as u64;
    let t12 = 3688448094816436224;
    let (t5, _carry) = t11.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x23, x14, hs
    // TODO: Unsupported instruction: dup.2d v10, x22
    let t12 = 9209861237972664320;
    let (t5, _carry) = t5.overflowing_add(t8);
    // TODO: Unsupported instruction: cinc x16, x23, hs
    // TODO: Unsupported instruction: dup.2d v11, x22
    let t12 = av_1.wrapping_mul(av_3);
    let t13 = 12218265789056155648;
    let av_1 = (((av_1 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v12, x23
    let t13 = 17739678932212383744;
    let (t8, _carry) = t12.overflowing_add(t8);
    // TODO: Unsupported instruction: cinc x24, x1, hs
    // TODO: Unsupported instruction: dup.2d v13, x23
    let (t8, _carry) = t8.overflowing_add(t10);
    // TODO: Unsupported instruction: cinc x20, x24, hs
    let t13 = 2301339409586323456;
    let (t3, _carry) = t3.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x12, x15, hs
    // TODO: Unsupported instruction: dup.2d v14, x23
    let t7 = 7822752552742551552;
    let (t4, _carry) = t11.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x14, x14, hs
    // TODO: Unsupported instruction: dup.2d v15, x15
    let (t4, _carry) = t4.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    let t6 = 5071053180419178496;
    let t7 = av_2.wrapping_mul(av_2);
    // TODO: Unsupported instruction: dup.2d v16, x14
    let t6 = 16352570246982270976;
    let t11 = (((av_2 as u128) * (av_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v17, x14
    let (t5, _carry) = t7.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x21, hs
    // TODO: Unsupported instruction: ucvtf.2d v0, v0
    let (t5, _carry) = t5.overflowing_add(t8);
    // TODO: Unsupported instruction: cinc x14, x14, hs
    // TODO: Unsupported instruction: ucvtf.2d v1, v1
    let t7 = av_2.wrapping_mul(av_3);
    // TODO: Unsupported instruction: ucvtf.2d v2, v2
    // TODO: Unsupported instruction: ucvtf.2d v7, v7
    let av_2 = (((av_2 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v3, v3
    let (t6, _carry) = t7.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x16, x2, hs
    // TODO: Unsupported instruction: mov.16b v18, v5
    let (t6, _carry) = t6.overflowing_add(t10);
    // TODO: Unsupported instruction: cinc x16, x16, hs
    let t15 = av_0.mul_add(av_0, t15);
    let t16 = a1_2 - t15;
    let (t4, _carry) = t9.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x0, x0, hs
    let t16 = av_0.mul_add(av_0, t16);
    let (av_0, _carry) = t12.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    // TODO: Unsupported instruction: add.2d v10, v10, v18
    let (av_0, _carry) = av_0.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    // TODO: Unsupported instruction: add.2d v8, v8, v19
    // TODO: Unsupported instruction: mov.16b v18, v5
    let (av_1, _carry) = t7.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    let t15 = av_0.mul_add(av_1, t15);
    let (av_1, _carry) = av_1.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    let t16 = a1_2 - t15;
    let t5 = av_3.wrapping_mul(av_3);
    let t16 = av_0.mul_add(av_1, t16);
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    let av_3 = (((av_3 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v19, v19, v19
    let (av_2, _carry) = t5.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    // TODO: Unsupported instruction: add.2d v12, v12, v18
    let (av_2, _carry) = av_2.overflowing_add(t8);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    // TODO: Unsupported instruction: add.2d v10, v10, v19
    let t5 = 48718;
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t15 = av_0.mul_add(av_2, t15);
    // TODO: Unsupported instruction: movk x13, #4732, lsl 16
    let t16 = a1_2 - t15;
    // TODO: Unsupported instruction: movk x13, #45078, lsl 32
    let t16 = av_0.mul_add(av_2, t16);
    // TODO: Unsupported instruction: movk x13, #39852, lsl 48
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    // TODO: Unsupported instruction: add.2d v19, v19, v19
    let t6 = 16676;
    // TODO: Unsupported instruction: add.2d v14, v14, v18
    // TODO: Unsupported instruction: movk x14, #12692, lsl 16
    // TODO: Unsupported instruction: add.2d v12, v12, v19
    // TODO: Unsupported instruction: movk x14, #20986, lsl 32
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t15 = av_0.mul_add(a1_3, t15);
    // TODO: Unsupported instruction: movk x14, #2848, lsl 48
    let t16 = a1_2 - t15;
    let t7 = 51052;
    let t16 = av_0.mul_add(a1_3, t16);
    // TODO: Unsupported instruction: movk x15, #24721, lsl 16
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    // TODO: Unsupported instruction: add.2d v19, v19, v19
    // TODO: Unsupported instruction: movk x15, #61092, lsl 32
    // TODO: Unsupported instruction: add.2d v16, v16, v18
    // TODO: Unsupported instruction: movk x15, #45156, lsl 48
    // TODO: Unsupported instruction: add.2d v14, v14, v19
    let t8 = 3197;
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t15 = av_0.mul_add(av_3, t15);
    // TODO: Unsupported instruction: movk x16, #18936, lsl 16
    let t16 = a1_2 - t15;
    // TODO: Unsupported instruction: movk x16, #10922, lsl 32
    let t16 = av_0.mul_add(av_3, t16);
    // TODO: Unsupported instruction: movk x16, #11014, lsl 48
    // TODO: Unsupported instruction: add.2d v0, v18, v18
    let t9 = t5.wrapping_mul(t1);
    // TODO: Unsupported instruction: add.2d v18, v19, v19
    // TODO: Unsupported instruction: add.2d v0, v17, v0
    let t5 = (((t5 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v16, v16, v18
    let (t4, _carry) = t9.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    // TODO: Unsupported instruction: mov.16b v17, v5
    let t9 = t6.wrapping_mul(t1);
    let t9 = av_1.mul_add(av_1, t9);
    let t15 = a1_2 - t9;
    let t6 = (((t6 as u128) * (t1 as u128)) >> 64) as u64;
    let t15 = av_1.mul_add(av_1, t15);
    let (t5, _carry) = t9.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x14, hs
    // TODO: Unsupported instruction: add.2d v14, v14, v17
    let (av_0, _carry) = t5.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: add.2d v12, v12, v18
    // TODO: Unsupported instruction: mov.16b v17, v5
    let t6 = t7.wrapping_mul(t1);
    let t9 = av_1.mul_add(av_2, t9);
    let t7 = (((t7 as u128) * (t1 as u128)) >> 64) as u64;
    let t15 = a1_2 - t9;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x15, hs
    let t15 = av_1.mul_add(av_2, t15);
    // TODO: Unsupported instruction: add.2d v17, v17, v17
    let (av_1, _carry) = t5.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    let t6 = t8.wrapping_mul(t1);
    // TODO: Unsupported instruction: add.2d v16, v16, v17
    let t1 = (((t8 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v14, v14, v18
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: mov.16b v17, v5
    let t9 = av_1.mul_add(a1_3, t9);
    let (av_2, _carry) = t5.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    let t15 = a1_2 - t9;
    let av_3 = av_3.wrapping_add(t1);
    let t15 = av_1.mul_add(a1_3, t15);
    let t1 = 56431;
    // TODO: Unsupported instruction: add.2d v17, v17, v17
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    // TODO: Unsupported instruction: movk x9, #30457, lsl 16
    // TODO: Unsupported instruction: add.2d v0, v0, v17
    // TODO: Unsupported instruction: movk x9, #30012, lsl 32
    // TODO: Unsupported instruction: add.2d v16, v16, v18
    // TODO: Unsupported instruction: movk x9, #6382, lsl 48
    // TODO: Unsupported instruction: mov.16b v17, v5
    let t9 = av_1.mul_add(av_3, t9);
    let t5 = 59151;
    let t15 = a1_2 - t9;
    // TODO: Unsupported instruction: movk x13, #41769, lsl 16
    let t15 = av_1.mul_add(av_3, t15);
    // TODO: Unsupported instruction: movk x13, #32276, lsl 32
    // TODO: Unsupported instruction: add.2d v1, v17, v17
    // TODO: Unsupported instruction: add.2d v17, v18, v18
    // TODO: Unsupported instruction: movk x13, #21677, lsl 48
    // TODO: Unsupported instruction: add.2d v1, v15, v1
    let t6 = 34015;
    // TODO: Unsupported instruction: add.2d v0, v0, v17
    // TODO: Unsupported instruction: movk x14, #20342, lsl 16
    // TODO: Unsupported instruction: mov.16b v15, v5
    let t7 = av_2.mul_add(av_2, t7);
    // TODO: Unsupported instruction: movk x14, #13935, lsl 32
    let t9 = a1_2 - t7;
    // TODO: Unsupported instruction: movk x14, #11030, lsl 48
    let t9 = av_2.mul_add(av_2, t9);
    let t7 = 13689;
    // TODO: Unsupported instruction: add.2d v0, v0, v15
    // TODO: Unsupported instruction: movk x15, #8159, lsl 16
    // TODO: Unsupported instruction: add.2d v15, v16, v17
    // TODO: Unsupported instruction: mov.16b v16, v5
    // TODO: Unsupported instruction: movk x15, #215, lsl 32
    let t8 = av_2.mul_add(a1_3, t8);
    // TODO: Unsupported instruction: movk x15, #4913, lsl 48
    let t9 = a1_2 - t8;
    let t8 = t1.wrapping_mul(t2);
    let t9 = av_2.mul_add(a1_3, t9);
    // TODO: Unsupported instruction: add.2d v16, v16, v16
    let t1 = (((t1 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v17, v17, v17
    let (t4, _carry) = t8.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    let t8 = t5.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v0, v0, v17
    // TODO: Unsupported instruction: mov.16b v16, v5
    let t5 = (((t5 as u128) * (t2 as u128)) >> 64) as u64;
    let t8 = av_2.mul_add(av_3, t8);
    let (t1, _carry) = t8.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    let t9 = a1_2 - t8;
    let (av_0, _carry) = t1.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x9, x13, hs
    let t9 = av_2.mul_add(av_3, t9);
    // TODO: Unsupported instruction: add.2d v2, v16, v16
    let t5 = t6.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v16, v17, v17
    let t6 = (((t6 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v2, v13, v2
    let (t1, _carry) = t5.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    // TODO: Unsupported instruction: mov.16b v13, v5
    let (av_1, _carry) = t1.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x9, x13, hs
    let t5 = a1_3.mul_add(a1_3, t5);
    let t5 = t7.wrapping_mul(t2);
    let t8 = a1_2 - t5;
    let t2 = (((t7 as u128) * (t2 as u128)) >> 64) as u64;
    let t8 = a1_3.mul_add(a1_3, t8);
    let (t1, _carry) = t5.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    let (av_2, _carry) = t1.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    // TODO: Unsupported instruction: mov.16b v13, v5
    let av_3 = av_3.wrapping_add(t1);
    let t5 = a1_3.mul_add(av_3, t5);
    let t1 = 61005;
    let t8 = a1_2 - t5;
    let t8 = a1_3.mul_add(av_3, t8);
    // TODO: Unsupported instruction: movk x9, #58262, lsl 16
    // TODO: Unsupported instruction: add.2d v7, v13, v13
    // TODO: Unsupported instruction: movk x9, #32851, lsl 32
    // TODO: Unsupported instruction: add.2d v13, v16, v16
    // TODO: Unsupported instruction: movk x9, #11582, lsl 48
    // TODO: Unsupported instruction: add.2d v7, v11, v7
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    let t2 = 37581;
    // TODO: Unsupported instruction: mov.16b v11, v5
    // TODO: Unsupported instruction: movk x10, #43836, lsl 16
    let t3 = av_3.mul_add(av_3, t3);
    // TODO: Unsupported instruction: movk x10, #36286, lsl 32
    let t5 = a1_2 - t3;
    let t5 = av_3.mul_add(av_3, t5);
    // TODO: Unsupported instruction: movk x10, #51783, lsl 48
    // TODO: Unsupported instruction: add.2d v3, v9, v11
    let t5 = 10899;
    // TODO: Unsupported instruction: add.2d v7, v7, v13
    // TODO: Unsupported instruction: movk x13, #30709, lsl 16
    // TODO: Unsupported instruction: usra.2d v10, v8, #52
    // TODO: Unsupported instruction: movk x13, #61551, lsl 32
    // TODO: Unsupported instruction: usra.2d v12, v10, #52
    // TODO: Unsupported instruction: usra.2d v14, v12, #52
    // TODO: Unsupported instruction: movk x13, #45784, lsl 48
    // TODO: Unsupported instruction: usra.2d v15, v14, #52
    let t6 = 36612;
    // TODO: Unsupported instruction: and.16b v8, v8, v4
    // TODO: Unsupported instruction: movk x14, #63402, lsl 16
    // TODO: Unsupported instruction: and.16b v9, v10, v4
    // TODO: Unsupported instruction: and.16b v10, v12, v4
    // TODO: Unsupported instruction: movk x14, #47623, lsl 32
    // TODO: Unsupported instruction: and.16b v4, v14, v4
    // TODO: Unsupported instruction: movk x14, #9430, lsl 48
    // TODO: Unsupported instruction: ucvtf.2d v8, v8
    let t7 = t1.wrapping_mul(t3);
    let t8 = 37864;
    // TODO: Unsupported instruction: movk x16, #1815, lsl 16
    let t1 = (((t1 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x16, #28960, lsl 32
    let (t4, _carry) = t7.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: movk x16, #17153, lsl 48
    let t7 = t2.wrapping_mul(t3);
    // TODO: Unsupported instruction: dup.2d v11, x16
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t2 = (((t2 as u128) * (t3 as u128)) >> 64) as u64;
    let t4 = t0.mul_add(t3, t4);
    let (t1, _carry) = t7.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    let t5 = a1_2 - t4;
    let (av_0, _carry) = t1.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    let t5 = t0.mul_add(t3, t5);
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    let t2 = t5.wrapping_mul(t3);
    // TODO: Unsupported instruction: add.2d v11, v15, v13
    let t5 = (((t5 as u128) * (t3 as u128)) >> 64) as u64;
    let t7 = 46128;
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x10, x13, hs
    // TODO: Unsupported instruction: movk x15, #29964, lsl 16
    let (av_1, _carry) = t1.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    // TODO: Unsupported instruction: movk x15, #7587, lsl 32
    // TODO: Unsupported instruction: movk x15, #17161, lsl 48
    let t2 = t6.wrapping_mul(t3);
    // TODO: Unsupported instruction: dup.2d v12, x15
    let t3 = (((t6 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v13, v5
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x10, x11, hs
    let t5 = t0.mul_add(t4, t5);
    let t6 = a1_2 - t5;
    let (av_2, _carry) = t1.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    let t6 = t0.mul_add(t4, t6);
    let av_3 = av_3.wrapping_add(t1);
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    let t1 = 65535;
    // TODO: Unsupported instruction: add.2d v0, v0, v14
    let t2 = 52826;
    // TODO: Unsupported instruction: movk x9, #61439, lsl 16
    // TODO: Unsupported instruction: movk x10, #57790, lsl 16
    // TODO: Unsupported instruction: movk x9, #62867, lsl 32
    // TODO: Unsupported instruction: movk x10, #55431, lsl 32
    // TODO: Unsupported instruction: movk x9, #49889, lsl 48
    // TODO: Unsupported instruction: movk x10, #17196, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x10
    let t1 = t1.wrapping_mul(t4);
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t2 = 1;
    let t5 = t0.mul_add(t4, t5);
    // TODO: Unsupported instruction: movk x10, #61440, lsl 16
    let t6 = a1_2 - t5;
    // TODO: Unsupported instruction: movk x10, #62867, lsl 32
    let t6 = t0.mul_add(t4, t6);
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    // TODO: Unsupported instruction: movk x10, #17377, lsl 48
    // TODO: Unsupported instruction: add.2d v1, v1, v14
    let t3 = 28817;
    let t5 = 31276;
    // TODO: Unsupported instruction: movk x11, #31161, lsl 16
    // TODO: Unsupported instruction: movk x13, #21262, lsl 16
    // TODO: Unsupported instruction: movk x13, #2304, lsl 32
    // TODO: Unsupported instruction: movk x11, #59464, lsl 32
    // TODO: Unsupported instruction: movk x13, #17182, lsl 48
    // TODO: Unsupported instruction: movk x11, #10291, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x13
    let t5 = 22621;
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t5 = t0.mul_add(t4, t5);
    // TODO: Unsupported instruction: movk x13, #33153, lsl 16
    let t6 = a1_2 - t5;
    // TODO: Unsupported instruction: movk x13, #17846, lsl 32
    let t6 = t0.mul_add(t4, t6);
    // TODO: Unsupported instruction: movk x13, #47184, lsl 48
    // TODO: Unsupported instruction: add.2d v7, v7, v13
    // TODO: Unsupported instruction: add.2d v2, v2, v14
    let t6 = 41001;
    let t7 = 28672;
    // TODO: Unsupported instruction: movk x14, #57649, lsl 16
    // TODO: Unsupported instruction: movk x15, #24515, lsl 16
    // TODO: Unsupported instruction: movk x14, #20082, lsl 32
    // TODO: Unsupported instruction: movk x15, #54929, lsl 32
    // TODO: Unsupported instruction: movk x15, #17064, lsl 48
    // TODO: Unsupported instruction: movk x14, #12388, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x15
    let t7 = t2.wrapping_mul(t1);
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t2 = (((t2 as u128) * (t1 as u128)) >> 64) as u64;
    let t5 = t0.mul_add(t4, t5);
    // TODO: Unsupported instruction: cmn x15, x12
    // TODO: Unsupported instruction: cinc x10, x10, hs
    let t6 = a1_2 - t5;
    let t6 = t0.mul_add(t4, t6);
    let t4 = t3.wrapping_mul(t1);
    // TODO: Unsupported instruction: add.2d v3, v3, v13
    let t3 = (((t3 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v7, v7, v14
    let (t2, _carry) = t4.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x11, x11, hs
    // TODO: Unsupported instruction: ucvtf.2d v8, v9
    let t4 = 44768;
    let (av_0, _carry) = t2.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x10, x11, hs
    // TODO: Unsupported instruction: movk x12, #51919, lsl 16
    let t3 = t5.wrapping_mul(t1);
    // TODO: Unsupported instruction: movk x12, #6346, lsl 32
    let t5 = (((t5 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x12, #17133, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x12
    let (t2, _carry) = t3.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x11, x13, hs
    // TODO: Unsupported instruction: mov.16b v12, v5
    let (av_1, _carry) = t2.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x10, x11, hs
    let t4 = t0.mul_add(t1, t4);
    let t3 = t6.wrapping_mul(t1);
    let t5 = a1_2 - t4;
    let t5 = t0.mul_add(t1, t5);
    let t1 = (((t6 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    let (t2, _carry) = t3.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: add.2d v9, v11, v13
    let (av_2, _carry) = t2.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    let t2 = 47492;
    // TODO: Unsupported instruction: movk x10, #23630, lsl 16
    let av_3 = av_3.wrapping_add(t1);
    // TODO: Unsupported instruction: movk x10, #49985, lsl 32
    let t1 = a1_0.wrapping_mul(a1_0);
    // TODO: Unsupported instruction: movk x10, #17168, lsl 48
    let t3 = (((a1_0 as u128) * (a1_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v11, x10
    let t2 = a1_0.wrapping_mul(a1_1);
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t4 = t0.mul_add(t3, t4);
    let t4 = (((a1_0 as u128) * (a1_1 as u128)) >> 64) as u64;
    let t5 = a1_2 - t4;
    let (t3, _carry) = t2.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x13, x12, hs
    let t5 = t0.mul_add(t3, t5);
    let t6 = a1_0.wrapping_mul(a1_2);
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    // TODO: Unsupported instruction: add.2d v0, v0, v13
    let t7 = (((a1_0 as u128) * (a1_2 as u128)) >> 64) as u64;
    let t8 = 57936;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x17, x15, hs
    // TODO: Unsupported instruction: movk x16, #54828, lsl 16
    let t10 = a1_0.wrapping_mul(a1_3);
    // TODO: Unsupported instruction: movk x16, #18292, lsl 32
    // TODO: Unsupported instruction: movk x16, #17197, lsl 48
    let a1_0 = (((a1_0 as u128) * (a1_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v11, x16
    let (t8, _carry) = t10.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x17, x4, hs
    // TODO: Unsupported instruction: mov.16b v12, v5
    let (t2, _carry) = t2.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x11, x12, hs
    let t4 = t0.mul_add(t3, t4);
    let t5 = a1_2 - t4;
    let t4 = a1_1.wrapping_mul(a1_1);
    let t5 = t0.mul_add(t3, t5);
    let t11 = (((a1_1 as u128) * (a1_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    let (t3, _carry) = t4.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x12, x21, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    let (t3, _carry) = t3.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x12, x12, hs
    let t5 = 17708;
    // TODO: Unsupported instruction: movk x13, #43915, lsl 16
    let t11 = a1_1.wrapping_mul(a1_2);
    // TODO: Unsupported instruction: movk x13, #64348, lsl 32
    let t12 = (((a1_1 as u128) * (a1_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x13, #17188, lsl 48
    let (t4, _carry) = t11.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x23, x22, hs
    // TODO: Unsupported instruction: dup.2d v11, x13
    // TODO: Unsupported instruction: mov.16b v12, v5
    let (t4, _carry) = t4.overflowing_add(t8);
    // TODO: Unsupported instruction: cinc x13, x23, hs
    let t4 = t0.mul_add(t3, t4);
    let t8 = a1_1.wrapping_mul(a1_3);
    let t5 = a1_2 - t4;
    let a1_1 = (((a1_1 as u128) * (a1_3 as u128)) >> 64) as u64;
    let t5 = t0.mul_add(t3, t5);
    // TODO: Unsupported instruction: add.2d v7, v7, v12
    let (t5, _carry) = t8.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x23, x5, hs
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    let (t5, _carry) = t5.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x17, x23, hs
    let t13 = 29184;
    let (t3, _carry) = t6.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x14, x15, hs
    // TODO: Unsupported instruction: movk x23, #20789, lsl 16
    // TODO: Unsupported instruction: movk x23, #19197, lsl 32
    let (t6, _carry) = t11.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x15, x22, hs
    // TODO: Unsupported instruction: movk x23, #17083, lsl 48
    let (t4, _carry) = t6.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x14, x15, hs
    // TODO: Unsupported instruction: dup.2d v11, x23
    let t7 = a1_2.wrapping_mul(a1_2);
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t4 = t0.mul_add(t3, t4);
    let t11 = (((a1_2 as u128) * (a1_2 as u128)) >> 64) as u64;
    let t5 = a1_2 - t4;
    let (t6, _carry) = t7.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x15, x21, hs
    let t5 = t0.mul_add(t3, t5);
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x15, hs
    // TODO: Unsupported instruction: add.2d v3, v3, v12
    let t7 = a1_2.wrapping_mul(a1_3);
    // TODO: Unsupported instruction: add.2d v7, v7, v13
    // TODO: Unsupported instruction: ucvtf.2d v8, v10
    let a1_2 = (((a1_2 as u128) * (a1_3 as u128)) >> 64) as u64;
    let t11 = 58856;
    let (t6, _carry) = t7.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x22, x6, hs
    // TODO: Unsupported instruction: movk x21, #14953, lsl 16
    let (t6, _carry) = t6.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x17, x22, hs
    // TODO: Unsupported instruction: movk x21, #15155, lsl 32
    // TODO: Unsupported instruction: movk x21, #17181, lsl 48
    let (t4, _carry) = t10.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: dup.2d v10, x21
    let (a1_0, _carry) = t8.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: mov.16b v11, v5
    let (a1_0, _carry) = a1_0.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t3 = t0.mul_add(t2, t3);
    let t4 = a1_2 - t3;
    let (a1_1, _carry) = t7.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    let t4 = t0.mul_add(t2, t4);
    let (a1_1, _carry) = a1_1.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    let t5 = a1_3.wrapping_mul(a1_3);
    // TODO: Unsupported instruction: add.2d v9, v9, v12
    let t6 = 35392;
    let a1_3 = (((a1_3 as u128) * (a1_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x14, #12477, lsl 16
    let (a1_2, _carry) = t5.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x7, x7, hs
    // TODO: Unsupported instruction: movk x14, #56780, lsl 32
    let (a1_2, _carry) = a1_2.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x7, x7, hs
    // TODO: Unsupported instruction: movk x14, #17142, lsl 48
    let t5 = 48718;
    // TODO: Unsupported instruction: dup.2d v10, x14
    // TODO: Unsupported instruction: mov.16b v11, v5
    // TODO: Unsupported instruction: movk x13, #4732, lsl 16
    let t3 = t0.mul_add(t2, t3);
    // TODO: Unsupported instruction: movk x13, #45078, lsl 32
    let t4 = a1_2 - t3;
    // TODO: Unsupported instruction: movk x13, #39852, lsl 48
    let t4 = t0.mul_add(t2, t4);
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    let t6 = 16676;
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    // TODO: Unsupported instruction: movk x14, #12692, lsl 16
    let t7 = 9848;
    // TODO: Unsupported instruction: movk x14, #20986, lsl 32
    // TODO: Unsupported instruction: movk x15, #54501, lsl 16
    // TODO: Unsupported instruction: movk x15, #31540, lsl 32
    // TODO: Unsupported instruction: movk x14, #2848, lsl 48
    // TODO: Unsupported instruction: movk x15, #17170, lsl 48
    let t8 = 51052;
    // TODO: Unsupported instruction: dup.2d v10, x15
    // TODO: Unsupported instruction: movk x16, #24721, lsl 16
    // TODO: Unsupported instruction: mov.16b v11, v5
    let t3 = t0.mul_add(t2, t3);
    // TODO: Unsupported instruction: movk x16, #61092, lsl 32
    let t4 = a1_2 - t3;
    // TODO: Unsupported instruction: movk x16, #45156, lsl 48
    let t4 = t0.mul_add(t2, t4);
    let t7 = 3197;
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    // TODO: Unsupported instruction: movk x15, #18936, lsl 16
    let t9 = 9584;
    // TODO: Unsupported instruction: movk x15, #10922, lsl 32
    // TODO: Unsupported instruction: movk x17, #63883, lsl 16
    // TODO: Unsupported instruction: movk x15, #11014, lsl 48
    // TODO: Unsupported instruction: movk x17, #18253, lsl 32
    let t10 = t5.wrapping_mul(t1);
    // TODO: Unsupported instruction: movk x17, #17190, lsl 48
    // TODO: Unsupported instruction: dup.2d v10, x17
    let t5 = (((t5 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v11, v5
    let (t4, _carry) = t10.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    let t3 = t0.mul_add(t2, t3);
    let t9 = t6.wrapping_mul(t1);
    let t4 = a1_2 - t3;
    let t4 = t0.mul_add(t2, t4);
    let t6 = (((t6 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v7, v7, v11
    let (t5, _carry) = t9.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x14, hs
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    let (a1_0, _carry) = t5.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    let t6 = 51712;
    // TODO: Unsupported instruction: movk x14, #16093, lsl 16
    let t9 = t8.wrapping_mul(t1);
    // TODO: Unsupported instruction: movk x14, #30633, lsl 32
    let t8 = (((t8 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x14, #17068, lsl 48
    let (t5, _carry) = t9.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x16, x16, hs
    // TODO: Unsupported instruction: dup.2d v10, x14
    // TODO: Unsupported instruction: mov.16b v11, v5
    let (a1_1, _carry) = t5.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x13, x16, hs
    let t3 = t0.mul_add(t2, t3);
    let t6 = t7.wrapping_mul(t1);
    let t4 = a1_2 - t3;
    let t1 = (((t7 as u128) * (t1 as u128)) >> 64) as u64;
    let t4 = t0.mul_add(t2, t4);
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: add.2d v3, v3, v11
    // TODO: Unsupported instruction: add.2d v7, v7, v12
    let (a1_2, _carry) = t5.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: ucvtf.2d v4, v4
    let a1_3 = a1_3.wrapping_add(t1);
    let t1 = 34724;
    let t5 = 56431;
    // TODO: Unsupported instruction: movk x9, #40393, lsl 16
    // TODO: Unsupported instruction: movk x9, #23752, lsl 32
    // TODO: Unsupported instruction: movk x13, #30457, lsl 16
    // TODO: Unsupported instruction: movk x9, #17184, lsl 48
    // TODO: Unsupported instruction: movk x13, #30012, lsl 32
    // TODO: Unsupported instruction: dup.2d v8, x9
    // TODO: Unsupported instruction: movk x13, #6382, lsl 48
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t2 = a1_0.mul_add(t0, t2);
    let t1 = 59151;
    let t3 = a1_2 - t2;
    // TODO: Unsupported instruction: movk x9, #41769, lsl 16
    let t3 = a1_0.mul_add(t0, t3);
    // TODO: Unsupported instruction: movk x9, #32276, lsl 32
    // TODO: Unsupported instruction: add.2d v0, v0, v10
    // TODO: Unsupported instruction: add.2d v8, v9, v11
    // TODO: Unsupported instruction: movk x9, #21677, lsl 48
    let t6 = 25532;
    let t7 = 34015;
    // TODO: Unsupported instruction: movk x14, #31025, lsl 16
    // TODO: Unsupported instruction: movk x15, #20342, lsl 16
    // TODO: Unsupported instruction: movk x14, #10002, lsl 32
    // TODO: Unsupported instruction: movk x14, #17199, lsl 48
    // TODO: Unsupported instruction: movk x15, #13935, lsl 32
    // TODO: Unsupported instruction: dup.2d v9, x14
    // TODO: Unsupported instruction: movk x15, #11030, lsl 48
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t6 = 13689;
    let t2 = a1_0.mul_add(t1, t2);
    // TODO: Unsupported instruction: movk x14, #8159, lsl 16
    let t3 = a1_2 - t2;
    let t3 = a1_0.mul_add(t1, t3);
    // TODO: Unsupported instruction: movk x14, #215, lsl 32
    // TODO: Unsupported instruction: add.2d v1, v1, v10
    // TODO: Unsupported instruction: movk x14, #4913, lsl 48
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    let t8 = t5.wrapping_mul(t2);
    let t9 = 18830;
    // TODO: Unsupported instruction: movk x17, #2465, lsl 16
    let t5 = (((t5 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x17, #36348, lsl 32
    let (t4, _carry) = t8.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    // TODO: Unsupported instruction: movk x17, #17194, lsl 48
    let t8 = t1.wrapping_mul(t2);
    // TODO: Unsupported instruction: dup.2d v9, x17
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t1 = (((t1 as u128) * (t2 as u128)) >> 64) as u64;
    let t2 = a1_0.mul_add(t1, t2);
    let (t5, _carry) = t8.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    let t3 = a1_2 - t2;
    let (a1_0, _carry) = t5.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    let t3 = a1_0.mul_add(t1, t3);
    // TODO: Unsupported instruction: add.2d v2, v2, v10
    let t5 = t7.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    let t7 = (((t7 as u128) * (t2 as u128)) >> 64) as u64;
    let t8 = 21566;
    let (t1, _carry) = t5.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x13, x15, hs
    // TODO: Unsupported instruction: movk x16, #43708, lsl 16
    // TODO: Unsupported instruction: movk x16, #57685, lsl 32
    let (a1_1, _carry) = t1.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x9, x13, hs
    // TODO: Unsupported instruction: movk x16, #17185, lsl 48
    let t5 = t6.wrapping_mul(t2);
    // TODO: Unsupported instruction: dup.2d v9, x16
    let t2 = (((t6 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v10, v5
    let (t1, _carry) = t5.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    let t2 = a1_0.mul_add(t1, t2);
    let t3 = a1_2 - t2;
    let (a1_2, _carry) = t1.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    let t3 = a1_0.mul_add(t1, t3);
    let a1_3 = a1_3.wrapping_add(t1);
    // TODO: Unsupported instruction: add.2d v7, v7, v10
    let t1 = 61005;
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    let t2 = 3072;
    // TODO: Unsupported instruction: movk x9, #58262, lsl 16
    // TODO: Unsupported instruction: movk x10, #8058, lsl 16
    // TODO: Unsupported instruction: movk x9, #32851, lsl 32
    // TODO: Unsupported instruction: movk x10, #46097, lsl 32
    // TODO: Unsupported instruction: movk x9, #11582, lsl 48
    // TODO: Unsupported instruction: movk x10, #17047, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x10
    let t2 = 37581;
    // TODO: Unsupported instruction: mov.16b v10, v5
    // TODO: Unsupported instruction: movk x10, #43836, lsl 16
    let t2 = a1_0.mul_add(t1, t2);
    // TODO: Unsupported instruction: movk x10, #36286, lsl 32
    let t3 = a1_2 - t2;
    let t3 = a1_0.mul_add(t1, t3);
    // TODO: Unsupported instruction: movk x10, #51783, lsl 48
    // TODO: Unsupported instruction: add.2d v3, v3, v10
    let t5 = 10899;
    // TODO: Unsupported instruction: add.2d v4, v7, v11
    // TODO: Unsupported instruction: movk x13, #30709, lsl 16
    let t6 = 65535;
    // TODO: Unsupported instruction: movk x13, #61551, lsl 32
    // TODO: Unsupported instruction: movk x14, #61439, lsl 16
    // TODO: Unsupported instruction: movk x14, #62867, lsl 32
    // TODO: Unsupported instruction: movk x13, #45784, lsl 48
    // TODO: Unsupported instruction: movk x14, #1, lsl 48
    let t7 = 36612;
    // TODO: Unsupported instruction: umov x16, v8.d[0]
    // TODO: Unsupported instruction: movk x15, #63402, lsl 16
    // TODO: Unsupported instruction: umov x17, v8.d[1]
    let t8 = t8.wrapping_mul(t6);
    // TODO: Unsupported instruction: movk x15, #47623, lsl 32
    let t6 = t9.wrapping_mul(t6);
    // TODO: Unsupported instruction: movk x15, #9430, lsl 48
    let t8 = t8 & t0;
    let t9 = t1.wrapping_mul(t3);
    let t0 = t6 & t0;
    // TODO: Unsupported instruction: ins v7.d[0], x16
    // TODO: Unsupported instruction: ins v7.d[1], x8
    let t0 = (((t1 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v7, v7
    let (t1, _carry) = t9.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x8, x8, hs
    let t4 = 16;
    let t6 = t2.wrapping_mul(t3);
    // TODO: Unsupported instruction: movk x12, #22847, lsl 32
    // TODO: Unsupported instruction: movk x12, #17151, lsl 48
    let t2 = (((t2 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v9, x12
    let (t0, _carry) = t6.overflowing_add(t0);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    // TODO: Unsupported instruction: mov.16b v10, v5
    let (a1_0, _carry) = t0.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x8, x10, hs
    let t2 = a1_3.mul_add(t1, t2);
    let t3 = a1_2 - t2;
    let t2 = t5.wrapping_mul(t3);
    let t3 = a1_3.mul_add(t1, t3);
    let t4 = (((t5 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v0, v0, v10
    let (t0, _carry) = t2.overflowing_add(t0);
    // TODO: Unsupported instruction: cinc x10, x12, hs
    // TODO: Unsupported instruction: add.2d v8, v8, v11
    let (a1_1, _carry) = t0.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x8, x10, hs
    let t2 = 20728;
    // TODO: Unsupported instruction: movk x10, #23588, lsl 16
    let t4 = t7.wrapping_mul(t3);
    // TODO: Unsupported instruction: movk x10, #7790, lsl 32
    let t3 = (((t7 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x10, #17170, lsl 48
    let (t0, _carry) = t4.overflowing_add(t0);
    // TODO: Unsupported instruction: cinc x11, x11, hs
    // TODO: Unsupported instruction: dup.2d v9, x10
    // TODO: Unsupported instruction: mov.16b v10, v5
    let (a1_2, _carry) = t0.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x8, x11, hs
    let t2 = a1_3.mul_add(t1, t2);
    let a1_3 = a1_3.wrapping_add(t0);
    let t3 = a1_2 - t2;
    let t0 = 65535;
    let t3 = a1_3.mul_add(t1, t3);
    // TODO: Unsupported instruction: add.2d v1, v1, v10
    // TODO: Unsupported instruction: movk x8, #61439, lsl 16
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    // TODO: Unsupported instruction: movk x8, #62867, lsl 32
    let t2 = 16000;
    // TODO: Unsupported instruction: movk x8, #49889, lsl 48
    // TODO: Unsupported instruction: movk x10, #53891, lsl 16
    // TODO: Unsupported instruction: movk x10, #5509, lsl 32
    let t0 = t0.wrapping_mul(t1);
    // TODO: Unsupported instruction: movk x10, #17144, lsl 48
    let t3 = 1;
    // TODO: Unsupported instruction: dup.2d v9, x10
    // TODO: Unsupported instruction: movk x11, #61440, lsl 16
    // TODO: Unsupported instruction: mov.16b v10, v5
    // TODO: Unsupported instruction: movk x11, #62867, lsl 32
    let t2 = a1_3.mul_add(t1, t2);
    let t3 = a1_2 - t2;
    // TODO: Unsupported instruction: movk x11, #17377, lsl 48
    let t3 = a1_3.mul_add(t1, t3);
    let t2 = 28817;
    // TODO: Unsupported instruction: add.2d v2, v2, v10
    // TODO: Unsupported instruction: movk x10, #31161, lsl 16
    // TODO: Unsupported instruction: add.2d v9, v1, v11
    let t4 = 46800;
    // TODO: Unsupported instruction: movk x10, #59464, lsl 32
    // TODO: Unsupported instruction: movk x12, #2568, lsl 16
    // TODO: Unsupported instruction: movk x10, #10291, lsl 48
    // TODO: Unsupported instruction: movk x12, #1335, lsl 32
    let t5 = 22621;
    // TODO: Unsupported instruction: movk x12, #17188, lsl 48
    // TODO: Unsupported instruction: dup.2d v1, x12
    // TODO: Unsupported instruction: movk x13, #33153, lsl 16
    // TODO: Unsupported instruction: mov.16b v10, v5
    // TODO: Unsupported instruction: movk x13, #17846, lsl 32
    let t2 = a1_3.mul_add(av_1, t2);
    // TODO: Unsupported instruction: movk x13, #47184, lsl 48
    let t3 = a1_2 - t2;
    let t3 = a1_3.mul_add(av_1, t3);
    let t4 = 41001;
    // TODO: Unsupported instruction: add.2d v1, v4, v10
    // TODO: Unsupported instruction: movk x12, #57649, lsl 16
    // TODO: Unsupported instruction: add.2d v4, v2, v11
    // TODO: Unsupported instruction: movk x12, #20082, lsl 32
    let t6 = 39040;
    // TODO: Unsupported instruction: movk x14, #14704, lsl 16
    // TODO: Unsupported instruction: movk x12, #12388, lsl 48
    // TODO: Unsupported instruction: movk x14, #12839, lsl 32
    let t7 = t3.wrapping_mul(t0);
    // TODO: Unsupported instruction: movk x14, #17096, lsl 48
    let t3 = (((t3 as u128) * (t0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v2, x14
    // TODO: Unsupported instruction: cmn x15, x9
    // TODO: Unsupported instruction: cinc x11, x11, hs
    // TODO: Unsupported instruction: mov.16b v5, v5
    let a1_1 = a1_3.mul_add(av_2, a1_1);
    let t1 = t2.wrapping_mul(t0);
    let a1_2 = a1_2 - a1_1;
    let t2 = (((t2 as u128) * (t0 as u128)) >> 64) as u64;
    let a1_2 = a1_3.mul_add(av_2, a1_2);
    let (t1, _carry) = t1.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    // TODO: Unsupported instruction: add.2d v5, v3, v5
    // TODO: Unsupported instruction: add.2d v6, v1, v6
    let (a1_0, _carry) = t1.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    // TODO: Unsupported instruction: ssra.2d v0, v8, #52
    let t2 = t5.wrapping_mul(t0);
    // TODO: Unsupported instruction: ssra.2d v9, v0, #52
    let t3 = (((t5 as u128) * (t0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ssra.2d v4, v9, #52
    // TODO: Unsupported instruction: ssra.2d v6, v4, #52
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x10, x11, hs
    // TODO: Unsupported instruction: ssra.2d v5, v6, #52
    let (a1_1, _carry) = t1.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    // TODO: Unsupported instruction: ushr.2d v1, v9, #12
    let t2 = t4.wrapping_mul(t0);
    // TODO: Unsupported instruction: ushr.2d v2, v4, #24
    // TODO: Unsupported instruction: ushr.2d v3, v6, #36
    let t0 = (((t4 as u128) * (t0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: sli.2d v0, v9, #52
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x8, x8, hs
    // TODO: Unsupported instruction: sli.2d v1, v4, #40
    let (a1_2, _carry) = t1.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x8, x8, hs
    // TODO: Unsupported instruction: sli.2d v2, v6, #28
    // TODO: Unsupported instruction: sli.2d v3, v5, #16
    let a1_3 = a1_3.wrapping_add(t0);

    let out = [av_0, av_1, av_2, av_3];
    let out1 = [a1_0, a1_1, a1_2, a1_3];
    let outv = [av_0, av_1, av_2, av_3];

    (out, out1, outv)
}
