// GENERATED FILE, DO NOT EDIT!
// Generated by HLA framework for WASM SIMD optimization
// Note: Imports are in the parent module (mod.rs)

#[inline(always)]
pub fn montgomery_interleaved_4(
    _guard: &RoundingGuard<Zero>,
    a: [u64; 4],
    b: [u64; 4],
    a1: [u64; 4],
    b1: [u64; 4],
    av: [Simd<u64, 2>; 4],
    bv: [Simd<u64, 2>; 4]
) -> ([u64; 4], [u64; 4], [Simd<u64, 2>; 4]) {
    let a_0 = a[0];
    let a_1 = a[1];
    let a_2 = a[2];
    let a_3 = a[3];
    let b_0 = b[0];
    let b_1 = b[1];
    let b_2 = b[2];
    let b_3 = b[3];
    let a1_0 = a1[0];
    let a1_1 = a1[1];
    let a1_2 = a1[2];
    let a1_3 = a1[3];
    let b1_0 = b1[0];
    let b1_1 = b1[1];
    let b1_2 = b1[2];
    let b1_3 = b1[3];
    let av_0 = av[0];
    let av_1 = av[1];
    let av_2 = av[2];
    let av_3 = av[3];
    let bv_0 = bv[0];
    let bv_1 = bv[1];
    let bv_2 = bv[2];
    let bv_3 = bv[3];

    let t0 = 4503599627370495;
    let t1 = av_0.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: dup.2d v8, x16
    let t2 = (((av_0 as u128) * (bv_0 as u128)) >> 64) as u64;
    let t3 = 5075556780046548992;
    // TODO: Unsupported instruction: dup.2d v9, x21
    let t3 = av_1.wrapping_mul(bv_0);
    let t4 = 1;
    let t5 = (((av_1 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x22, #18032, lsl 48
    let (t2, _carry) = t3.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x21, x23, hs
    // TODO: Unsupported instruction: dup.2d v10, x22
    // TODO: Unsupported instruction: shl.2d v11, v1, #14
    let t4 = av_2.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: shl.2d v12, v2, #26
    let t5 = (((av_2 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: shl.2d v13, v3, #38
    // TODO: Unsupported instruction: ushr.2d v3, v3, #14
    let (t3, _carry) = t4.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x22, x23, hs
    // TODO: Unsupported instruction: shl.2d v14, v0, #2
    let t5 = av_3.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: usra.2d v11, v0, #50
    let bv_0 = (((av_3 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: usra.2d v12, v1, #38
    // TODO: Unsupported instruction: usra.2d v13, v2, #26
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: and.16b v0, v14, v8
    let t5 = av_0.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: and.16b v1, v11, v8
    let t6 = (((av_0 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: and.16b v2, v12, v8
    // TODO: Unsupported instruction: and.16b v11, v13, v8
    let (t2, _carry) = t5.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x23, x24, hs
    // TODO: Unsupported instruction: shl.2d v12, v5, #14
    let t6 = av_1.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: shl.2d v13, v6, #26
    // TODO: Unsupported instruction: shl.2d v14, v7, #38
    let t7 = (((av_1 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ushr.2d v7, v7, #14
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x24, x25, hs
    // TODO: Unsupported instruction: shl.2d v15, v4, #2
    let (t3, _carry) = t5.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x23, x24, hs
    // TODO: Unsupported instruction: usra.2d v12, v4, #50
    // TODO: Unsupported instruction: usra.2d v13, v5, #38
    let t6 = av_2.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: usra.2d v14, v6, #26
    let t7 = (((av_2 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: and.16b v4, v15, v8
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x24, x25, hs
    // TODO: Unsupported instruction: and.16b v5, v12, v8
    // TODO: Unsupported instruction: and.16b v6, v13, v8
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x23, x24, hs
    // TODO: Unsupported instruction: and.16b v12, v14, v8
    let t6 = av_3.wrapping_mul(bv_1);
    let t7 = 13605374474286268416;
    // TODO: Unsupported instruction: dup.2d v13, x25
    let bv_1 = (((av_3 as u128) * (bv_1 as u128)) >> 64) as u64;
    let t7 = 6440147467139809280;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: dup.2d v14, x25
    let (bv_0, _carry) = t5.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t5 = 3688448094816436224;
    // TODO: Unsupported instruction: dup.2d v15, x23
    let t5 = av_0.wrapping_mul(bv_2);
    let t6 = 9209861237972664320;
    let t7 = (((av_0 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v16, x24
    let (t3, _carry) = t5.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x23, x25, hs
    let t6 = 12218265789056155648;
    // TODO: Unsupported instruction: dup.2d v17, x24
    let t6 = av_1.wrapping_mul(bv_2);
    let t7 = 17739678932212383744;
    let t8 = (((av_1 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v18, x25
    let t7 = 2301339409586323456;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x24, x26, hs
    // TODO: Unsupported instruction: dup.2d v19, x25
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x23, x24, hs
    let t6 = 7822752552742551552;
    let t7 = av_2.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: dup.2d v20, x24
    let t6 = 5071053180419178496;
    let t8 = (((av_2 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v21, x24
    let (t5, _carry) = t7.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x24, x26, hs
    let t7 = 16352570246982270976;
    let (bv_0, _carry) = t5.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x23, x24, hs
    // TODO: Unsupported instruction: dup.2d v22, x25
    // TODO: Unsupported instruction: ucvtf.2d v0, v0
    let t6 = av_3.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: ucvtf.2d v1, v1
    let bv_2 = (((av_3 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v2, v2
    // TODO: Unsupported instruction: ucvtf.2d v11, v11
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: ucvtf.2d v3, v3
    let (bv_1, _carry) = t5.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: ucvtf.2d v4, v4
    let t5 = av_0.wrapping_mul(bv_3);
    // TODO: Unsupported instruction: ucvtf.2d v5, v5
    // TODO: Unsupported instruction: ucvtf.2d v6, v6
    let av_0 = (((av_0 as u128) * (bv_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v12, v12
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x0, x0, hs
    // TODO: Unsupported instruction: ucvtf.2d v7, v7
    // TODO: Unsupported instruction: mov.16b v23, v9
    let t5 = av_1.wrapping_mul(bv_3);
    let t5 = av_0.mul_add(bv_0, t5);
    let av_1 = (((av_1 as u128) * (bv_3 as u128)) >> 64) as u64;
    let t6 = a1_2 - t5;
    let (av_0, _carry) = t5.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    let t6 = av_0.mul_add(bv_0, t6);
    // TODO: Unsupported instruction: add.2d v15, v15, v23
    let (av_0, _carry) = av_0.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    // TODO: Unsupported instruction: add.2d v13, v13, v24
    let bv_0 = av_2.wrapping_mul(bv_3);
    // TODO: Unsupported instruction: mov.16b v23, v9
    let av_2 = (((av_2 as u128) * (bv_3 as u128)) >> 64) as u64;
    let t5 = av_0.mul_add(bv_1, t5);
    let t6 = a1_2 - t5;
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    let t6 = av_0.mul_add(bv_1, t6);
    let (av_1, _carry) = av_1.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    // TODO: Unsupported instruction: add.2d v17, v17, v23
    // TODO: Unsupported instruction: add.2d v15, v15, v24
    let bv_0 = av_3.wrapping_mul(bv_3);
    // TODO: Unsupported instruction: mov.16b v23, v9
    let av_3 = (((av_3 as u128) * (bv_3 as u128)) >> 64) as u64;
    let t5 = av_0.mul_add(bv_2, t5);
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    let t6 = a1_2 - t5;
    let t6 = av_0.mul_add(bv_2, t6);
    let (av_2, _carry) = av_2.overflowing_add(bv_2);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    // TODO: Unsupported instruction: add.2d v19, v19, v23
    let bv_0 = 48718;
    // TODO: Unsupported instruction: add.2d v17, v17, v24
    // TODO: Unsupported instruction: movk x4, #4732, lsl 16
    // TODO: Unsupported instruction: mov.16b v23, v9
    let t5 = av_0.mul_add(b1_0, t5);
    // TODO: Unsupported instruction: movk x4, #45078, lsl 32
    let t6 = a1_2 - t5;
    // TODO: Unsupported instruction: movk x4, #39852, lsl 48
    let t6 = av_0.mul_add(b1_0, t6);
    // TODO: Unsupported instruction: add.2d v21, v21, v23
    let bv_1 = 16676;
    // TODO: Unsupported instruction: add.2d v19, v19, v24
    // TODO: Unsupported instruction: movk x5, #12692, lsl 16
    // TODO: Unsupported instruction: mov.16b v23, v9
    // TODO: Unsupported instruction: movk x5, #20986, lsl 32
    let t5 = av_0.mul_add(bv_3, t5);
    let t6 = a1_2 - t5;
    // TODO: Unsupported instruction: movk x5, #2848, lsl 48
    let t6 = av_0.mul_add(bv_3, t6);
    let bv_2 = 51052;
    // TODO: Unsupported instruction: add.2d v0, v22, v23
    // TODO: Unsupported instruction: movk x6, #24721, lsl 16
    // TODO: Unsupported instruction: add.2d v21, v21, v24
    // TODO: Unsupported instruction: mov.16b v22, v9
    // TODO: Unsupported instruction: movk x6, #61092, lsl 32
    let t4 = av_1.mul_add(bv_0, t4);
    // TODO: Unsupported instruction: movk x6, #45156, lsl 48
    let t5 = a1_2 - t4;
    let t5 = av_1.mul_add(bv_0, t5);
    let bv_3 = 3197;
    // TODO: Unsupported instruction: add.2d v17, v17, v22
    // TODO: Unsupported instruction: movk x7, #18936, lsl 16
    // TODO: Unsupported instruction: add.2d v15, v15, v23
    // TODO: Unsupported instruction: movk x7, #10922, lsl 32
    // TODO: Unsupported instruction: mov.16b v22, v9
    let t4 = av_1.mul_add(bv_1, t4);
    // TODO: Unsupported instruction: movk x7, #11014, lsl 48
    let t5 = a1_2 - t4;
    let t5 = bv_0.wrapping_mul(t1);
    let t5 = av_1.mul_add(bv_1, t5);
    let bv_0 = (((bv_0 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v19, v19, v22
    // TODO: Unsupported instruction: add.2d v17, v17, v23
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: mov.16b v22, v9
    let t5 = bv_1.wrapping_mul(t1);
    let t4 = av_1.mul_add(bv_2, t4);
    let t5 = a1_2 - t4;
    let bv_1 = (((bv_1 as u128) * (t1 as u128)) >> 64) as u64;
    let t5 = av_1.mul_add(bv_2, t5);
    let (bv_0, _carry) = t5.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: add.2d v21, v21, v22
    let (av_0, _carry) = bv_0.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    // TODO: Unsupported instruction: add.2d v19, v19, v23
    // TODO: Unsupported instruction: mov.16b v22, v9
    let bv_1 = bv_2.wrapping_mul(t1);
    let t4 = av_1.mul_add(b1_0, t4);
    let bv_2 = (((bv_2 as u128) * (t1 as u128)) >> 64) as u64;
    let t5 = a1_2 - t4;
    let t5 = av_1.mul_add(b1_0, t5);
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    // TODO: Unsupported instruction: add.2d v0, v0, v22
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    // TODO: Unsupported instruction: add.2d v21, v21, v23
    let bv_1 = bv_3.wrapping_mul(t1);
    // TODO: Unsupported instruction: mov.16b v22, v9
    let t4 = av_1.mul_add(bv_3, t4);
    let bv_2 = (((bv_3 as u128) * (t1 as u128)) >> 64) as u64;
    let t5 = a1_2 - t4;
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t5 = av_1.mul_add(bv_3, t5);
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    // TODO: Unsupported instruction: add.2d v1, v20, v22
    // TODO: Unsupported instruction: add.2d v0, v0, v23
    let av_3 = av_3.wrapping_add(bv_0);
    // TODO: Unsupported instruction: mov.16b v20, v9
    let bv_0 = 56431;
    let t2 = av_2.mul_add(bv_0, t2);
    let t4 = a1_2 - t2;
    // TODO: Unsupported instruction: movk x4, #30457, lsl 16
    let t4 = av_2.mul_add(bv_0, t4);
    // TODO: Unsupported instruction: movk x4, #30012, lsl 32
    // TODO: Unsupported instruction: add.2d v19, v19, v20
    // TODO: Unsupported instruction: movk x4, #6382, lsl 48
    // TODO: Unsupported instruction: add.2d v17, v17, v22
    // TODO: Unsupported instruction: mov.16b v20, v9
    let bv_1 = 59151;
    let t2 = av_2.mul_add(bv_1, t2);
    // TODO: Unsupported instruction: movk x5, #41769, lsl 16
    let t4 = a1_2 - t2;
    // TODO: Unsupported instruction: movk x5, #32276, lsl 32
    let t4 = av_2.mul_add(bv_1, t4);
    // TODO: Unsupported instruction: add.2d v20, v21, v20
    // TODO: Unsupported instruction: movk x5, #21677, lsl 48
    // TODO: Unsupported instruction: add.2d v19, v19, v22
    let bv_2 = 34015;
    // TODO: Unsupported instruction: mov.16b v21, v9
    let t3 = av_2.mul_add(bv_2, t3);
    // TODO: Unsupported instruction: movk x6, #20342, lsl 16
    let t4 = a1_2 - t3;
    // TODO: Unsupported instruction: movk x6, #13935, lsl 32
    let t4 = av_2.mul_add(bv_2, t4);
    // TODO: Unsupported instruction: movk x6, #11030, lsl 48
    // TODO: Unsupported instruction: add.2d v0, v0, v21
    // TODO: Unsupported instruction: add.2d v20, v20, v22
    let bv_3 = 13689;
    // TODO: Unsupported instruction: mov.16b v21, v9
    // TODO: Unsupported instruction: movk x7, #8159, lsl 16
    let t3 = av_2.mul_add(b1_0, t3);
    // TODO: Unsupported instruction: movk x7, #215, lsl 32
    let t4 = a1_2 - t3;
    let t4 = av_2.mul_add(b1_0, t4);
    // TODO: Unsupported instruction: movk x7, #4913, lsl 48
    // TODO: Unsupported instruction: add.2d v1, v1, v21
    let t1 = bv_0.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v0, v0, v22
    // TODO: Unsupported instruction: mov.16b v21, v9
    let bv_0 = (((bv_0 as u128) * (t2 as u128)) >> 64) as u64;
    let t3 = av_2.mul_add(bv_3, t3);
    let (t1, _carry) = t1.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    let t4 = a1_2 - t3;
    let t4 = bv_1.wrapping_mul(t2);
    let t4 = av_2.mul_add(bv_3, t4);
    // TODO: Unsupported instruction: add.2d v2, v18, v21
    let bv_1 = (((bv_1 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v1, v1, v22
    let (bv_0, _carry) = t4.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: mov.16b v18, v9
    let (av_0, _carry) = bv_0.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    let t9 = a1_3.mul_add(bv_0, t9);
    let t3 = a1_2 - t9;
    let bv_1 = bv_2.wrapping_mul(t2);
    let t3 = a1_3.mul_add(bv_0, t3);
    let bv_2 = (((bv_2 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v18, v20, v18
    // TODO: Unsupported instruction: add.2d v19, v19, v21
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    // TODO: Unsupported instruction: mov.16b v20, v9
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    let t2 = a1_3.mul_add(bv_1, t2);
    let bv_1 = bv_3.wrapping_mul(t2);
    let t3 = a1_2 - t2;
    let t3 = a1_3.mul_add(bv_1, t3);
    let bv_2 = (((bv_3 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v0, v0, v20
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    // TODO: Unsupported instruction: add.2d v18, v18, v21
    // TODO: Unsupported instruction: mov.16b v20, v9
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    let t2 = a1_3.mul_add(bv_2, t2);
    let av_3 = av_3.wrapping_add(bv_0);
    let t3 = a1_2 - t2;
    let bv_0 = 61005;
    let t3 = a1_3.mul_add(bv_2, t3);
    // TODO: Unsupported instruction: add.2d v1, v1, v20
    // TODO: Unsupported instruction: movk x4, #58262, lsl 16
    // TODO: Unsupported instruction: add.2d v0, v0, v21
    // TODO: Unsupported instruction: movk x4, #32851, lsl 32
    // TODO: Unsupported instruction: mov.16b v20, v9
    // TODO: Unsupported instruction: movk x4, #11582, lsl 48
    let t2 = a1_3.mul_add(b1_0, t2);
    let t3 = a1_2 - t2;
    let bv_1 = 37581;
    let t3 = a1_3.mul_add(b1_0, t3);
    // TODO: Unsupported instruction: movk x5, #43836, lsl 16
    // TODO: Unsupported instruction: add.2d v2, v2, v20
    // TODO: Unsupported instruction: add.2d v1, v1, v21
    // TODO: Unsupported instruction: movk x5, #36286, lsl 32
    // TODO: Unsupported instruction: mov.16b v20, v9
    // TODO: Unsupported instruction: movk x5, #51783, lsl 48
    let t2 = a1_3.mul_add(bv_3, t2);
    let bv_2 = 10899;
    let t3 = a1_2 - t2;
    let t3 = a1_3.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x6, #30709, lsl 16
    // TODO: Unsupported instruction: add.2d v11, v16, v20
    // TODO: Unsupported instruction: movk x6, #61551, lsl 32
    // TODO: Unsupported instruction: add.2d v2, v2, v21
    // TODO: Unsupported instruction: movk x6, #45784, lsl 48
    // TODO: Unsupported instruction: mov.16b v16, v9
    let t0 = av_3.mul_add(bv_0, t0);
    let bv_3 = 36612;
    let t2 = a1_2 - t0;
    // TODO: Unsupported instruction: movk x7, #63402, lsl 16
    let t2 = av_3.mul_add(bv_0, t2);
    // TODO: Unsupported instruction: add.2d v0, v0, v16
    // TODO: Unsupported instruction: movk x7, #47623, lsl 32
    // TODO: Unsupported instruction: add.2d v4, v18, v20
    // TODO: Unsupported instruction: movk x7, #9430, lsl 48
    // TODO: Unsupported instruction: mov.16b v16, v9
    let t2 = bv_0.wrapping_mul(t3);
    let t0 = av_3.mul_add(bv_1, t0);
    let t9 = a1_2 - t0;
    let bv_0 = (((bv_0 as u128) * (t3 as u128)) >> 64) as u64;
    let t9 = av_3.mul_add(bv_1, t9);
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    let t2 = bv_1.wrapping_mul(t3);
    // TODO: Unsupported instruction: add.2d v0, v0, v18
    // TODO: Unsupported instruction: mov.16b v5, v9
    let bv_1 = (((bv_1 as u128) * (t3 as u128)) >> 64) as u64;
    let bv_1 = av_3.mul_add(bv_2, bv_1);
    let (bv_0, _carry) = t2.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t0 = a1_2 - bv_1;
    let t0 = av_3.mul_add(bv_2, t0);
    let (av_0, _carry) = bv_0.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    // TODO: Unsupported instruction: add.2d v2, v2, v5
    let bv_1 = bv_2.wrapping_mul(t3);
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    let bv_2 = (((bv_2 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v5, v9
    let bv_1 = av_3.mul_add(b1_0, bv_1);
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let bv_2 = a1_2 - bv_1;
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    let bv_2 = av_3.mul_add(b1_0, bv_2);
    let bv_1 = bv_3.wrapping_mul(t3);
    // TODO: Unsupported instruction: add.2d v5, v11, v5
    // TODO: Unsupported instruction: add.2d v2, v2, v6
    let bv_2 = (((bv_3 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v6, v9
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let bv_2 = av_3.mul_add(bv_3, bv_2);
    let a1_3 = a1_2 - bv_2;
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    let a1_3 = av_3.mul_add(bv_3, a1_3);
    let av_3 = av_3.wrapping_add(bv_0);
    // TODO: Unsupported instruction: add.2d v3, v14, v6
    let bv_0 = 65535;
    // TODO: Unsupported instruction: add.2d v5, v5, v11
    // TODO: Unsupported instruction: usra.2d v15, v13, #52
    // TODO: Unsupported instruction: movk x4, #61439, lsl 16
    // TODO: Unsupported instruction: usra.2d v17, v15, #52
    // TODO: Unsupported instruction: movk x4, #62867, lsl 32
    // TODO: Unsupported instruction: usra.2d v19, v17, #52
    // TODO: Unsupported instruction: usra.2d v4, v19, #52
    // TODO: Unsupported instruction: movk x4, #49889, lsl 48
    // TODO: Unsupported instruction: and.16b v6, v13, v8
    let bv_0 = bv_0.wrapping_mul(t1);
    // TODO: Unsupported instruction: and.16b v7, v15, v8
    let bv_1 = 1;
    // TODO: Unsupported instruction: and.16b v11, v17, v8
    // TODO: Unsupported instruction: and.16b v8, v19, v8
    // TODO: Unsupported instruction: movk x5, #61440, lsl 16
    // TODO: Unsupported instruction: ucvtf.2d v6, v6
    // TODO: Unsupported instruction: movk x5, #62867, lsl 32
    let bv_2 = 37864;
    // TODO: Unsupported instruction: movk x5, #17377, lsl 48
    // TODO: Unsupported instruction: movk x6, #1815, lsl 16
    // TODO: Unsupported instruction: movk x6, #28960, lsl 32
    let bv_3 = 28817;
    // TODO: Unsupported instruction: movk x6, #17153, lsl 48
    // TODO: Unsupported instruction: movk x7, #31161, lsl 16
    // TODO: Unsupported instruction: dup.2d v12, x6
    // TODO: Unsupported instruction: mov.16b v13, v9
    // TODO: Unsupported instruction: movk x7, #59464, lsl 32
    let b1_1 = bv_2.mul_add(b1_0, b1_1);
    // TODO: Unsupported instruction: movk x7, #10291, lsl 48
    let b1_2 = a1_2 - b1_1;
    let bv_2 = 22621;
    let b1_2 = bv_2.mul_add(b1_0, b1_2);
    // TODO: Unsupported instruction: add.2d v0, v0, v13
    // TODO: Unsupported instruction: movk x6, #33153, lsl 16
    // TODO: Unsupported instruction: add.2d v4, v4, v14
    // TODO: Unsupported instruction: movk x6, #17846, lsl 32
    let t2 = 46128;
    // TODO: Unsupported instruction: movk x6, #47184, lsl 48
    // TODO: Unsupported instruction: movk x20, #29964, lsl 16
    // TODO: Unsupported instruction: movk x20, #7587, lsl 32
    let t3 = 41001;
    // TODO: Unsupported instruction: movk x20, #17161, lsl 48
    // TODO: Unsupported instruction: movk x21, #57649, lsl 16
    // TODO: Unsupported instruction: dup.2d v12, x20
    // TODO: Unsupported instruction: mov.16b v13, v9
    // TODO: Unsupported instruction: movk x21, #20082, lsl 32
    let b1_1 = bv_2.mul_add(b1_0, b1_1);
    // TODO: Unsupported instruction: movk x21, #12388, lsl 48
    let b1_2 = a1_2 - b1_1;
    let t2 = bv_1.wrapping_mul(bv_0);
    let b1_2 = bv_2.mul_add(b1_0, b1_2);
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    let bv_1 = (((bv_1 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v0, v0, v14
    // TODO: Unsupported instruction: cmn x20, x17
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t1 = 52826;
    let t2 = bv_3.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: movk x17, #57790, lsl 16
    // TODO: Unsupported instruction: movk x17, #55431, lsl 32
    let bv_3 = (((bv_3 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x17, #17196, lsl 48
    let (bv_1, _carry) = t2.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x7, x7, hs
    // TODO: Unsupported instruction: dup.2d v12, x17
    // TODO: Unsupported instruction: mov.16b v13, v9
    let (av_0, _carry) = bv_1.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x5, x7, hs
    let b1_1 = bv_2.mul_add(b1_0, b1_1);
    let bv_3 = bv_2.wrapping_mul(bv_0);
    let b1_2 = a1_2 - b1_1;
    let bv_2 = (((bv_2 as u128) * (bv_0 as u128)) >> 64) as u64;
    let b1_2 = bv_2.mul_add(b1_0, b1_2);
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    let (bv_1, _carry) = bv_3.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v14
    let (av_1, _carry) = bv_1.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let bv_2 = 31276;
    let bv_3 = t3.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: movk x6, #21262, lsl 16
    // TODO: Unsupported instruction: movk x6, #2304, lsl 32
    let bv_0 = (((t3 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x6, #17182, lsl 48
    let (bv_1, _carry) = bv_3.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: dup.2d v12, x6
    // TODO: Unsupported instruction: mov.16b v13, v9
    let (av_2, _carry) = bv_1.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    let b1_1 = bv_2.mul_add(b1_0, b1_1);
    let av_3 = av_3.wrapping_add(bv_0);
    let b1_2 = a1_2 - b1_1;
    let bv_0 = a1_0.wrapping_mul(b1_0);
    let b1_2 = bv_2.mul_add(b1_0, b1_2);
    // TODO: Unsupported instruction: add.2d v5, v5, v13
    let bv_1 = (((a1_0 as u128) * (b1_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v2, v2, v14
    let bv_2 = a1_1.wrapping_mul(b1_0);
    let bv_3 = 28672;
    // TODO: Unsupported instruction: movk x7, #24515, lsl 16
    let t1 = (((a1_1 as u128) * (b1_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x7, #54929, lsl 32
    let (bv_1, _carry) = bv_2.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x6, x17, hs
    // TODO: Unsupported instruction: movk x7, #17064, lsl 48
    let t1 = a1_2.wrapping_mul(b1_0);
    // TODO: Unsupported instruction: dup.2d v12, x7
    // TODO: Unsupported instruction: mov.16b v13, v9
    let bv_3 = (((a1_2 as u128) * (b1_0 as u128)) >> 64) as u64;
    let b1_1 = bv_2.mul_add(b1_0, b1_1);
    let (bv_2, _carry) = t1.overflowing_add(bv_2);
    // TODO: Unsupported instruction: cinc x7, x7, hs
    let b1_2 = a1_2 - b1_1;
    let t1 = a1_3.wrapping_mul(b1_0);
    let b1_2 = bv_2.mul_add(b1_0, b1_2);
    // TODO: Unsupported instruction: add.2d v3, v3, v13
    let b1_0 = (((a1_3 as u128) * (b1_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v5, v5, v14
    let (bv_3, _carry) = t1.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x12, x12, hs
    // TODO: Unsupported instruction: ucvtf.2d v6, v7
    let t1 = 44768;
    let t2 = a1_0.wrapping_mul(b1_1);
    // TODO: Unsupported instruction: movk x17, #51919, lsl 16
    let t3 = (((a1_0 as u128) * (b1_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x17, #6346, lsl 32
    let (bv_1, _carry) = t2.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x20, x21, hs
    // TODO: Unsupported instruction: movk x17, #17133, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x17
    let t1 = a1_1.wrapping_mul(b1_1);
    // TODO: Unsupported instruction: mov.16b v12, v9
    let t3 = (((a1_1 as u128) * (b1_1 as u128)) >> 64) as u64;
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    let (t1, _carry) = t1.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x20, x21, hs
    let b1_1 = a1_2 - b1_0;
    let b1_1 = bv_2.mul_add(bv_3, b1_1);
    let (bv_2, _carry) = t1.overflowing_add(bv_2);
    // TODO: Unsupported instruction: cinc x17, x20, hs
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    let t2 = a1_2.wrapping_mul(b1_1);
    // TODO: Unsupported instruction: add.2d v4, v4, v13
    let t3 = 47492;
    let t4 = (((a1_2 as u128) * (b1_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x21, #23630, lsl 16
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x20, x22, hs
    // TODO: Unsupported instruction: movk x21, #49985, lsl 32
    let (bv_3, _carry) = t1.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x17, x20, hs
    // TODO: Unsupported instruction: movk x21, #17168, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x21
    let t2 = a1_3.wrapping_mul(b1_1);
    // TODO: Unsupported instruction: mov.16b v12, v9
    let b1_1 = (((a1_3 as u128) * (b1_1 as u128)) >> 64) as u64;
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    let b1_1 = a1_2 - b1_0;
    let b1_1 = bv_2.mul_add(bv_3, b1_1);
    let (b1_0, _carry) = t1.overflowing_add(b1_0);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    let t1 = a1_0.wrapping_mul(b1_2);
    // TODO: Unsupported instruction: add.2d v0, v0, v13
    let t2 = 57936;
    let t3 = (((a1_0 as u128) * (b1_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x20, #54828, lsl 16
    let (bv_2, _carry) = t1.overflowing_add(bv_2);
    // TODO: Unsupported instruction: cinc x17, x21, hs
    // TODO: Unsupported instruction: movk x20, #18292, lsl 32
    let t3 = a1_1.wrapping_mul(b1_2);
    // TODO: Unsupported instruction: movk x20, #17197, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x20
    let t2 = (((a1_1 as u128) * (b1_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v12, v9
    let (t1, _carry) = t3.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x20, x20, hs
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    let (bv_3, _carry) = t1.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x17, x20, hs
    let b1_1 = a1_2 - b1_0;
    let b1_1 = bv_2.mul_add(bv_3, b1_1);
    let t2 = a1_2.wrapping_mul(b1_2);
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    let t3 = (((a1_2 as u128) * (b1_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    let t4 = 17708;
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x20, x21, hs
    // TODO: Unsupported instruction: movk x22, #43915, lsl 16
    let (b1_0, _carry) = t1.overflowing_add(b1_0);
    // TODO: Unsupported instruction: cinc x17, x20, hs
    // TODO: Unsupported instruction: movk x22, #64348, lsl 32
    let t2 = a1_3.wrapping_mul(b1_2);
    // TODO: Unsupported instruction: movk x22, #17188, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x22
    let b1_2 = (((a1_3 as u128) * (b1_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v12, v9
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x14, x14, hs
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    let b1_1 = a1_2 - b1_0;
    let (b1_1, _carry) = t1.overflowing_add(b1_1);
    // TODO: Unsupported instruction: cinc x14, x14, hs
    let b1_1 = bv_2.mul_add(bv_3, b1_1);
    let t1 = a1_0.wrapping_mul(b1_3);
    // TODO: Unsupported instruction: add.2d v5, v5, v12
    let a1_0 = (((a1_0 as u128) * (b1_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    let t2 = 29184;
    let (bv_3, _carry) = t1.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x8, x8, hs
    // TODO: Unsupported instruction: movk x20, #20789, lsl 16
    let t1 = a1_1.wrapping_mul(b1_3);
    // TODO: Unsupported instruction: movk x20, #19197, lsl 32
    let a1_1 = (((a1_1 as u128) * (b1_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x20, #17083, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x20
    let (a1_0, _carry) = t1.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: mov.16b v12, v9
    let (a1_0, _carry) = a1_0.overflowing_add(b1_0);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    let b1_1 = a1_2 - b1_0;
    let b1_0 = a1_2.wrapping_mul(b1_3);
    let b1_1 = bv_2.mul_add(bv_3, b1_1);
    let a1_2 = (((a1_2 as u128) * (b1_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v3, v3, v12
    let (a1_1, _carry) = b1_0.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    // TODO: Unsupported instruction: add.2d v5, v5, v13
    // TODO: Unsupported instruction: ucvtf.2d v6, v11
    let (a1_1, _carry) = a1_1.overflowing_add(b1_1);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    let b1_0 = 58856;
    let b1_1 = a1_3.wrapping_mul(b1_3);
    // TODO: Unsupported instruction: movk x12, #14953, lsl 16
    let a1_3 = (((a1_3 as u128) * (b1_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x12, #15155, lsl 32
    // TODO: Unsupported instruction: movk x12, #17181, lsl 48
    let (a1_2, _carry) = b1_1.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x11, x11, hs
    // TODO: Unsupported instruction: dup.2d v7, x12
    let (a1_2, _carry) = a1_2.overflowing_add(b1_2);
    // TODO: Unsupported instruction: cinc x11, x11, hs
    // TODO: Unsupported instruction: mov.16b v11, v9
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    let b1_0 = 48718;
    let b1_0 = a1_2 - a1_3;
    // TODO: Unsupported instruction: movk x12, #4732, lsl 16
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    // TODO: Unsupported instruction: movk x12, #45078, lsl 32
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    // TODO: Unsupported instruction: add.2d v4, v4, v12
    // TODO: Unsupported instruction: movk x12, #39852, lsl 48
    let b1_1 = 35392;
    let b1_2 = 16676;
    // TODO: Unsupported instruction: movk x13, #12477, lsl 16
    // TODO: Unsupported instruction: movk x14, #12692, lsl 16
    // TODO: Unsupported instruction: movk x13, #56780, lsl 32
    // TODO: Unsupported instruction: movk x13, #17142, lsl 48
    // TODO: Unsupported instruction: movk x14, #20986, lsl 32
    // TODO: Unsupported instruction: dup.2d v7, x13
    // TODO: Unsupported instruction: movk x14, #2848, lsl 48
    // TODO: Unsupported instruction: mov.16b v11, v9
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    let b1_1 = 51052;
    let b1_0 = a1_2 - a1_3;
    // TODO: Unsupported instruction: movk x13, #24721, lsl 16
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    // TODO: Unsupported instruction: movk x13, #61092, lsl 32
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    // TODO: Unsupported instruction: movk x13, #45156, lsl 48
    let b1_3 = 9848;
    let t1 = 3197;
    // TODO: Unsupported instruction: movk x15, #54501, lsl 16
    // TODO: Unsupported instruction: movk x17, #18936, lsl 16
    // TODO: Unsupported instruction: movk x15, #31540, lsl 32
    // TODO: Unsupported instruction: movk x15, #17170, lsl 48
    // TODO: Unsupported instruction: movk x17, #10922, lsl 32
    // TODO: Unsupported instruction: dup.2d v7, x15
    // TODO: Unsupported instruction: movk x17, #11014, lsl 48
    // TODO: Unsupported instruction: mov.16b v11, v9
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    let b1_3 = b1_0.wrapping_mul(bv_0);
    let b1_0 = a1_2 - a1_3;
    let b1_0 = (((b1_0 as u128) * (bv_0 as u128)) >> 64) as u64;
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    let (bv_3, _carry) = b1_3.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x12, x12, hs
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    let b1_3 = b1_2.wrapping_mul(bv_0);
    let t2 = 9584;
    let b1_2 = (((b1_2 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x20, #63883, lsl 16
    // TODO: Unsupported instruction: movk x20, #18253, lsl 32
    let (b1_0, _carry) = b1_3.overflowing_add(b1_0);
    // TODO: Unsupported instruction: cinc x14, x14, hs
    // TODO: Unsupported instruction: movk x20, #17190, lsl 48
    let (a1_0, _carry) = b1_0.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x12, x14, hs
    // TODO: Unsupported instruction: dup.2d v7, x20
    let b1_2 = b1_1.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: mov.16b v11, v9
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    let b1_1 = (((b1_1 as u128) * (bv_0 as u128)) >> 64) as u64;
    let b1_0 = a1_2 - a1_3;
    let (b1_0, _carry) = b1_2.overflowing_add(b1_0);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    let (a1_1, _carry) = b1_0.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x12, x13, hs
    // TODO: Unsupported instruction: add.2d v5, v5, v11
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    let b1_1 = t1.wrapping_mul(bv_0);
    let b1_2 = 51712;
    let bv_0 = (((t1 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x14, #16093, lsl 16
    // TODO: Unsupported instruction: movk x14, #30633, lsl 32
    let (b1_0, _carry) = b1_1.overflowing_add(b1_0);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: movk x14, #17068, lsl 48
    let (a1_2, _carry) = b1_0.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: dup.2d v7, x14
    let bv_0 = a1_3.wrapping_add(bv_0);
    // TODO: Unsupported instruction: mov.16b v11, v9
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    let a1_3 = 56431;
    let b1_0 = a1_2 - a1_3;
    // TODO: Unsupported instruction: movk x11, #30457, lsl 16
    let b1_0 = bv_2.mul_add(bv_3, b1_0);
    // TODO: Unsupported instruction: movk x11, #30012, lsl 32
    // TODO: Unsupported instruction: add.2d v3, v3, v11
    // TODO: Unsupported instruction: add.2d v5, v5, v12
    // TODO: Unsupported instruction: movk x11, #6382, lsl 48
    // TODO: Unsupported instruction: ucvtf.2d v6, v8
    let b1_0 = 59151;
    let b1_1 = 34724;
    // TODO: Unsupported instruction: movk x13, #40393, lsl 16
    // TODO: Unsupported instruction: movk x12, #41769, lsl 16
    // TODO: Unsupported instruction: movk x13, #23752, lsl 32
    // TODO: Unsupported instruction: movk x12, #32276, lsl 32
    // TODO: Unsupported instruction: movk x13, #17184, lsl 48
    // TODO: Unsupported instruction: movk x12, #21677, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x13
    // TODO: Unsupported instruction: mov.16b v8, v9
    let b1_1 = 34015;
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    // TODO: Unsupported instruction: movk x13, #20342, lsl 16
    let a1_3 = a1_2 - a1_0;
    // TODO: Unsupported instruction: movk x13, #13935, lsl 32
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    // TODO: Unsupported instruction: add.2d v0, v0, v8
    // TODO: Unsupported instruction: movk x13, #11030, lsl 48
    // TODO: Unsupported instruction: add.2d v4, v4, v11
    let b1_2 = 13689;
    let b1_3 = 25532;
    // TODO: Unsupported instruction: movk x15, #31025, lsl 16
    // TODO: Unsupported instruction: movk x14, #8159, lsl 16
    // TODO: Unsupported instruction: movk x15, #10002, lsl 32
    // TODO: Unsupported instruction: movk x14, #215, lsl 32
    // TODO: Unsupported instruction: movk x15, #17199, lsl 48
    // TODO: Unsupported instruction: movk x14, #4913, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x15
    // TODO: Unsupported instruction: mov.16b v8, v9
    let b1_3 = a1_3.wrapping_mul(bv_1);
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    let a1_3 = (((a1_3 as u128) * (bv_1 as u128)) >> 64) as u64;
    let a1_3 = a1_2 - a1_0;
    let (bv_3, _carry) = b1_3.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x11, x11, hs
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    // TODO: Unsupported instruction: add.2d v1, v1, v8
    let b1_3 = b1_0.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    let b1_0 = (((b1_0 as u128) * (bv_1 as u128)) >> 64) as u64;
    let t1 = 18830;
    // TODO: Unsupported instruction: movk x17, #2465, lsl 16
    let (a1_3, _carry) = b1_3.overflowing_add(a1_3);
    // TODO: Unsupported instruction: cinc x12, x12, hs
    // TODO: Unsupported instruction: movk x17, #36348, lsl 32
    let (a1_0, _carry) = a1_3.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x11, x12, hs
    // TODO: Unsupported instruction: movk x17, #17194, lsl 48
    let b1_0 = b1_1.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: dup.2d v7, x17
    // TODO: Unsupported instruction: mov.16b v8, v9
    let b1_1 = (((b1_1 as u128) * (bv_1 as u128)) >> 64) as u64;
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    let (a1_3, _carry) = b1_0.overflowing_add(a1_3);
    // TODO: Unsupported instruction: cinc x12, x13, hs
    let a1_3 = a1_2 - a1_0;
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    let (a1_1, _carry) = a1_3.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x11, x12, hs
    // TODO: Unsupported instruction: add.2d v2, v2, v8
    let b1_0 = b1_2.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    let bv_1 = (((b1_2 as u128) * (bv_1 as u128)) >> 64) as u64;
    let b1_1 = 21566;
    // TODO: Unsupported instruction: movk x13, #43708, lsl 16
    let (a1_3, _carry) = b1_0.overflowing_add(a1_3);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: movk x13, #57685, lsl 32
    let (a1_2, _carry) = a1_3.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: movk x13, #17185, lsl 48
    let bv_0 = bv_0.wrapping_add(bv_1);
    // TODO: Unsupported instruction: dup.2d v7, x13
    // TODO: Unsupported instruction: mov.16b v8, v9
    let bv_1 = 61005;
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    // TODO: Unsupported instruction: movk x5, #58262, lsl 16
    let a1_3 = a1_2 - a1_0;
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    // TODO: Unsupported instruction: movk x5, #32851, lsl 32
    // TODO: Unsupported instruction: add.2d v5, v5, v8
    // TODO: Unsupported instruction: movk x5, #11582, lsl 48
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    let a1_3 = 37581;
    let b1_0 = 3072;
    // TODO: Unsupported instruction: movk x12, #8058, lsl 16
    // TODO: Unsupported instruction: movk x11, #43836, lsl 16
    // TODO: Unsupported instruction: movk x12, #46097, lsl 32
    // TODO: Unsupported instruction: movk x11, #36286, lsl 32
    // TODO: Unsupported instruction: movk x12, #17047, lsl 48
    // TODO: Unsupported instruction: movk x11, #51783, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x12
    // TODO: Unsupported instruction: mov.16b v8, v9
    let b1_0 = 10899;
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    // TODO: Unsupported instruction: movk x12, #30709, lsl 16
    let a1_3 = a1_2 - a1_0;
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    // TODO: Unsupported instruction: movk x12, #61551, lsl 32
    // TODO: Unsupported instruction: add.2d v3, v3, v8
    // TODO: Unsupported instruction: movk x12, #45784, lsl 48
    // TODO: Unsupported instruction: add.2d v5, v5, v11
    let b1_1 = 36612;
    let b1_2 = 65535;
    // TODO: Unsupported instruction: movk x14, #61439, lsl 16
    // TODO: Unsupported instruction: movk x13, #63402, lsl 16
    // TODO: Unsupported instruction: movk x14, #62867, lsl 32
    // TODO: Unsupported instruction: movk x13, #47623, lsl 32
    // TODO: Unsupported instruction: movk x14, #1, lsl 48
    // TODO: Unsupported instruction: movk x13, #9430, lsl 48
    // TODO: Unsupported instruction: umov x15, v4.d[0]
    // TODO: Unsupported instruction: umov x17, v4.d[1]
    let t2 = bv_1.wrapping_mul(bv_2);
    let b1_3 = b1_3.wrapping_mul(b1_2);
    let bv_1 = (((bv_1 as u128) * (bv_2 as u128)) >> 64) as u64;
    let b1_2 = t1.wrapping_mul(b1_2);
    let b1_3 = b1_3 & t0;
    let (bv_3, _carry) = t2.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let b1_2 = b1_2 & t0;
    let t0 = a1_3.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: ins v6.d[0], x15
    // TODO: Unsupported instruction: ins v6.d[1], x14
    let a1_3 = (((a1_3 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v6, v6
    let b1_2 = 16;
    let (bv_1, _carry) = t0.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x11, x11, hs
    // TODO: Unsupported instruction: movk x14, #22847, lsl 32
    let (bv_1, _carry) = bv_1.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x8, x11, hs
    // TODO: Unsupported instruction: movk x14, #17151, lsl 48
    let a1_3 = b1_0.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: dup.2d v7, x14
    // TODO: Unsupported instruction: mov.16b v8, v9
    let b1_0 = (((b1_0 as u128) * (bv_2 as u128)) >> 64) as u64;
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    let (a1_0, _carry) = a1_3.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x11, x12, hs
    let a1_3 = a1_2 - a1_0;
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    let (a1_0, _carry) = a1_0.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x9, x11, hs
    // TODO: Unsupported instruction: add.2d v0, v0, v8
    let a1_3 = b1_1.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: add.2d v4, v4, v11
    let bv_2 = (((b1_1 as u128) * (bv_2 as u128)) >> 64) as u64;
    let b1_0 = 20728;
    // TODO: Unsupported instruction: movk x12, #23588, lsl 16
    let (a1_1, _carry) = a1_3.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: movk x12, #7790, lsl 32
    let (a1_1, _carry) = a1_1.overflowing_add(a1_2);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: movk x12, #17170, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x12
    let a1_2 = bv_0.wrapping_add(bv_2);
    // TODO: Unsupported instruction: mov.16b v8, v9
    let bv_0 = 65535;
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    // TODO: Unsupported instruction: movk x4, #61439, lsl 16
    let a1_3 = a1_2 - a1_0;
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    // TODO: Unsupported instruction: movk x4, #62867, lsl 32
    // TODO: Unsupported instruction: add.2d v1, v1, v8
    // TODO: Unsupported instruction: movk x4, #49889, lsl 48
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    let bv_2 = bv_0.wrapping_mul(bv_3);
    let bv_0 = 16000;
    // TODO: Unsupported instruction: movk x4, #53891, lsl 16
    let a1_3 = 1;
    // TODO: Unsupported instruction: movk x4, #5509, lsl 32
    // TODO: Unsupported instruction: movk x11, #61440, lsl 16
    // TODO: Unsupported instruction: movk x4, #17144, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x4
    // TODO: Unsupported instruction: movk x11, #62867, lsl 32
    // TODO: Unsupported instruction: mov.16b v8, v9
    // TODO: Unsupported instruction: movk x11, #17377, lsl 48
    let a1_0 = bv_2.mul_add(bv_3, a1_0);
    let bv_0 = 28817;
    let a1_3 = a1_2 - a1_0;
    let a1_3 = bv_2.mul_add(bv_3, a1_3);
    // TODO: Unsupported instruction: movk x4, #31161, lsl 16
    // TODO: Unsupported instruction: add.2d v2, v2, v8
    // TODO: Unsupported instruction: movk x4, #59464, lsl 32
    // TODO: Unsupported instruction: add.2d v7, v1, v11
    // TODO: Unsupported instruction: movk x4, #10291, lsl 48
    let b1_0 = 46800;
    // TODO: Unsupported instruction: movk x12, #2568, lsl 16
    let b1_1 = 22621;
    // TODO: Unsupported instruction: movk x12, #1335, lsl 32
    // TODO: Unsupported instruction: movk x13, #33153, lsl 16
    // TODO: Unsupported instruction: movk x12, #17188, lsl 48
    // TODO: Unsupported instruction: dup.2d v1, x12
    // TODO: Unsupported instruction: movk x13, #17846, lsl 32
    // TODO: Unsupported instruction: mov.16b v8, v9
    // TODO: Unsupported instruction: movk x13, #47184, lsl 48
    let a1_0 = bv_2.mul_add(av_1, a1_0);
    let b1_0 = 41001;
    let a1_3 = a1_2 - a1_0;
    let a1_3 = bv_2.mul_add(av_1, a1_3);
    // TODO: Unsupported instruction: movk x12, #57649, lsl 16
    // TODO: Unsupported instruction: add.2d v1, v5, v8
    // TODO: Unsupported instruction: movk x12, #20082, lsl 32
    // TODO: Unsupported instruction: add.2d v5, v2, v11
    // TODO: Unsupported instruction: movk x12, #12388, lsl 48
    let b1_2 = 39040;
    // TODO: Unsupported instruction: movk x14, #14704, lsl 16
    let b1_3 = a1_3.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: movk x14, #12839, lsl 32
    let a1_3 = (((a1_3 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x14, #17096, lsl 48
    // TODO: Unsupported instruction: dup.2d v2, x14
    // TODO: Unsupported instruction: cmn x15, x7
    // TODO: Unsupported instruction: cinc x11, x11, hs
    // TODO: Unsupported instruction: mov.16b v8, v9
    let bv_3 = bv_0.wrapping_mul(bv_2);
    let a1_0 = bv_2.mul_add(av_2, a1_0);
    let bv_0 = (((bv_0 as u128) * (bv_2 as u128)) >> 64) as u64;
    let a1_1 = a1_2 - a1_0;
    let a1_1 = bv_2.mul_add(av_2, a1_1);
    let (bv_3, _carry) = bv_3.overflowing_add(a1_3);
    // TODO: Unsupported instruction: cinc x11, x4, hs
    // TODO: Unsupported instruction: add.2d v6, v3, v8
    let (bv_0, _carry) = bv_3.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x5, x11, hs
    // TODO: Unsupported instruction: add.2d v8, v1, v9
    let bv_3 = b1_1.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: ssra.2d v0, v4, #52
    // TODO: Unsupported instruction: ssra.2d v7, v0, #52
    let a1_3 = (((b1_1 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ssra.2d v5, v7, #52
    let (bv_1, _carry) = bv_3.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x7, x11, hs
    // TODO: Unsupported instruction: ssra.2d v8, v5, #52
    // TODO: Unsupported instruction: ssra.2d v6, v8, #52
    let (bv_1, _carry) = bv_1.overflowing_add(a1_0);
    // TODO: Unsupported instruction: cinc x7, x7, hs
    // TODO: Unsupported instruction: ushr.2d v1, v7, #12
    let a1_0 = b1_0.wrapping_mul(bv_2);
    // TODO: Unsupported instruction: ushr.2d v2, v5, #24
    let bv_2 = (((b1_0 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ushr.2d v3, v8, #36
    // TODO: Unsupported instruction: sli.2d v0, v7, #52
    let (bv_3, _carry) = a1_0.overflowing_add(bv_3);
    // TODO: Unsupported instruction: cinc x8, x6, hs
    // TODO: Unsupported instruction: sli.2d v1, v5, #40
    let (bv_2, _carry) = bv_3.overflowing_add(a1_1);
    // TODO: Unsupported instruction: cinc x7, x8, hs
    // TODO: Unsupported instruction: sli.2d v2, v8, #28
    // TODO: Unsupported instruction: sli.2d v3, v6, #16
    let bv_3 = a1_2.wrapping_add(bv_3);

    let out = [av_0, av_1, av_2, av_3];
    let out1 = [bv_0, bv_1, bv_2, bv_3];
    let outv = [av_0, av_1, av_2, av_3];

    (out, out1, outv)
}
