[package]
name = "provekit-verifier"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# Workspace crates
provekit-common.workspace = true
provekit-backend-bn254.workspace = true

# Cryptography and proof systems
ark-ff.workspace = true
ark-std.workspace = true
whir.workspace = true

# 3rd party
anyhow.workspace = true
rayon.workspace = true
tracing.workspace = true

[lints]
workspace = true
