// GENERATED FILE, DO NOT EDIT!
// Generated by HLA framework for WASM SIMD optimization
// Note: Imports are in the parent module (mod.rs)

#[inline(always)]
pub fn montgomery_square_interleaved_3(
    _guard: &RoundingGuard<Zero>,
    a: [u64; 4],
    av: [Simd<u64, 2>; 4]
) -> ([u64; 4], [Simd<u64, 2>; 4]) {
    let a_0 = a[0];
    let a_1 = a[1];
    let a_2 = a[2];
    let a_3 = a[3];
    let av_0 = av[0];
    let av_1 = av[1];
    let av_2 = av[2];
    let av_3 = av[3];

    let t0 = 4503599627370495;
    // TODO: Unsupported instruction: dup.2d v4, x4
    let t1 = av_0.wrapping_mul(av_0);
    let t2 = 5075556780046548992;
    // TODO: Unsupported instruction: dup.2d v5, x6
    let t2 = 1;
    let t3 = (((av_0 as u128) * (av_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x6, #18032, lsl 48
    // TODO: Unsupported instruction: dup.2d v6, x6
    let t2 = av_0.wrapping_mul(av_1);
    // TODO: Unsupported instruction: shl.2d v7, v1, #14
    // TODO: Unsupported instruction: shl.2d v8, v2, #26
    // TODO: Unsupported instruction: shl.2d v9, v3, #38
    let t4 = (((av_0 as u128) * (av_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ushr.2d v3, v3, #14
    // TODO: Unsupported instruction: shl.2d v10, v0, #2
    // TODO: Unsupported instruction: usra.2d v7, v0, #50
    let (t3, _carry) = t2.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x9, x8, hs
    // TODO: Unsupported instruction: usra.2d v8, v1, #38
    // TODO: Unsupported instruction: usra.2d v9, v2, #26
    let t6 = av_0.wrapping_mul(av_2);
    // TODO: Unsupported instruction: and.16b v0, v10, v4
    // TODO: Unsupported instruction: and.16b v1, v7, v4
    // TODO: Unsupported instruction: and.16b v2, v8, v4
    let t7 = (((av_0 as u128) * (av_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: and.16b v7, v9, v4
    let t8 = 13605374474286268416;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x13, x11, hs
    // TODO: Unsupported instruction: dup.2d v8, x12
    let t8 = 6440147467139809280;
    // TODO: Unsupported instruction: dup.2d v9, x12
    let t8 = av_0.wrapping_mul(av_3);
    let t10 = 3688448094816436224;
    // TODO: Unsupported instruction: dup.2d v10, x14
    let t10 = 9209861237972664320;
    let av_0 = (((av_0 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v11, x14
    let t10 = 12218265789056155648;
    let (t9, _carry) = t8.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x15, x0, hs
    // TODO: Unsupported instruction: dup.2d v12, x14
    let t10 = 17739678932212383744;
    // TODO: Unsupported instruction: dup.2d v13, x14
    let (t2, _carry) = t2.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x7, x8, hs
    let t4 = 2301339409586323456;
    // TODO: Unsupported instruction: dup.2d v14, x8
    let t4 = 7822752552742551552;
    let t10 = av_1.wrapping_mul(av_1);
    // TODO: Unsupported instruction: dup.2d v15, x8
    let t4 = 5071053180419178496;
    let t12 = (((av_1 as u128) * (av_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v16, x8
    let t4 = 16352570246982270976;
    // TODO: Unsupported instruction: dup.2d v17, x8
    let (t3, _carry) = t10.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x8, x16, hs
    // TODO: Unsupported instruction: ucvtf.2d v0, v0
    // TODO: Unsupported instruction: ucvtf.2d v1, v1
    let (t3, _carry) = t3.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x8, x8, hs
    // TODO: Unsupported instruction: ucvtf.2d v2, v2
    // TODO: Unsupported instruction: ucvtf.2d v7, v7
    // TODO: Unsupported instruction: ucvtf.2d v3, v3
    let t5 = av_1.wrapping_mul(av_2);
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t14 = av_0.mul_add(av_0, t14);
    let t15 = t2 - t14;
    let t10 = (((av_1 as u128) * (av_2 as u128)) >> 64) as u64;
    let t15 = av_0.mul_add(av_0, t15);
    // TODO: Unsupported instruction: add.2d v10, v10, v18
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x16, x14, hs
    // TODO: Unsupported instruction: add.2d v8, v8, v19
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t14 = av_0.mul_add(av_1, t14);
    let (t4, _carry) = t4.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x13, x16, hs
    let t15 = t2 - t14;
    let t15 = av_0.mul_add(av_1, t15);
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    let t12 = av_1.wrapping_mul(av_3);
    // TODO: Unsupported instruction: add.2d v19, v19, v19
    // TODO: Unsupported instruction: add.2d v12, v12, v18
    let av_1 = (((av_1 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v10, v10, v19
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t14 = av_0.mul_add(av_2, t14);
    let (t9, _carry) = t12.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x17, x1, hs
    let t15 = t2 - t14;
    let t15 = av_0.mul_add(av_2, t15);
    let (t9, _carry) = t9.overflowing_add(t11);
    // TODO: Unsupported instruction: cinc x15, x17, hs
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    // TODO: Unsupported instruction: add.2d v19, v19, v19
    // TODO: Unsupported instruction: add.2d v14, v14, v18
    let (t3, _carry) = t6.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x10, x11, hs
    // TODO: Unsupported instruction: add.2d v12, v12, v19
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t14 = av_0.mul_add(t3, t14);
    let (t5, _carry) = t5.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x10, x14, hs
    let t15 = t2 - t14;
    let t15 = av_0.mul_add(t3, t15);
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    // TODO: Unsupported instruction: add.2d v19, v19, v19
    // TODO: Unsupported instruction: add.2d v16, v16, v18
    let t6 = av_2.wrapping_mul(av_2);
    // TODO: Unsupported instruction: add.2d v14, v14, v19
    // TODO: Unsupported instruction: mov.16b v18, v5
    let t14 = av_0.mul_add(av_3, t14);
    let t7 = (((av_2 as u128) * (av_2 as u128)) >> 64) as u64;
    let t15 = t2 - t14;
    let t15 = av_0.mul_add(av_3, t15);
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x10, x11, hs
    // TODO: Unsupported instruction: add.2d v0, v18, v18
    // TODO: Unsupported instruction: add.2d v18, v19, v19
    // TODO: Unsupported instruction: add.2d v0, v17, v0
    let (t5, _carry) = t5.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    // TODO: Unsupported instruction: add.2d v16, v16, v18
    // TODO: Unsupported instruction: mov.16b v17, v5
    let t7 = av_2.wrapping_mul(av_3);
    let t13 = av_1.mul_add(av_1, t13);
    let t14 = t2 - t13;
    let t14 = av_1.mul_add(av_1, t14);
    let av_2 = (((av_2 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v14, v14, v17
    // TODO: Unsupported instruction: add.2d v12, v12, v18
    // TODO: Unsupported instruction: mov.16b v17, v5
    let (t6, _carry) = t7.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x13, x2, hs
    let t13 = av_1.mul_add(av_2, t13);
    let t14 = t2 - t13;
    let (t6, _carry) = t6.overflowing_add(t11);
    // TODO: Unsupported instruction: cinc x13, x13, hs
    let t14 = av_1.mul_add(av_2, t14);
    // TODO: Unsupported instruction: add.2d v17, v17, v17
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    let (t4, _carry) = t8.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x0, x0, hs
    // TODO: Unsupported instruction: add.2d v16, v16, v17
    // TODO: Unsupported instruction: add.2d v14, v14, v18
    let (av_0, _carry) = t12.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    // TODO: Unsupported instruction: mov.16b v17, v5
    let t13 = av_1.mul_add(t3, t13);
    let t14 = t2 - t13;
    let (av_0, _carry) = av_0.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    let t14 = av_1.mul_add(t3, t14);
    // TODO: Unsupported instruction: add.2d v17, v17, v17
    // TODO: Unsupported instruction: add.2d v18, v18, v18
    let (av_1, _carry) = t7.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    // TODO: Unsupported instruction: add.2d v0, v0, v17
    // TODO: Unsupported instruction: add.2d v16, v16, v18
    let (av_1, _carry) = av_1.overflowing_add(t6);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    // TODO: Unsupported instruction: mov.16b v17, v5
    let t13 = av_1.mul_add(av_3, t13);
    let t14 = t2 - t13;
    let t5 = av_3.wrapping_mul(av_3);
    let t14 = av_1.mul_add(av_3, t14);
    // TODO: Unsupported instruction: add.2d v1, v17, v17
    // TODO: Unsupported instruction: add.2d v17, v18, v18
    let av_3 = (((av_3 as u128) * (av_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v1, v15, v1
    // TODO: Unsupported instruction: add.2d v0, v0, v17
    let (av_2, _carry) = t5.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    // TODO: Unsupported instruction: mov.16b v15, v5
    let t11 = av_2.mul_add(av_2, t11);
    let t13 = t2 - t11;
    let (av_2, _carry) = av_2.overflowing_add(t9);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    let t13 = av_2.mul_add(av_2, t13);
    // TODO: Unsupported instruction: add.2d v0, v0, v15
    let t5 = 48718;
    // TODO: Unsupported instruction: add.2d v15, v16, v17
    // TODO: Unsupported instruction: mov.16b v16, v5
    let t12 = av_2.mul_add(t3, t12);
    // TODO: Unsupported instruction: movk x9, #4732, lsl 16
    let t13 = t2 - t12;
    let t13 = av_2.mul_add(t3, t13);
    // TODO: Unsupported instruction: add.2d v16, v16, v16
    // TODO: Unsupported instruction: movk x9, #45078, lsl 32
    // TODO: Unsupported instruction: add.2d v17, v17, v17
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    // TODO: Unsupported instruction: movk x9, #39852, lsl 48
    // TODO: Unsupported instruction: add.2d v0, v0, v17
    // TODO: Unsupported instruction: mov.16b v16, v5
    let t12 = av_2.mul_add(av_3, t12);
    let t6 = 16676;
    let t13 = t2 - t12;
    let t13 = av_2.mul_add(av_3, t13);
    // TODO: Unsupported instruction: add.2d v2, v16, v16
    // TODO: Unsupported instruction: movk x10, #12692, lsl 16
    // TODO: Unsupported instruction: add.2d v16, v17, v17
    // TODO: Unsupported instruction: add.2d v2, v13, v2
    // TODO: Unsupported instruction: movk x10, #20986, lsl 32
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t9 = t3.mul_add(t3, t9);
    // TODO: Unsupported instruction: movk x10, #2848, lsl 48
    let t12 = t2 - t9;
    let t12 = t3.mul_add(t3, t12);
    let t7 = 51052;
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    // TODO: Unsupported instruction: mov.16b v13, v5
    // TODO: Unsupported instruction: movk x11, #24721, lsl 16
    let t9 = t3.mul_add(av_3, t9);
    let t12 = t2 - t9;
    let t12 = t3.mul_add(av_3, t12);
    // TODO: Unsupported instruction: movk x11, #61092, lsl 32
    // TODO: Unsupported instruction: add.2d v7, v13, v13
    // TODO: Unsupported instruction: add.2d v13, v16, v16
    // TODO: Unsupported instruction: movk x11, #45156, lsl 48
    // TODO: Unsupported instruction: add.2d v7, v11, v7
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    // TODO: Unsupported instruction: mov.16b v11, v5
    let t8 = 3197;
    let t7 = av_3.mul_add(av_3, t7);
    let t9 = t2 - t7;
    let t9 = av_3.mul_add(av_3, t9);
    // TODO: Unsupported instruction: movk x12, #18936, lsl 16
    // TODO: Unsupported instruction: add.2d v3, v9, v11
    // TODO: Unsupported instruction: add.2d v7, v7, v13
    // TODO: Unsupported instruction: movk x12, #10922, lsl 32
    // TODO: Unsupported instruction: usra.2d v10, v8, #52
    // TODO: Unsupported instruction: usra.2d v12, v10, #52
    // TODO: Unsupported instruction: usra.2d v14, v12, #52
    // TODO: Unsupported instruction: movk x12, #11014, lsl 48
    // TODO: Unsupported instruction: usra.2d v15, v14, #52
    // TODO: Unsupported instruction: and.16b v8, v8, v4
    let t9 = t5.wrapping_mul(t1);
    // TODO: Unsupported instruction: and.16b v9, v10, v4
    // TODO: Unsupported instruction: and.16b v10, v12, v4
    // TODO: Unsupported instruction: and.16b v4, v14, v4
    let t5 = (((t5 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v8, v8
    let t10 = 37864;
    // TODO: Unsupported instruction: movk x14, #1815, lsl 16
    let (t4, _carry) = t9.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: movk x14, #28960, lsl 32
    // TODO: Unsupported instruction: movk x14, #17153, lsl 48
    let t9 = t6.wrapping_mul(t1);
    // TODO: Unsupported instruction: dup.2d v11, x14
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t8 = t4.mul_add(t7, t8);
    let t6 = (((t6 as u128) * (t1 as u128)) >> 64) as u64;
    let t9 = t2 - t8;
    let t9 = t4.mul_add(t7, t9);
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    let (t5, _carry) = t9.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x10, x10, hs
    // TODO: Unsupported instruction: add.2d v11, v15, v13
    let t9 = 46128;
    let (av_0, _carry) = t5.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    // TODO: Unsupported instruction: movk x13, #29964, lsl 16
    // TODO: Unsupported instruction: movk x13, #7587, lsl 32
    // TODO: Unsupported instruction: movk x13, #17161, lsl 48
    let t6 = t7.wrapping_mul(t1);
    // TODO: Unsupported instruction: dup.2d v12, x13
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t7 = (((t7 as u128) * (t1 as u128)) >> 64) as u64;
    let t9 = t4.mul_add(t8, t9);
    let t10 = t2 - t9;
    let t10 = t4.mul_add(t8, t10);
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x10, x11, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    // TODO: Unsupported instruction: add.2d v0, v0, v14
    let t7 = 52826;
    let (av_1, _carry) = t5.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x9, x10, hs
    // TODO: Unsupported instruction: movk x11, #57790, lsl 16
    // TODO: Unsupported instruction: movk x11, #55431, lsl 32
    let t6 = t8.wrapping_mul(t1);
    // TODO: Unsupported instruction: movk x11, #17196, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x11
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t1 = (((t8 as u128) * (t1 as u128)) >> 64) as u64;
    let t9 = t4.mul_add(t8, t9);
    let t10 = t2 - t9;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t10 = t4.mul_add(t8, t10);
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    // TODO: Unsupported instruction: add.2d v1, v1, v14
    let (av_2, _carry) = t5.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t5 = 31276;
    // TODO: Unsupported instruction: movk x9, #21262, lsl 16
    // TODO: Unsupported instruction: movk x9, #2304, lsl 32
    let av_3 = av_3.wrapping_add(t1);
    // TODO: Unsupported instruction: movk x9, #17182, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x9
    let t1 = 56431;
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t9 = t4.mul_add(t8, t9);
    let t10 = t2 - t9;
    // TODO: Unsupported instruction: movk x5, #30457, lsl 16
    let t10 = t4.mul_add(t8, t10);
    // TODO: Unsupported instruction: add.2d v7, v7, v13
    // TODO: Unsupported instruction: add.2d v2, v2, v14
    // TODO: Unsupported instruction: movk x5, #30012, lsl 32
    let t5 = 28672;
    // TODO: Unsupported instruction: movk x9, #24515, lsl 16
    // TODO: Unsupported instruction: movk x5, #6382, lsl 48
    // TODO: Unsupported instruction: movk x9, #54929, lsl 32
    // TODO: Unsupported instruction: movk x9, #17064, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x9
    let t5 = 59151;
    // TODO: Unsupported instruction: mov.16b v13, v5
    let t9 = t4.mul_add(t8, t9);
    // TODO: Unsupported instruction: movk x9, #41769, lsl 16
    let t10 = t2 - t9;
    let t10 = t4.mul_add(t8, t10);
    // TODO: Unsupported instruction: add.2d v3, v3, v13
    // TODO: Unsupported instruction: movk x9, #32276, lsl 32
    // TODO: Unsupported instruction: add.2d v7, v7, v14
    // TODO: Unsupported instruction: ucvtf.2d v8, v9
    let t6 = 44768;
    // TODO: Unsupported instruction: movk x9, #21677, lsl 48
    // TODO: Unsupported instruction: movk x10, #51919, lsl 16
    // TODO: Unsupported instruction: movk x10, #6346, lsl 32
    let t7 = 34015;
    // TODO: Unsupported instruction: movk x10, #17133, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x10
    // TODO: Unsupported instruction: mov.16b v12, v5
    // TODO: Unsupported instruction: movk x11, #20342, lsl 16
    let t8 = t4.mul_add(t5, t8);
    let t9 = t2 - t8;
    let t9 = t4.mul_add(t5, t9);
    // TODO: Unsupported instruction: movk x11, #13935, lsl 32
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    // TODO: Unsupported instruction: add.2d v9, v11, v13
    // TODO: Unsupported instruction: movk x11, #11030, lsl 48
    let t6 = 47492;
    // TODO: Unsupported instruction: movk x10, #23630, lsl 16
    // TODO: Unsupported instruction: movk x10, #49985, lsl 32
    let t8 = 13689;
    // TODO: Unsupported instruction: movk x10, #17168, lsl 48
    // TODO: Unsupported instruction: dup.2d v11, x10
    // TODO: Unsupported instruction: movk x12, #8159, lsl 16
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t8 = t4.mul_add(t7, t8);
    let t9 = t2 - t8;
    // TODO: Unsupported instruction: movk x12, #215, lsl 32
    let t9 = t4.mul_add(t7, t9);
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    // TODO: Unsupported instruction: add.2d v0, v0, v13
    // TODO: Unsupported instruction: movk x12, #4913, lsl 48
    let t6 = 57936;
    // TODO: Unsupported instruction: movk x10, #54828, lsl 16
    let t9 = t1.wrapping_mul(t2);
    // TODO: Unsupported instruction: movk x10, #18292, lsl 32
    // TODO: Unsupported instruction: movk x10, #17197, lsl 48
    // TODO: Unsupported instruction: dup.2d v11, x10
    let t1 = (((t1 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t8 = t4.mul_add(t7, t8);
    let t9 = t2 - t8;
    let (t4, _carry) = t9.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t9 = t4.mul_add(t7, t9);
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    let t6 = t5.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    let t9 = 17708;
    // TODO: Unsupported instruction: movk x13, #43915, lsl 16
    let t5 = (((t5 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x13, #64348, lsl 32
    // TODO: Unsupported instruction: movk x13, #17188, lsl 48
    let (t1, _carry) = t6.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x9, x9, hs
    // TODO: Unsupported instruction: dup.2d v11, x13
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t8 = t4.mul_add(t7, t8);
    let (av_0, _carry) = t1.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x5, x9, hs
    let t9 = t2 - t8;
    let t9 = t4.mul_add(t7, t9);
    // TODO: Unsupported instruction: add.2d v7, v7, v12
    let t5 = t7.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    let t6 = 29184;
    let t7 = (((t7 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x10, #20789, lsl 16
    // TODO: Unsupported instruction: movk x10, #19197, lsl 32
    // TODO: Unsupported instruction: movk x10, #17083, lsl 48
    let (t1, _carry) = t5.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x9, x11, hs
    // TODO: Unsupported instruction: dup.2d v11, x10
    // TODO: Unsupported instruction: mov.16b v12, v5
    let t8 = t4.mul_add(t7, t8);
    let (av_1, _carry) = t1.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x5, x9, hs
    let t9 = t2 - t8;
    let t9 = t4.mul_add(t7, t9);
    let t5 = t8.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v3, v3, v12
    // TODO: Unsupported instruction: add.2d v7, v7, v13
    // TODO: Unsupported instruction: ucvtf.2d v8, v10
    let t2 = (((t8 as u128) * (t2 as u128)) >> 64) as u64;
    let t6 = 58856;
    // TODO: Unsupported instruction: movk x10, #14953, lsl 16
    let (t1, _carry) = t5.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: movk x10, #15155, lsl 32
    // TODO: Unsupported instruction: movk x10, #17181, lsl 48
    // TODO: Unsupported instruction: dup.2d v10, x10
    let (av_2, _carry) = t1.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    // TODO: Unsupported instruction: mov.16b v11, v5
    let t7 = t4.mul_add(t6, t7);
    let t8 = t2 - t7;
    let av_3 = av_3.wrapping_add(t1);
    let t8 = t4.mul_add(t6, t8);
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    let t1 = 61005;
    // TODO: Unsupported instruction: add.2d v9, v9, v12
    let t2 = 35392;
    // TODO: Unsupported instruction: movk x6, #12477, lsl 16
    // TODO: Unsupported instruction: movk x5, #58262, lsl 16
    // TODO: Unsupported instruction: movk x6, #56780, lsl 32
    // TODO: Unsupported instruction: movk x6, #17142, lsl 48
    // TODO: Unsupported instruction: movk x5, #32851, lsl 32
    // TODO: Unsupported instruction: dup.2d v10, x6
    // TODO: Unsupported instruction: mov.16b v11, v5
    let t7 = t4.mul_add(t6, t7);
    // TODO: Unsupported instruction: movk x5, #11582, lsl 48
    let t8 = t2 - t7;
    let t8 = t4.mul_add(t6, t8);
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    let t2 = 37581;
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    let t5 = 9848;
    // TODO: Unsupported instruction: movk x6, #43836, lsl 16
    // TODO: Unsupported instruction: movk x9, #54501, lsl 16
    // TODO: Unsupported instruction: movk x9, #31540, lsl 32
    // TODO: Unsupported instruction: movk x9, #17170, lsl 48
    // TODO: Unsupported instruction: movk x6, #36286, lsl 32
    // TODO: Unsupported instruction: dup.2d v10, x9
    // TODO: Unsupported instruction: mov.16b v11, v5
    let t7 = t4.mul_add(t6, t7);
    // TODO: Unsupported instruction: movk x6, #51783, lsl 48
    let t8 = t2 - t7;
    let t8 = t4.mul_add(t6, t8);
    let t5 = 10899;
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    let t6 = 9584;
    // TODO: Unsupported instruction: movk x9, #30709, lsl 16
    // TODO: Unsupported instruction: movk x10, #63883, lsl 16
    // TODO: Unsupported instruction: movk x10, #18253, lsl 32
    // TODO: Unsupported instruction: movk x9, #61551, lsl 32
    // TODO: Unsupported instruction: movk x10, #17190, lsl 48
    // TODO: Unsupported instruction: dup.2d v10, x10
    // TODO: Unsupported instruction: mov.16b v11, v5
    // TODO: Unsupported instruction: movk x9, #45784, lsl 48
    let t7 = t4.mul_add(t6, t7);
    let t8 = t2 - t7;
    let t8 = t4.mul_add(t6, t8);
    let t6 = 36612;
    // TODO: Unsupported instruction: add.2d v7, v7, v11
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    // TODO: Unsupported instruction: movk x10, #63402, lsl 16
    let t7 = 51712;
    // TODO: Unsupported instruction: movk x11, #16093, lsl 16
    // TODO: Unsupported instruction: movk x11, #30633, lsl 32
    // TODO: Unsupported instruction: movk x10, #47623, lsl 32
    // TODO: Unsupported instruction: movk x11, #17068, lsl 48
    // TODO: Unsupported instruction: dup.2d v10, x11
    // TODO: Unsupported instruction: mov.16b v11, v5
    // TODO: Unsupported instruction: movk x10, #9430, lsl 48
    let t7 = t4.mul_add(t6, t7);
    let t8 = t2 - t7;
    let t7 = t1.wrapping_mul(t3);
    let t8 = t4.mul_add(t6, t8);
    // TODO: Unsupported instruction: add.2d v3, v3, v11
    // TODO: Unsupported instruction: add.2d v7, v7, v12
    let t1 = (((t1 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v4, v4
    let t8 = 34724;
    let (t4, _carry) = t7.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: movk x12, #40393, lsl 16
    // TODO: Unsupported instruction: movk x12, #23752, lsl 32
    // TODO: Unsupported instruction: movk x12, #17184, lsl 48
    let t7 = t2.wrapping_mul(t3);
    // TODO: Unsupported instruction: dup.2d v8, x12
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t6 = t0.mul_add(t4, t6);
    let t2 = (((t2 as u128) * (t3 as u128)) >> 64) as u64;
    let t7 = t2 - t6;
    let t7 = t0.mul_add(t4, t7);
    let (t1, _carry) = t7.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: add.2d v0, v0, v10
    // TODO: Unsupported instruction: add.2d v8, v9, v11
    let t7 = 25532;
    let (av_0, _carry) = t1.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    // TODO: Unsupported instruction: movk x11, #31025, lsl 16
    // TODO: Unsupported instruction: movk x11, #10002, lsl 32
    // TODO: Unsupported instruction: movk x11, #17199, lsl 48
    let t2 = t5.wrapping_mul(t3);
    // TODO: Unsupported instruction: dup.2d v9, x11
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t5 = (((t5 as u128) * (t3 as u128)) >> 64) as u64;
    let t6 = t0.mul_add(t5, t6);
    let t7 = t2 - t6;
    let t7 = t0.mul_add(t5, t7);
    let (t1, _carry) = t2.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x6, x9, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v10
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    let (av_1, _carry) = t1.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t2 = 18830;
    // TODO: Unsupported instruction: movk x6, #2465, lsl 16
    // TODO: Unsupported instruction: movk x6, #36348, lsl 32
    let t5 = t6.wrapping_mul(t3);
    // TODO: Unsupported instruction: movk x6, #17194, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x6
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t2 = (((t6 as u128) * (t3 as u128)) >> 64) as u64;
    let t6 = t0.mul_add(t5, t6);
    let t7 = t2 - t6;
    let (t1, _carry) = t5.overflowing_add(t1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    let t7 = t0.mul_add(t5, t7);
    // TODO: Unsupported instruction: add.2d v2, v2, v10
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    let (av_2, _carry) = t1.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t2 = 21566;
    // TODO: Unsupported instruction: movk x6, #43708, lsl 16
    // TODO: Unsupported instruction: movk x6, #57685, lsl 32
    let av_3 = av_3.wrapping_add(t1);
    // TODO: Unsupported instruction: movk x6, #17185, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x6
    let t1 = 65535;
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t6 = t0.mul_add(t5, t6);
    let t7 = t2 - t6;
    // TODO: Unsupported instruction: movk x5, #61439, lsl 16
    let t7 = t0.mul_add(t5, t7);
    // TODO: Unsupported instruction: add.2d v7, v7, v10
    // TODO: Unsupported instruction: movk x5, #62867, lsl 32
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    let t2 = 3072;
    // TODO: Unsupported instruction: movk x6, #8058, lsl 16
    // TODO: Unsupported instruction: movk x5, #49889, lsl 48
    // TODO: Unsupported instruction: movk x6, #46097, lsl 32
    // TODO: Unsupported instruction: movk x6, #17047, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x6
    let t1 = t1.wrapping_mul(t4);
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t6 = t0.mul_add(t5, t6);
    let t2 = 1;
    let t7 = t2 - t6;
    let t7 = t0.mul_add(t5, t7);
    // TODO: Unsupported instruction: add.2d v3, v3, v10
    // TODO: Unsupported instruction: movk x6, #61440, lsl 16
    // TODO: Unsupported instruction: add.2d v4, v7, v11
    let t3 = 65535;
    // TODO: Unsupported instruction: movk x6, #62867, lsl 32
    // TODO: Unsupported instruction: movk x7, #61439, lsl 16
    // TODO: Unsupported instruction: movk x7, #62867, lsl 32
    // TODO: Unsupported instruction: movk x7, #1, lsl 48
    // TODO: Unsupported instruction: movk x6, #17377, lsl 48
    // TODO: Unsupported instruction: umov x9, v8.d[0]
    // TODO: Unsupported instruction: umov x10, v8.d[1]
    let t5 = t5.wrapping_mul(t3);
    let t7 = 28817;
    let t3 = t6.wrapping_mul(t3);
    let t5 = t5 & t0;
    // TODO: Unsupported instruction: movk x11, #31161, lsl 16
    let t0 = t3 & t0;
    // TODO: Unsupported instruction: ins v7.d[0], x9
    // TODO: Unsupported instruction: ins v7.d[1], x4
    // TODO: Unsupported instruction: ucvtf.2d v7, v7
    // TODO: Unsupported instruction: movk x11, #59464, lsl 32
    let t0 = 16;
    // TODO: Unsupported instruction: movk x4, #22847, lsl 32
    // TODO: Unsupported instruction: movk x4, #17151, lsl 48
    // TODO: Unsupported instruction: movk x11, #10291, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x4
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t0 = 22621;
    let t6 = t3.mul_add(t5, t6);
    let t7 = t2 - t6;
    let t7 = t3.mul_add(t5, t7);
    // TODO: Unsupported instruction: movk x4, #33153, lsl 16
    // TODO: Unsupported instruction: add.2d v0, v0, v10
    // TODO: Unsupported instruction: add.2d v8, v8, v11
    // TODO: Unsupported instruction: movk x4, #17846, lsl 32
    let t3 = 20728;
    // TODO: Unsupported instruction: movk x7, #23588, lsl 16
    // TODO: Unsupported instruction: movk x7, #7790, lsl 32
    // TODO: Unsupported instruction: movk x4, #47184, lsl 48
    // TODO: Unsupported instruction: movk x7, #17170, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x7
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t3 = 41001;
    let t6 = t3.mul_add(t5, t6);
    let t7 = t2 - t6;
    // TODO: Unsupported instruction: movk x7, #57649, lsl 16
    let t7 = t3.mul_add(t5, t7);
    // TODO: Unsupported instruction: add.2d v1, v1, v10
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    // TODO: Unsupported instruction: movk x7, #20082, lsl 32
    let t5 = 16000;
    // TODO: Unsupported instruction: movk x9, #53891, lsl 16
    // TODO: Unsupported instruction: movk x9, #5509, lsl 32
    // TODO: Unsupported instruction: movk x7, #12388, lsl 48
    // TODO: Unsupported instruction: movk x9, #17144, lsl 48
    // TODO: Unsupported instruction: dup.2d v9, x9
    let t5 = t2.wrapping_mul(t1);
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t6 = t3.mul_add(t5, t6);
    let t7 = t2 - t6;
    let t2 = (((t2 as u128) * (t1 as u128)) >> 64) as u64;
    let t7 = t3.mul_add(t5, t7);
    // TODO: Unsupported instruction: add.2d v2, v2, v10
    // TODO: Unsupported instruction: cmn x9, x8
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: add.2d v9, v1, v11
    let t4 = 46800;
    // TODO: Unsupported instruction: movk x8, #2568, lsl 16
    let t5 = t7.wrapping_mul(t1);
    // TODO: Unsupported instruction: movk x8, #1335, lsl 32
    // TODO: Unsupported instruction: movk x8, #17188, lsl 48
    // TODO: Unsupported instruction: dup.2d v1, x8
    let t4 = (((t7 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v10, v5
    let t6 = t3.mul_add(av_1, t6);
    let (t2, _carry) = t5.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x8, x8, hs
    let t7 = t2 - t6;
    let t7 = t3.mul_add(av_1, t7);
    // TODO: Unsupported instruction: add.2d v1, v4, v10
    let (av_0, _carry) = t2.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x6, x8, hs
    // TODO: Unsupported instruction: add.2d v4, v2, v11
    let t4 = 39040;
    // TODO: Unsupported instruction: movk x8, #14704, lsl 16
    let t5 = t0.wrapping_mul(t1);
    // TODO: Unsupported instruction: movk x8, #12839, lsl 32
    // TODO: Unsupported instruction: movk x8, #17096, lsl 48
    let t0 = (((t0 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v2, x8
    // TODO: Unsupported instruction: mov.16b v5, v5
    let t1 = t3.mul_add(av_2, t1);
    let (t2, _carry) = t5.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    let t2 = t2 - t1;
    let t2 = t3.mul_add(av_2, t2);
    let (av_1, _carry) = t2.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: add.2d v5, v3, v5
    // TODO: Unsupported instruction: add.2d v6, v1, v6
    // TODO: Unsupported instruction: ssra.2d v0, v8, #52
    let t2 = t3.wrapping_mul(t1);
    // TODO: Unsupported instruction: ssra.2d v9, v0, #52
    // TODO: Unsupported instruction: ssra.2d v4, v9, #52
    // TODO: Unsupported instruction: ssra.2d v6, v4, #52
    let t1 = (((t3 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ssra.2d v5, v6, #52
    // TODO: Unsupported instruction: ushr.2d v1, v9, #12
    let (t0, _carry) = t2.overflowing_add(t0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: ushr.2d v2, v4, #24
    // TODO: Unsupported instruction: ushr.2d v3, v6, #36
    // TODO: Unsupported instruction: sli.2d v0, v9, #52
    let (av_2, _carry) = t0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    // TODO: Unsupported instruction: sli.2d v1, v4, #40
    // TODO: Unsupported instruction: sli.2d v2, v6, #28
    // TODO: Unsupported instruction: sli.2d v3, v5, #16
    let av_3 = av_3.wrapping_add(t0);

    let out = [av_0, av_1, av_2, av_3];
    let outv = [av_0, av_1, av_2, av_3];

    (out, outv)
}
