// GENERATED FILE, DO NOT EDIT!
// Generated by HLA framework for WASM SIMD optimization
// Note: Imports are in the parent module (mod.rs)

#[inline(always)]
pub fn montgomery_interleaved_3(
    _guard: &RoundingGuard<Zero>,
    a: [u64; 4],
    b: [u64; 4],
    av: [Simd<u64, 2>; 4],
    bv: [Simd<u64, 2>; 4]
) -> ([u64; 4], [Simd<u64, 2>; 4]) {
    let a_0 = a[0];
    let a_1 = a[1];
    let a_2 = a[2];
    let a_3 = a[3];
    let b_0 = b[0];
    let b_1 = b[1];
    let b_2 = b[2];
    let b_3 = b[3];
    let av_0 = av[0];
    let av_1 = av[1];
    let av_2 = av[2];
    let av_3 = av[3];
    let bv_0 = bv[0];
    let bv_1 = bv[1];
    let bv_2 = bv[2];
    let bv_3 = bv[3];

    let t0 = 4503599627370495;
    // TODO: Unsupported instruction: dup.2d v8, x8
    let t1 = av_0.wrapping_mul(bv_0);
    let t2 = 5075556780046548992;
    // TODO: Unsupported instruction: dup.2d v9, x10
    let t2 = 1;
    let t3 = (((av_0 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x10, #18032, lsl 48
    // TODO: Unsupported instruction: dup.2d v10, x10
    // TODO: Unsupported instruction: shl.2d v11, v1, #14
    let t2 = av_1.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: shl.2d v12, v2, #26
    // TODO: Unsupported instruction: shl.2d v13, v3, #38
    // TODO: Unsupported instruction: ushr.2d v3, v3, #14
    let t4 = (((av_1 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: shl.2d v14, v0, #2
    // TODO: Unsupported instruction: usra.2d v11, v0, #50
    let (t2, _carry) = t2.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x11, x12, hs
    // TODO: Unsupported instruction: usra.2d v12, v1, #38
    // TODO: Unsupported instruction: usra.2d v13, v2, #26
    // TODO: Unsupported instruction: and.16b v0, v14, v8
    let t4 = av_2.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: and.16b v1, v11, v8
    // TODO: Unsupported instruction: and.16b v2, v12, v8
    // TODO: Unsupported instruction: and.16b v11, v13, v8
    let t5 = (((av_2 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: shl.2d v12, v5, #14
    // TODO: Unsupported instruction: shl.2d v13, v6, #26
    // TODO: Unsupported instruction: shl.2d v14, v7, #38
    let (t3, _carry) = t4.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x12, x13, hs
    // TODO: Unsupported instruction: ushr.2d v7, v7, #14
    // TODO: Unsupported instruction: shl.2d v15, v4, #2
    let t5 = av_3.wrapping_mul(bv_0);
    // TODO: Unsupported instruction: usra.2d v12, v4, #50
    // TODO: Unsupported instruction: usra.2d v13, v5, #38
    // TODO: Unsupported instruction: usra.2d v14, v6, #26
    let bv_0 = (((av_3 as u128) * (bv_0 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: and.16b v4, v15, v8
    // TODO: Unsupported instruction: and.16b v5, v12, v8
    // TODO: Unsupported instruction: and.16b v6, v13, v8
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    // TODO: Unsupported instruction: and.16b v12, v14, v8
    let t5 = 13605374474286268416;
    // TODO: Unsupported instruction: dup.2d v13, x13
    let t5 = av_0.wrapping_mul(bv_1);
    let t6 = 6440147467139809280;
    // TODO: Unsupported instruction: dup.2d v14, x14
    let t6 = (((av_0 as u128) * (bv_1 as u128)) >> 64) as u64;
    let t7 = 3688448094816436224;
    // TODO: Unsupported instruction: dup.2d v15, x15
    let t7 = 9209861237972664320;
    let (t2, _carry) = t5.overflowing_add(t2);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: dup.2d v16, x15
    let t6 = 12218265789056155648;
    // TODO: Unsupported instruction: dup.2d v17, x14
    let t6 = av_1.wrapping_mul(bv_1);
    let t7 = 17739678932212383744;
    // TODO: Unsupported instruction: dup.2d v18, x15
    let t7 = 2301339409586323456;
    let t8 = (((av_1 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v19, x15
    let t7 = 7822752552742551552;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x16, hs
    // TODO: Unsupported instruction: dup.2d v20, x15
    let t7 = 5071053180419178496;
    // TODO: Unsupported instruction: dup.2d v21, x15
    let (t3, _carry) = t5.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    let t6 = 16352570246982270976;
    // TODO: Unsupported instruction: dup.2d v22, x14
    // TODO: Unsupported instruction: ucvtf.2d v0, v0
    let t6 = av_2.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: ucvtf.2d v1, v1
    // TODO: Unsupported instruction: ucvtf.2d v2, v2
    // TODO: Unsupported instruction: ucvtf.2d v11, v11
    let t7 = (((av_2 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ucvtf.2d v3, v3
    // TODO: Unsupported instruction: ucvtf.2d v4, v4
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x15, hs
    // TODO: Unsupported instruction: ucvtf.2d v5, v5
    // TODO: Unsupported instruction: ucvtf.2d v6, v6
    // TODO: Unsupported instruction: ucvtf.2d v12, v12
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: ucvtf.2d v7, v7
    // TODO: Unsupported instruction: mov.16b v23, v9
    let t15 = av_0.mul_add(bv_0, t15);
    let t6 = av_3.wrapping_mul(bv_1);
    let t16 = t2 - t15;
    let t16 = av_0.mul_add(bv_0, t16);
    // TODO: Unsupported instruction: add.2d v15, v15, v23
    let bv_1 = (((av_3 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v13, v13, v24
    // TODO: Unsupported instruction: mov.16b v23, v9
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    let t15 = av_0.mul_add(bv_1, t15);
    let t16 = t2 - t15;
    let t16 = av_0.mul_add(bv_1, t16);
    let (bv_0, _carry) = t5.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: add.2d v17, v17, v23
    // TODO: Unsupported instruction: add.2d v15, v15, v24
    // TODO: Unsupported instruction: mov.16b v23, v9
    let t5 = av_0.wrapping_mul(bv_2);
    let t15 = av_0.mul_add(bv_2, t15);
    let t16 = t2 - t15;
    let t16 = av_0.mul_add(bv_2, t16);
    let t6 = (((av_0 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v19, v19, v23
    // TODO: Unsupported instruction: add.2d v17, v17, v24
    let (t3, _carry) = t5.overflowing_add(t3);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: mov.16b v23, v9
    let t15 = av_0.mul_add(t4, t15);
    let t16 = t2 - t15;
    let t6 = av_1.wrapping_mul(bv_2);
    let t16 = av_0.mul_add(t4, t16);
    // TODO: Unsupported instruction: add.2d v21, v21, v23
    // TODO: Unsupported instruction: add.2d v19, v19, v24
    let t7 = (((av_1 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v23, v9
    let t15 = av_0.mul_add(bv_3, t15);
    let t16 = t2 - t15;
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x15, hs
    let t16 = av_0.mul_add(bv_3, t16);
    // TODO: Unsupported instruction: add.2d v0, v22, v23
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: add.2d v21, v21, v24
    // TODO: Unsupported instruction: mov.16b v22, v9
    let t14 = av_1.mul_add(bv_0, t14);
    let t6 = av_2.wrapping_mul(bv_2);
    let t15 = t2 - t14;
    let t15 = av_1.mul_add(bv_0, t15);
    // TODO: Unsupported instruction: add.2d v17, v17, v22
    let t7 = (((av_2 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v15, v15, v23
    // TODO: Unsupported instruction: mov.16b v22, v9
    let t14 = av_1.mul_add(bv_1, t14);
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x14, x15, hs
    let t15 = t2 - t14;
    let t15 = av_1.mul_add(bv_1, t15);
    let (bv_0, _carry) = t5.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x13, x14, hs
    // TODO: Unsupported instruction: add.2d v19, v19, v22
    // TODO: Unsupported instruction: add.2d v17, v17, v23
    // TODO: Unsupported instruction: mov.16b v22, v9
    let t6 = av_3.wrapping_mul(bv_2);
    let t14 = av_1.mul_add(bv_2, t14);
    let t15 = t2 - t14;
    let t15 = av_1.mul_add(bv_2, t15);
    let bv_2 = (((av_3 as u128) * (bv_2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v21, v21, v22
    // TODO: Unsupported instruction: add.2d v19, v19, v23
    // TODO: Unsupported instruction: mov.16b v22, v9
    let (t5, _carry) = t6.overflowing_add(t5);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    let t14 = av_1.mul_add(t4, t14);
    let t15 = t2 - t14;
    let t15 = av_1.mul_add(t4, t15);
    let (bv_1, _carry) = t5.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: add.2d v0, v0, v22
    // TODO: Unsupported instruction: add.2d v21, v21, v23
    let t5 = av_0.wrapping_mul(bv_3);
    // TODO: Unsupported instruction: mov.16b v22, v9
    let t14 = av_1.mul_add(bv_3, t14);
    let t15 = t2 - t14;
    let av_0 = (((av_0 as u128) * (bv_3 as u128)) >> 64) as u64;
    let t15 = av_1.mul_add(bv_3, t15);
    // TODO: Unsupported instruction: add.2d v1, v20, v22
    // TODO: Unsupported instruction: add.2d v0, v0, v23
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x0, x0, hs
    // TODO: Unsupported instruction: mov.16b v20, v9
    let t12 = av_2.mul_add(bv_0, t12);
    let t14 = t2 - t12;
    let t5 = av_1.wrapping_mul(bv_3);
    let t14 = av_2.mul_add(bv_0, t14);
    // TODO: Unsupported instruction: add.2d v19, v19, v20
    let av_1 = (((av_1 as u128) * (bv_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v17, v17, v22
    // TODO: Unsupported instruction: mov.16b v20, v9
    let t12 = av_2.mul_add(bv_1, t12);
    let (av_0, _carry) = t5.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    let t14 = t2 - t12;
    let t14 = av_2.mul_add(bv_1, t14);
    // TODO: Unsupported instruction: add.2d v20, v21, v20
    let (av_0, _carry) = av_0.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x1, x1, hs
    // TODO: Unsupported instruction: add.2d v19, v19, v22
    // TODO: Unsupported instruction: mov.16b v21, v9
    let t13 = av_2.mul_add(bv_2, t13);
    let bv_0 = av_2.wrapping_mul(bv_3);
    let t14 = t2 - t13;
    let t14 = av_2.mul_add(bv_2, t14);
    let av_2 = (((av_2 as u128) * (bv_3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v0, v0, v21
    // TODO: Unsupported instruction: add.2d v20, v20, v22
    // TODO: Unsupported instruction: mov.16b v21, v9
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    let t13 = av_2.mul_add(t4, t13);
    let t14 = t2 - t13;
    let t14 = av_2.mul_add(t4, t14);
    let (av_1, _carry) = av_1.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x2, x2, hs
    // TODO: Unsupported instruction: add.2d v1, v1, v21
    // TODO: Unsupported instruction: add.2d v0, v0, v22
    // TODO: Unsupported instruction: mov.16b v21, v9
    let bv_0 = av_3.wrapping_mul(bv_3);
    let t13 = av_2.mul_add(bv_3, t13);
    let t14 = t2 - t13;
    let av_3 = (((av_3 as u128) * (bv_3 as u128)) >> 64) as u64;
    let t14 = av_2.mul_add(bv_3, t14);
    // TODO: Unsupported instruction: add.2d v2, v18, v21
    // TODO: Unsupported instruction: add.2d v1, v1, v22
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    // TODO: Unsupported instruction: mov.16b v18, v9
    let t10 = t3.mul_add(bv_0, t10);
    let t13 = t2 - t10;
    let (av_2, _carry) = av_2.overflowing_add(bv_2);
    // TODO: Unsupported instruction: cinc x3, x3, hs
    let t13 = t3.mul_add(bv_0, t13);
    // TODO: Unsupported instruction: add.2d v18, v20, v18
    // TODO: Unsupported instruction: add.2d v19, v19, v21
    let bv_0 = 48718;
    // TODO: Unsupported instruction: mov.16b v20, v9
    let t12 = t3.mul_add(bv_1, t12);
    // TODO: Unsupported instruction: movk x4, #4732, lsl 16
    let t13 = t2 - t12;
    let t13 = t3.mul_add(bv_1, t13);
    // TODO: Unsupported instruction: add.2d v0, v0, v20
    // TODO: Unsupported instruction: movk x4, #45078, lsl 32
    // TODO: Unsupported instruction: add.2d v18, v18, v21
    // TODO: Unsupported instruction: mov.16b v20, v9
    let t12 = t3.mul_add(bv_2, t12);
    // TODO: Unsupported instruction: movk x4, #39852, lsl 48
    let t13 = t2 - t12;
    let t13 = t3.mul_add(bv_2, t13);
    // TODO: Unsupported instruction: add.2d v1, v1, v20
    let bv_1 = 16676;
    // TODO: Unsupported instruction: add.2d v0, v0, v21
    // TODO: Unsupported instruction: mov.16b v20, v9
    // TODO: Unsupported instruction: movk x5, #12692, lsl 16
    let t12 = t3.mul_add(t4, t12);
    let t13 = t2 - t12;
    let t13 = t3.mul_add(t4, t13);
    // TODO: Unsupported instruction: movk x5, #20986, lsl 32
    // TODO: Unsupported instruction: add.2d v2, v2, v20
    // TODO: Unsupported instruction: add.2d v1, v1, v21
    // TODO: Unsupported instruction: mov.16b v20, v9
    // TODO: Unsupported instruction: movk x5, #2848, lsl 48
    let t12 = t3.mul_add(bv_3, t12);
    let t13 = t2 - t12;
    let t13 = t3.mul_add(bv_3, t13);
    let bv_2 = 51052;
    // TODO: Unsupported instruction: add.2d v11, v16, v20
    // TODO: Unsupported instruction: add.2d v2, v2, v21
    // TODO: Unsupported instruction: movk x6, #24721, lsl 16
    // TODO: Unsupported instruction: mov.16b v16, v9
    let t8 = av_3.mul_add(bv_0, t8);
    let t12 = t2 - t8;
    // TODO: Unsupported instruction: movk x6, #61092, lsl 32
    let t12 = av_3.mul_add(bv_0, t12);
    // TODO: Unsupported instruction: add.2d v0, v0, v16
    // TODO: Unsupported instruction: add.2d v4, v18, v20
    // TODO: Unsupported instruction: movk x6, #45156, lsl 48
    // TODO: Unsupported instruction: mov.16b v16, v9
    let t8 = av_3.mul_add(bv_1, t8);
    let t10 = t2 - t8;
    let bv_3 = 3197;
    let t10 = av_3.mul_add(bv_1, t10);
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    // TODO: Unsupported instruction: movk x7, #18936, lsl 16
    // TODO: Unsupported instruction: add.2d v0, v0, v18
    // TODO: Unsupported instruction: mov.16b v5, v9
    let bv_1 = av_3.mul_add(bv_2, bv_1);
    // TODO: Unsupported instruction: movk x7, #10922, lsl 32
    let t8 = t2 - bv_1;
    let t8 = av_3.mul_add(bv_2, t8);
    // TODO: Unsupported instruction: add.2d v2, v2, v5
    // TODO: Unsupported instruction: movk x7, #11014, lsl 48
    // TODO: Unsupported instruction: add.2d v1, v1, v16
    // TODO: Unsupported instruction: mov.16b v5, v9
    let bv_1 = av_3.mul_add(t4, bv_1);
    let t5 = bv_0.wrapping_mul(t1);
    let bv_2 = t2 - bv_1;
    let bv_2 = av_3.mul_add(t4, bv_2);
    let bv_0 = (((bv_0 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: add.2d v5, v11, v5
    // TODO: Unsupported instruction: add.2d v2, v2, v6
    // TODO: Unsupported instruction: mov.16b v6, v9
    let (t4, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    let bv_2 = av_3.mul_add(bv_3, bv_2);
    let t3 = t2 - bv_2;
    let t3 = av_3.mul_add(bv_3, t3);
    let t5 = bv_1.wrapping_mul(t1);
    // TODO: Unsupported instruction: add.2d v3, v14, v6
    // TODO: Unsupported instruction: add.2d v5, v5, v11
    // TODO: Unsupported instruction: usra.2d v15, v13, #52
    let bv_1 = (((bv_1 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: usra.2d v17, v15, #52
    // TODO: Unsupported instruction: usra.2d v19, v17, #52
    // TODO: Unsupported instruction: usra.2d v4, v19, #52
    let (bv_0, _carry) = t5.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: and.16b v6, v13, v8
    // TODO: Unsupported instruction: and.16b v7, v15, v8
    let (av_0, _carry) = bv_0.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    // TODO: Unsupported instruction: and.16b v11, v17, v8
    // TODO: Unsupported instruction: and.16b v8, v19, v8
    // TODO: Unsupported instruction: ucvtf.2d v6, v6
    let bv_1 = bv_2.wrapping_mul(t1);
    let t5 = 37864;
    // TODO: Unsupported instruction: movk x13, #1815, lsl 16
    // TODO: Unsupported instruction: movk x13, #28960, lsl 32
    let bv_2 = (((bv_2 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x13, #17153, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x13
    // TODO: Unsupported instruction: mov.16b v13, v9
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t5 = bv_2.mul_add(t4, t5);
    let t6 = t2 - t5;
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    let t6 = bv_2.mul_add(t4, t6);
    // TODO: Unsupported instruction: add.2d v0, v0, v13
    // TODO: Unsupported instruction: add.2d v4, v4, v14
    let bv_1 = bv_3.wrapping_mul(t1);
    let bv_2 = 46128;
    // TODO: Unsupported instruction: movk x6, #29964, lsl 16
    // TODO: Unsupported instruction: movk x6, #7587, lsl 32
    let bv_3 = (((bv_3 as u128) * (t1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x6, #17161, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x6
    // TODO: Unsupported instruction: mov.16b v13, v9
    let (bv_0, _carry) = bv_1.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x7, hs
    let t5 = bv_2.mul_add(t4, t5);
    let t6 = t2 - t5;
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    let t6 = bv_2.mul_add(t4, t6);
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    // TODO: Unsupported instruction: add.2d v0, v0, v14
    let av_3 = av_3.wrapping_add(bv_0);
    let bv_0 = 52826;
    // TODO: Unsupported instruction: movk x4, #57790, lsl 16
    // TODO: Unsupported instruction: movk x4, #55431, lsl 32
    let bv_1 = 56431;
    // TODO: Unsupported instruction: movk x4, #17196, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x4
    // TODO: Unsupported instruction: mov.16b v13, v9
    // TODO: Unsupported instruction: movk x5, #30457, lsl 16
    let t5 = bv_2.mul_add(t4, t5);
    let t6 = t2 - t5;
    // TODO: Unsupported instruction: movk x5, #30012, lsl 32
    let t6 = bv_2.mul_add(t4, t6);
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    // TODO: Unsupported instruction: add.2d v1, v1, v14
    // TODO: Unsupported instruction: movk x5, #6382, lsl 48
    let bv_0 = 31276;
    // TODO: Unsupported instruction: movk x4, #21262, lsl 16
    // TODO: Unsupported instruction: movk x4, #2304, lsl 32
    let bv_2 = 59151;
    // TODO: Unsupported instruction: movk x4, #17182, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x4
    // TODO: Unsupported instruction: mov.16b v13, v9
    // TODO: Unsupported instruction: movk x6, #41769, lsl 16
    let t5 = bv_2.mul_add(t4, t5);
    let t6 = t2 - t5;
    // TODO: Unsupported instruction: movk x6, #32276, lsl 32
    let t6 = bv_2.mul_add(t4, t6);
    // TODO: Unsupported instruction: add.2d v5, v5, v13
    // TODO: Unsupported instruction: add.2d v2, v2, v14
    // TODO: Unsupported instruction: movk x6, #21677, lsl 48
    let bv_0 = 28672;
    // TODO: Unsupported instruction: movk x4, #24515, lsl 16
    // TODO: Unsupported instruction: movk x4, #54929, lsl 32
    let bv_3 = 34015;
    // TODO: Unsupported instruction: movk x4, #17064, lsl 48
    // TODO: Unsupported instruction: dup.2d v12, x4
    // TODO: Unsupported instruction: mov.16b v13, v9
    // TODO: Unsupported instruction: movk x7, #20342, lsl 16
    let t5 = bv_2.mul_add(t4, t5);
    let t6 = t2 - t5;
    // TODO: Unsupported instruction: movk x7, #13935, lsl 32
    let t6 = bv_2.mul_add(t4, t6);
    // TODO: Unsupported instruction: add.2d v3, v3, v13
    // TODO: Unsupported instruction: add.2d v5, v5, v14
    // TODO: Unsupported instruction: movk x7, #11030, lsl 48
    // TODO: Unsupported instruction: ucvtf.2d v6, v7
    let bv_0 = 44768;
    // TODO: Unsupported instruction: movk x4, #51919, lsl 16
    let t1 = 13689;
    // TODO: Unsupported instruction: movk x4, #6346, lsl 32
    // TODO: Unsupported instruction: movk x4, #17133, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x4
    // TODO: Unsupported instruction: movk x9, #8159, lsl 16
    // TODO: Unsupported instruction: mov.16b v12, v9
    let t4 = bv_2.mul_add(bv_3, t4);
    // TODO: Unsupported instruction: movk x9, #215, lsl 32
    let t5 = t2 - t4;
    let t5 = bv_2.mul_add(bv_3, t5);
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    // TODO: Unsupported instruction: movk x9, #4913, lsl 48
    // TODO: Unsupported instruction: add.2d v4, v4, v13
    let bv_0 = 47492;
    // TODO: Unsupported instruction: movk x4, #23630, lsl 16
    let t5 = bv_1.wrapping_mul(t2);
    // TODO: Unsupported instruction: movk x4, #49985, lsl 32
    // TODO: Unsupported instruction: movk x4, #17168, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x4
    let bv_0 = (((bv_1 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: mov.16b v12, v9
    let t4 = bv_2.mul_add(bv_3, t4);
    let (bv_1, _carry) = t5.overflowing_add(t4);
    // TODO: Unsupported instruction: cinc x4, x4, hs
    let t5 = t2 - t4;
    let t5 = bv_2.mul_add(bv_3, t5);
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    let t4 = bv_2.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v0, v0, v13
    let t5 = 57936;
    // TODO: Unsupported instruction: movk x13, #54828, lsl 16
    let bv_2 = (((bv_2 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x13, #18292, lsl 32
    // TODO: Unsupported instruction: movk x13, #17197, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x13
    let (bv_0, _carry) = t4.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: mov.16b v12, v9
    let t4 = bv_2.mul_add(bv_3, t4);
    let (av_0, _carry) = bv_0.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x4, x6, hs
    let t5 = t2 - t4;
    let t5 = bv_2.mul_add(bv_3, t5);
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    let bv_2 = bv_3.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v1, v1, v13
    let t4 = 17708;
    // TODO: Unsupported instruction: movk x12, #43915, lsl 16
    let bv_3 = (((bv_3 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x12, #64348, lsl 32
    // TODO: Unsupported instruction: movk x12, #17188, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x12
    let (bv_0, _carry) = bv_2.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x6, x7, hs
    // TODO: Unsupported instruction: mov.16b v12, v9
    let t4 = bv_2.mul_add(bv_3, t4);
    let t5 = t2 - t4;
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x4, x6, hs
    let t5 = bv_2.mul_add(bv_3, t5);
    // TODO: Unsupported instruction: add.2d v5, v5, v12
    let bv_2 = t1.wrapping_mul(t2);
    // TODO: Unsupported instruction: add.2d v2, v2, v13
    let bv_3 = 29184;
    // TODO: Unsupported instruction: movk x7, #20789, lsl 16
    let t1 = (((t1 as u128) * (t2 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x7, #19197, lsl 32
    // TODO: Unsupported instruction: movk x7, #17083, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x7
    let (bv_0, _carry) = bv_2.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x6, x9, hs
    // TODO: Unsupported instruction: mov.16b v12, v9
    let t4 = bv_2.mul_add(bv_3, t4);
    let t5 = t2 - t4;
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x6, hs
    let t5 = bv_2.mul_add(bv_3, t5);
    // TODO: Unsupported instruction: add.2d v3, v3, v12
    let av_3 = av_3.wrapping_add(bv_0);
    // TODO: Unsupported instruction: add.2d v5, v5, v13
    // TODO: Unsupported instruction: ucvtf.2d v6, v11
    let bv_0 = 58856;
    let bv_2 = 61005;
    // TODO: Unsupported instruction: movk x4, #14953, lsl 16
    // TODO: Unsupported instruction: movk x4, #15155, lsl 32
    // TODO: Unsupported instruction: movk x4, #17181, lsl 48
    // TODO: Unsupported instruction: movk x6, #58262, lsl 16
    // TODO: Unsupported instruction: dup.2d v7, x4
    // TODO: Unsupported instruction: mov.16b v11, v9
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x6, #32851, lsl 32
    let t4 = t2 - t3;
    let t4 = bv_2.mul_add(bv_3, t4);
    // TODO: Unsupported instruction: movk x6, #11582, lsl 48
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    // TODO: Unsupported instruction: add.2d v4, v4, v12
    let bv_0 = 35392;
    let bv_3 = 37581;
    // TODO: Unsupported instruction: movk x4, #12477, lsl 16
    // TODO: Unsupported instruction: movk x4, #56780, lsl 32
    // TODO: Unsupported instruction: movk x4, #17142, lsl 48
    // TODO: Unsupported instruction: movk x7, #43836, lsl 16
    // TODO: Unsupported instruction: dup.2d v7, x4
    // TODO: Unsupported instruction: mov.16b v11, v9
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x7, #36286, lsl 32
    let t4 = t2 - t3;
    let t4 = bv_2.mul_add(bv_3, t4);
    // TODO: Unsupported instruction: movk x7, #51783, lsl 48
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    // TODO: Unsupported instruction: add.2d v0, v0, v12
    let bv_0 = 9848;
    let t1 = 10899;
    // TODO: Unsupported instruction: movk x4, #54501, lsl 16
    // TODO: Unsupported instruction: movk x4, #31540, lsl 32
    // TODO: Unsupported instruction: movk x4, #17170, lsl 48
    // TODO: Unsupported instruction: movk x9, #30709, lsl 16
    // TODO: Unsupported instruction: dup.2d v7, x4
    // TODO: Unsupported instruction: mov.16b v11, v9
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x9, #61551, lsl 32
    let t4 = t2 - t3;
    let t4 = bv_2.mul_add(bv_3, t4);
    // TODO: Unsupported instruction: movk x9, #45784, lsl 48
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    // TODO: Unsupported instruction: add.2d v1, v1, v12
    let bv_0 = 9584;
    let t2 = 36612;
    // TODO: Unsupported instruction: movk x4, #63883, lsl 16
    // TODO: Unsupported instruction: movk x4, #18253, lsl 32
    // TODO: Unsupported instruction: movk x4, #17190, lsl 48
    // TODO: Unsupported instruction: movk x10, #63402, lsl 16
    // TODO: Unsupported instruction: dup.2d v7, x4
    // TODO: Unsupported instruction: mov.16b v11, v9
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x10, #47623, lsl 32
    let t4 = t2 - t3;
    let t4 = bv_2.mul_add(bv_3, t4);
    // TODO: Unsupported instruction: movk x10, #9430, lsl 48
    // TODO: Unsupported instruction: add.2d v5, v5, v11
    // TODO: Unsupported instruction: add.2d v2, v2, v12
    let bv_0 = 51712;
    let t4 = bv_2.wrapping_mul(t3);
    // TODO: Unsupported instruction: movk x4, #16093, lsl 16
    // TODO: Unsupported instruction: movk x4, #30633, lsl 32
    // TODO: Unsupported instruction: movk x4, #17068, lsl 48
    let bv_2 = (((bv_2 as u128) * (t3 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: dup.2d v7, x4
    // TODO: Unsupported instruction: mov.16b v11, v9
    let t3 = bv_2.mul_add(bv_3, t3);
    let (bv_0, _carry) = t4.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t4 = t2 - t3;
    let t4 = bv_2.mul_add(bv_3, t4);
    let bv_2 = bv_3.wrapping_mul(t3);
    // TODO: Unsupported instruction: add.2d v3, v3, v11
    // TODO: Unsupported instruction: add.2d v5, v5, v12
    // TODO: Unsupported instruction: ucvtf.2d v6, v8
    let bv_3 = (((bv_3 as u128) * (t3 as u128)) >> 64) as u64;
    let t4 = 34724;
    // TODO: Unsupported instruction: movk x12, #40393, lsl 16
    // TODO: Unsupported instruction: movk x12, #23752, lsl 32
    let (bv_1, _carry) = bv_2.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x6, x7, hs
    // TODO: Unsupported instruction: movk x12, #17184, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x12
    // TODO: Unsupported instruction: mov.16b v8, v9
    let (av_0, _carry) = bv_1.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let bv_2 = t1.wrapping_mul(t3);
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: add.2d v0, v0, v8
    // TODO: Unsupported instruction: add.2d v4, v4, v11
    let bv_3 = (((t1 as u128) * (t3 as u128)) >> 64) as u64;
    let t1 = 25532;
    // TODO: Unsupported instruction: movk x9, #31025, lsl 16
    // TODO: Unsupported instruction: movk x9, #10002, lsl 32
    let (bv_1, _carry) = bv_2.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x6, x7, hs
    // TODO: Unsupported instruction: movk x9, #17199, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x9
    // TODO: Unsupported instruction: mov.16b v8, v9
    let (av_1, _carry) = bv_1.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let bv_2 = t2.wrapping_mul(t3);
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: add.2d v1, v1, v8
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    let bv_3 = (((t2 as u128) * (t3 as u128)) >> 64) as u64;
    let t1 = 18830;
    // TODO: Unsupported instruction: movk x9, #2465, lsl 16
    // TODO: Unsupported instruction: movk x9, #36348, lsl 32
    let (bv_1, _carry) = bv_2.overflowing_add(bv_1);
    // TODO: Unsupported instruction: cinc x6, x7, hs
    // TODO: Unsupported instruction: movk x9, #17194, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x9
    // TODO: Unsupported instruction: mov.16b v8, v9
    let (av_2, _carry) = bv_1.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x5, x6, hs
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let t3 = bv_2.mul_add(bv_3, t3);
    let av_3 = av_3.wrapping_add(bv_1);
    // TODO: Unsupported instruction: add.2d v2, v2, v8
    // TODO: Unsupported instruction: add.2d v1, v1, v11
    let bv_1 = 65535;
    let bv_2 = 21566;
    // TODO: Unsupported instruction: movk x6, #43708, lsl 16
    // TODO: Unsupported instruction: movk x6, #57685, lsl 32
    // TODO: Unsupported instruction: movk x5, #61439, lsl 16
    // TODO: Unsupported instruction: movk x6, #17185, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x6
    // TODO: Unsupported instruction: mov.16b v8, v9
    // TODO: Unsupported instruction: movk x5, #62867, lsl 32
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x5, #49889, lsl 48
    // TODO: Unsupported instruction: add.2d v5, v5, v8
    // TODO: Unsupported instruction: add.2d v2, v2, v11
    let bv_1 = bv_1.wrapping_mul(bv_0);
    let bv_2 = 3072;
    // TODO: Unsupported instruction: movk x6, #8058, lsl 16
    // TODO: Unsupported instruction: movk x6, #46097, lsl 32
    let bv_3 = 1;
    // TODO: Unsupported instruction: movk x6, #17047, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x6
    // TODO: Unsupported instruction: mov.16b v8, v9
    // TODO: Unsupported instruction: movk x7, #61440, lsl 16
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x7, #62867, lsl 32
    // TODO: Unsupported instruction: add.2d v3, v3, v8
    // TODO: Unsupported instruction: add.2d v5, v5, v11
    // TODO: Unsupported instruction: movk x7, #17377, lsl 48
    let bv_2 = 65535;
    // TODO: Unsupported instruction: movk x6, #61439, lsl 16
    // TODO: Unsupported instruction: movk x6, #62867, lsl 32
    let t1 = 28817;
    // TODO: Unsupported instruction: movk x6, #1, lsl 48
    // TODO: Unsupported instruction: umov x10, v4.d[0]
    // TODO: Unsupported instruction: umov x11, v4.d[1]
    // TODO: Unsupported instruction: movk x9, #31161, lsl 16
    let t2 = t2.wrapping_mul(bv_2);
    let bv_2 = t3.wrapping_mul(bv_2);
    let t2 = t2 & t0;
    // TODO: Unsupported instruction: movk x9, #59464, lsl 32
    let bv_2 = bv_2 & t0;
    // TODO: Unsupported instruction: ins v6.d[0], x10
    // TODO: Unsupported instruction: ins v6.d[1], x6
    // TODO: Unsupported instruction: movk x9, #10291, lsl 48
    // TODO: Unsupported instruction: ucvtf.2d v6, v6
    let bv_2 = 16;
    // TODO: Unsupported instruction: movk x6, #22847, lsl 32
    let t0 = 22621;
    // TODO: Unsupported instruction: movk x6, #17151, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x6
    // TODO: Unsupported instruction: mov.16b v8, v9
    // TODO: Unsupported instruction: movk x8, #33153, lsl 16
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x8, #17846, lsl 32
    // TODO: Unsupported instruction: add.2d v0, v0, v8
    // TODO: Unsupported instruction: add.2d v4, v4, v11
    // TODO: Unsupported instruction: movk x8, #47184, lsl 48
    let bv_2 = 20728;
    // TODO: Unsupported instruction: movk x6, #23588, lsl 16
    // TODO: Unsupported instruction: movk x6, #7790, lsl 32
    let t2 = 41001;
    // TODO: Unsupported instruction: movk x6, #17170, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x6
    // TODO: Unsupported instruction: mov.16b v8, v9
    // TODO: Unsupported instruction: movk x10, #57649, lsl 16
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: movk x10, #20082, lsl 32
    // TODO: Unsupported instruction: add.2d v1, v1, v8
    // TODO: Unsupported instruction: add.2d v0, v0, v11
    // TODO: Unsupported instruction: movk x10, #12388, lsl 48
    let bv_2 = 16000;
    // TODO: Unsupported instruction: movk x6, #53891, lsl 16
    // TODO: Unsupported instruction: movk x6, #5509, lsl 32
    let t3 = bv_3.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: movk x6, #17144, lsl 48
    // TODO: Unsupported instruction: dup.2d v7, x6
    // TODO: Unsupported instruction: mov.16b v8, v9
    let bv_2 = (((bv_3 as u128) * (bv_1 as u128)) >> 64) as u64;
    let t0 = bv_2.mul_add(bv_3, t0);
    let t3 = t2 - t0;
    let t3 = bv_2.mul_add(bv_3, t3);
    // TODO: Unsupported instruction: cmn x11, x4
    // TODO: Unsupported instruction: cinc x6, x6, hs
    // TODO: Unsupported instruction: add.2d v2, v2, v8
    // TODO: Unsupported instruction: add.2d v7, v1, v11
    let bv_0 = t1.wrapping_mul(bv_1);
    let bv_3 = 46800;
    // TODO: Unsupported instruction: movk x7, #2568, lsl 16
    // TODO: Unsupported instruction: movk x7, #1335, lsl 32
    let t1 = (((t1 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x7, #17188, lsl 48
    // TODO: Unsupported instruction: dup.2d v1, x7
    // TODO: Unsupported instruction: mov.16b v8, v9
    let (bv_0, _carry) = bv_0.overflowing_add(bv_2);
    // TODO: Unsupported instruction: cinc x6, x9, hs
    let t0 = bv_2.mul_add(av_1, t0);
    let t3 = t2 - t0;
    let t3 = bv_2.mul_add(av_1, t3);
    let (av_0, _carry) = bv_0.overflowing_add(av_0);
    // TODO: Unsupported instruction: cinc x4, x6, hs
    // TODO: Unsupported instruction: add.2d v1, v5, v8
    // TODO: Unsupported instruction: add.2d v5, v2, v11
    let bv_2 = t0.wrapping_mul(bv_1);
    let bv_3 = 39040;
    // TODO: Unsupported instruction: movk x7, #14704, lsl 16
    // TODO: Unsupported instruction: movk x7, #12839, lsl 32
    let t0 = (((t0 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: movk x7, #17096, lsl 48
    // TODO: Unsupported instruction: dup.2d v2, x7
    // TODO: Unsupported instruction: mov.16b v8, v9
    let (bv_0, _carry) = bv_2.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x6, x8, hs
    let t0 = bv_2.mul_add(av_2, t0);
    let t1 = t2 - t0;
    let t1 = bv_2.mul_add(av_2, t1);
    let (av_1, _carry) = bv_0.overflowing_add(av_1);
    // TODO: Unsupported instruction: cinc x4, x6, hs
    // TODO: Unsupported instruction: add.2d v6, v3, v8
    // TODO: Unsupported instruction: add.2d v8, v1, v9
    let bv_2 = t2.wrapping_mul(bv_1);
    // TODO: Unsupported instruction: ssra.2d v0, v4, #52
    // TODO: Unsupported instruction: ssra.2d v7, v0, #52
    // TODO: Unsupported instruction: ssra.2d v5, v7, #52
    let bv_1 = (((t2 as u128) * (bv_1 as u128)) >> 64) as u64;
    // TODO: Unsupported instruction: ssra.2d v8, v5, #52
    // TODO: Unsupported instruction: ssra.2d v6, v8, #52
    // TODO: Unsupported instruction: ushr.2d v1, v7, #12
    let (bv_0, _carry) = bv_2.overflowing_add(bv_0);
    // TODO: Unsupported instruction: cinc x5, x5, hs
    // TODO: Unsupported instruction: ushr.2d v2, v5, #24
    // TODO: Unsupported instruction: ushr.2d v3, v8, #36
    // TODO: Unsupported instruction: sli.2d v0, v7, #52
    let (av_2, _carry) = bv_0.overflowing_add(av_2);
    // TODO: Unsupported instruction: cinc x4, x5, hs
    // TODO: Unsupported instruction: sli.2d v1, v5, #40
    // TODO: Unsupported instruction: sli.2d v2, v8, #28
    // TODO: Unsupported instruction: sli.2d v3, v6, #16
    let av_3 = av_3.wrapping_add(bv_0);

    let out = [av_0, av_1, av_2, av_3];
    let outv = [av_0, av_1, av_2, av_3];

    (out, outv)
}
