[package]
name = "provekit-ffi"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
# Workspace crates
provekit-common.workspace = true
provekit-prover = { workspace = true, features = ["witness-generation", "parallel"] }
provekit-r1cs-compiler = { workspace = true }
provekit-verifier = { workspace = true }

# 3rd party
anyhow.workspace = true
noirc_abi.workspace = true
parking_lot.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
nargo_cli = { workspace = true }
nargo_toml = { workspace = true }
noirc_driver = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
