use {
    crate::Command,
    anyhow::{Context, Result},
    argh::FromArgs,
    provekit_common::{
        file::read, NoirProof, Verifier,
    },
    provekit_verifier::Verify,
    std::{
        fs::File,
        io::Write,
        path::PathBuf,
    },
    tracing::{info, instrument},
};

/// Generate input files for the Noir recursive verifier circuit.
///
/// Extracts all values the Noir verifier needs from a proof + verifier pair,
/// outputting a Prover.toml that can be used to witness-solve the recursive
/// verifier circuit.
#[derive(FromArgs, PartialEq, Eq, Debug)]
#[argh(subcommand, name = "generate-noir-inputs")]
pub struct Args {
    /// path to the verifier data file (.pkp)
    #[argh(positional)]
    verifier_path: PathBuf,

    /// path to the proof file (.np or .json)
    #[argh(positional)]
    proof_path: PathBuf,

    /// output path for the Noir Prover.toml
    #[argh(
        option,
        long = "output",
        default = "String::from(\"./Prover.toml\")"
    )]
    output_path: String,

    /// output path for supplementary JSON data (WHIR config, R1CS matrices)
    #[argh(
        option,
        long = "json",
        default = "String::from(\"./noir_verifier_data.json\")"
    )]
    json_path: String,
}

impl Command for Args {
    #[instrument(skip_all)]
    fn run(&self) -> Result<()> {
        let verifier: Verifier =
            read(&self.verifier_path).context("while reading Verifier data")?;

        let (constraints, witnesses) = (
            verifier.r1cs.num_constraints(),
            verifier.r1cs.num_witnesses(),
        );
        info!(constraints, witnesses, "Read verifier data");

        let proof: NoirProof = read(&self.proof_path).context("while reading proof")?;

        let wfw = verifier
            .whir_for_witness
            .as_ref()
            .context("verifier is missing whir_for_witness config")?;

        // Compute domain separator bytes (SHA3-512 hash of CBOR-serialized scheme)
        let ds = wfw.create_domain_separator();

        // Compute instance bytes (public inputs hash)
        let instance = proof.public_inputs.hash_bytes();

        info!(
            m_0 = wfw.m_0,
            m = wfw.m,
            num_challenges = wfw.num_challenges,
            has_public_inputs = wfw.has_public_inputs,
            "Generating Noir verifier inputs"
        );

        // Output key parameters as JSON for the Rust-side input generator
        let params = serde_json::json!({
            "log_num_constraints": wfw.m_0,
            "log_num_variables": wfw.m,
            "num_challenges": wfw.num_challenges,
            "w1_size": wfw.w1_size,
            "has_public_inputs": wfw.has_public_inputs,
            "narg_string": hex::encode(&proof.whir_r1cs_proof.narg_string),
            "narg_string_len": proof.whir_r1cs_proof.narg_string.len(),
            "hints": hex::encode(&proof.whir_r1cs_proof.hints),
            "hints_len": proof.whir_r1cs_proof.hints.len(),
            "public_inputs": proof.public_inputs.0.iter()
                .map(|f| format!("{f}"))
                .collect::<Vec<_>>(),
            "instance_hex": hex::encode(&instance),
            "r1cs_num_public_inputs": verifier.r1cs.num_public_inputs,
        });

        // Write JSON data
        let mut json_file =
            File::create(&self.json_path).context("while creating JSON output file")?;
        json_file
            .write_all(serde_json::to_string_pretty(&params)?.as_bytes())
            .context("while writing JSON output")?;
        info!(path = %self.json_path, "Wrote supplementary JSON data");

        // Also verify the proof passes (sanity check)
        info!("Running Rust verifier as sanity check...");
        let mut verifier_clone = verifier.clone();
        verifier_clone
            .verify(&proof)
            .context("Proof verification failed — cannot generate inputs for invalid proof")?;
        info!("Proof verified successfully");

        // Write a stub Prover.toml noting that full TOML generation requires
        // replaying the transcript. For now, output the JSON data that a
        // Python/Rust script can convert to Prover.toml.
        let mut toml_file =
            File::create(&self.output_path).context("while creating Prover.toml")?;
        toml_file
            .write_all(
                b"# ProveKit Noir Recursive Verifier Inputs\n\
                  # Generated by `provekit generate-noir-inputs`\n\
                  #\n\
                  # This file contains stub values. Full input generation\n\
                  # requires replaying the Fiat-Shamir transcript to extract\n\
                  # each intermediate value.\n\
                  #\n\
                  # See noir_verifier_data.json for the raw proof data.\n\n",
            )
            .context("while writing Prover.toml")?;

        // Write basic fields we can populate directly
        write!(toml_file, "num_public_inputs = {}\n", proof.public_inputs.0.len())?;
        write!(toml_file, "\n[public_inputs]\n")?;
        for (i, pi) in proof.public_inputs.0.iter().enumerate() {
            write!(toml_file, "  # public_inputs[{i}] = {pi}\n")?;
        }

        info!(
            toml_path = %self.output_path,
            json_path = %self.json_path,
            "Noir verifier inputs generated"
        );

        Ok(())
    }
}
