[package]
name = "complete_age_check"
type = "bin"
compiler_version = ">=0.32.0"

[dependencies]
compare_age = { path = "../zkpassport_libs/compare/age" }
data_check_expiry = { path = "../zkpassport_libs/data-check/expiry" }
passport_validity_check = { path = "../passport_validity_check" }
