[package]
name = "utils"
type = "lib"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
poseidon = { path = "../../../../target/v1-benchmarks/noir-beta19-compat/passport/poseidon" }
