[package]
name = "oprf"
type = "bin"
authors = [""]

[dependencies]
poseidon2 = { tag = "v0.6.2" , git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
babyjubjub = {path = "../babyjubjub"}
eddsa_poseidon2 = {path ="../eddsa_poseidon2"}
