import { ProveKitError, ProveKitErrorCode } from "./errors.js";
import type {
  ProveKitWasmModule,
  WasmInitInput,
  WasmModuleSource,
  WasmVariant,
} from "./wasm-types.js";

export interface ResolvedWasmModule {
  module: ProveKitWasmModule;
  wasmUrl?: WasmInitInput;
}

function viteOptimizedWorkerUrl(): string | undefined {
  if (!import.meta.url.includes("/node_modules/.vite/deps/")) return undefined;
  return new URL(
    /* @vite-ignore */ "../../@worldcoin/provekit/dist/wasm/threaded/provekit_wasm_worker.js",
    import.meta.url,
  ).href;
}

function isModule(value: unknown): value is ProveKitWasmModule {
  if (value === null || typeof value !== "object") return false;
  const candidate = value as Partial<ProveKitWasmModule>;
  return typeof candidate.default === "function" &&
    typeof candidate.Prover === "function" &&
    typeof candidate.Verifier === "function";
}

export async function resolveWasmModule(
  source: WasmModuleSource | undefined,
  variant: WasmVariant,
): Promise<ResolvedWasmModule> {
  let loaded: unknown;
  let wasmUrl: WasmInitInput | undefined;
  if (typeof source === "function") loaded = await source();
  else if (source) loaded = await source;
  else {
    // Keep both module specifiers static so dependency optimizers include the
    // generated glue in their module graph. A variable new URL() rooted in a
    // prebundled dependency becomes an empty Vite asset lookup at runtime.
    if (variant === "threaded") {
      // @ts-expect-error Generated by build:wasm and copied into dist/wasm.
      loaded = await import("./wasm/threaded/provekit_wasm.js");
      // @ts-expect-error Vite-compatible asset URL generated at consumer build time.
      wasmUrl = (await import("./wasm/threaded/provekit_wasm_bg.wasm?url")).default as string;
      const workerUrl = viteOptimizedWorkerUrl();
      if (workerUrl !== undefined) {
        (loaded as Partial<ProveKitWasmModule>).setWorkerUrl?.(workerUrl);
      }
    } else {
      // @ts-expect-error Generated by build:wasm and copied into dist/wasm.
      loaded = await import("./wasm/single/provekit_wasm.js");
      // @ts-expect-error Vite-compatible asset URL generated at consumer build time.
      wasmUrl = (await import("./wasm/single/provekit_wasm_bg.wasm?url")).default as string;
    }
  }

  if (!isModule(loaded)) {
    throw new ProveKitError(
      ProveKitErrorCode.WASM_UNAVAILABLE,
      "The ProveKit WASM module does not expose init, Prover, and Verifier",
    );
  }
  const result: ResolvedWasmModule = { module: loaded };
  if (wasmUrl !== undefined) result.wasmUrl = wasmUrl;
  return result;
}
