[package]
name = "data_check_expiry_lib"
type = "lib"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
date = { tag = "v0.4.4", git = "https://github.com/madztheo/noir-date.git" }
utils = { path = "../../utils" }