[package]
name = "complete_age_check"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
compare_age = { path = "vendor/utils/compare/age" }
data_check_expiry = { path = "vendor/utils/data-check/expiry" }
passport_validity_check = { path = "vendor/utils/passport_validity_check" }
