/**
 * ProveKit WASM Browser Demo
 *
 * Demonstrates zero-knowledge proof generation using ProveKit WASM bindings in the browser:
 * 1. Load compiled Noir circuit
 * 2. Generate witness using @noir-lang/noir_js (local web bundles)
 * 3. Generate proof using ProveKit WASM
 */

// DOM elements
const logContainer = document.getElementById("logContainer");
const runBtn = document.getElementById("runBtn");
const verifyBtn = document.getElementById("verifyBtn");

// Logging functions
function log(msg, type = "info") {
  const line = document.createElement("div");
  line.className = `log-line log-${type}`;
  line.textContent = msg;
  logContainer.appendChild(line);
  logContainer.scrollTop = logContainer.scrollHeight;
}

function updateStep(step, status, statusClass = "") {
  const el = document.getElementById(`step${step}-status`);
  if (el) {
    el.innerHTML = status;
    el.className = `step-status ${statusClass}`;
  }
}

/**
 * Log memory usage and key object sizes
 */
function logMemory(label, extras = {}) {
  let msg = `📊 ${label}`;
  
  // Log sizes of tracked objects
  for (const [name, obj] of Object.entries(extras)) {
    if (obj instanceof ArrayBuffer) {
      msg += ` | ${name}: ${(obj.byteLength / 1024 / 1024).toFixed(2)} MB`;
    } else if (obj instanceof Uint8Array) {
      msg += ` | ${name}: ${(obj.byteLength / 1024 / 1024).toFixed(2)} MB`;
    } else if (typeof obj === 'object' && obj !== null) {
      const jsonSize = JSON.stringify(obj).length;
      msg += ` | ${name}: ~${(jsonSize / 1024).toFixed(0)} KB`;
    }
  }
  
  // Chrome's non-standard memory API
  if (performance.memory) {
    const used = (performance.memory.usedJSHeapSize / 1024 / 1024).toFixed(1);
    msg += ` | heap: ${used} MB`;
  }
  
  log(msg, "info");
}

/**
 * Convert a Noir witness map to the format expected by ProveKit WASM.
 */
function convertWitnessMap(witnessMap) {
  const result = {};
  if (witnessMap instanceof Map) {
    for (const [index, value] of witnessMap.entries()) {
      result[index] = value;
    }
  } else if (typeof witnessMap === "object" && witnessMap !== null) {
    for (const [index, value] of Object.entries(witnessMap)) {
      result[Number(index)] = value;
    }
  } else {
    throw new Error(`Unexpected witness map type: ${typeof witnessMap}`);
  }
  return result;
}

/**
 * Get the artifact base path for the currently selected circuit.
 */
function getArtifactBase() {
  const circuit = window.activeCircuit || 'sha256';
  return `artifacts/${circuit}/`;
}

/**
 * Load circuit inputs from inputs.json (generated by setup from Prover.toml)
 */
async function loadInputs() {
  const response = await fetch(getArtifactBase() + "inputs.json");
  if (!response.ok) {
    throw new Error("inputs.json not found. Run setup first.");
  }
  return response.json();
}

/**
 * Simple TOML parser for Prover.toml files (browser-side).
 * Handles flat key = value, [section] headers, arrays, and strings.
 */
function parseSimpleToml(content) {
  const result = {};
  let section = null;
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const secMatch = line.match(/^\[([^\]]+)\]$/);
    if (secMatch) {
      section = secMatch[1];
      result[section] = result[section] || {};
      continue;
    }
    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) continue;
    const key = line.slice(0, eqIdx).trim();
    let val = line.slice(eqIdx + 1).trim();
    // Parse value
    if (val.startsWith('[') && val.endsWith(']')) {
      try { val = JSON.parse(val); } catch { /* keep as string */ }
    } else if (val.startsWith('"') && val.endsWith('"')) {
      val = val.slice(1, -1);
    } else if (val.startsWith("'") && val.endsWith("'")) {
      val = val.slice(1, -1);
    } else if (/^\d+$/.test(val)) {
      val = val; // Keep as string — noir_js expects string numbers
    }
    if (section) {
      result[section][key] = val;
    } else {
      result[key] = val;
    }
  }
  return result;
}

// Global state
let provekit = null;
let circuitJson = null;
let proverBin = null;
let verifierBin = null;
let lastProofBytes = null;

/**
 * Get current JS heap memory in MB (Chrome/Edge only, returns 0 elsewhere).
 */
function getHeapMB() {
  if (performance.memory) {
    return performance.memory.usedJSHeapSize / 1024 / 1024;
  }
  return 0;
}

async function initWasm() {
  try {
    // Step 1: Load WASM modules
    updateStep(1, '<span class="spinner"></span>Loading...', "running");
    log("Loading ProveKit WASM module...");

    const wasmModule = await import("../pkg/provekit_wasm.js");
    const wasmBinary = await fetch("pkg/provekit_wasm_bg.wasm");
    const wasmBytes = await wasmBinary.arrayBuffer();
    await wasmModule.default(wasmBytes);

    if (wasmModule.initPanicHook) {
      wasmModule.initPanicHook();
    }

    // Platform detection
    const isIOS = /iPhone|iPad|iPod/.test(navigator.userAgent);
    const isAndroid = /Android/.test(navigator.userAgent);
    const isMobile = isIOS || isAndroid;
    const maxThreads = navigator.hardwareConcurrency || 4;
    const threadCountEl = document.getElementById("threadCount");
    const hasSharedArrayBuffer = typeof SharedArrayBuffer !== 'undefined';
    
    // iOS WebKit has unreliable WASM threading - don't even try
    if (isIOS) {
      log("📱 iOS detected - WebKit WASM threading is unreliable");
      log("Running in single-threaded mode (optimized for iOS)");
      if (threadCountEl) {
        threadCountEl.textContent = 1;
      }
      // Don't call initThreadPool on iOS - it will fail
    } else if (isAndroid && hasSharedArrayBuffer) {
      // Android with Chrome/Firefox - try threading
      const androidThreads = Math.min(maxThreads, 4);
      log(`📱 Android detected, trying ${androidThreads} threads...`);
      try {
        await wasmModule.initThreadPool(androidThreads);
        log(`Thread pool ready (${androidThreads} workers)`);
        if (threadCountEl) {
          threadCountEl.textContent = androidThreads;
        }
      } catch (e) {
        log(`Thread pool failed: ${e.message}`, "warn");
        log("Falling back to single-threaded mode", "warn");
        if (threadCountEl) {
          threadCountEl.textContent = 1;
        }
      }
    } else if (!isMobile) {
      // Desktop
      if (hasSharedArrayBuffer) {
        try {
          log(`Initializing thread pool with ${maxThreads} workers...`);
          await wasmModule.initThreadPool(maxThreads);
          log(`Thread pool ready (${maxThreads} workers)`);
          if (threadCountEl) {
            threadCountEl.textContent = maxThreads;
          }
        } catch (e) {
          log(`Thread pool failed: ${e.message}`, "warn");
          log("Falling back to single-threaded mode", "warn");
          if (threadCountEl) {
            threadCountEl.textContent = 1;
          }
        }
      } else {
        log("SharedArrayBuffer not available, running single-threaded", "warn");
        if (threadCountEl) {
          threadCountEl.textContent = 1;
        }
      }
    } else {
      // Other mobile without SharedArrayBuffer
      log("Mobile: running in single-threaded mode");
      if (threadCountEl) {
        threadCountEl.textContent = 1;
      }
    }

    provekit = wasmModule;
    log("Initializing noir_js WASM modules...");

    // Wait for noir_js to be available (loaded via script tag)
    let attempts = 0;
    while (!window.Noir && attempts < 50) {
      await new Promise((r) => setTimeout(r, 100));
      attempts++;
    }

    if (!window.Noir) {
      throw new Error("Failed to load noir_js");
    }

    // Initialize noir WASM modules
    if (window.initNoir) {
      await window.initNoir();
    }

    log("noir_js initialized");
    updateStep(1, "Loaded", "success");
    runBtn.disabled = false;
    window.wasmReady = true;

  } catch (error) {
    log(`Error initializing WASM: ${error.message}`, "error");
    console.error(error);
    updateStep(1, "Failed", "error");
    // Keep button disabled
  }
}

async function runDemo() {
  runBtn.disabled = true;
  // Clear log lines but preserve hidden elements (proofOutput, proofCard)
  const logLines = logContainer.querySelectorAll('.log-line, .log-error-block');
  logLines.forEach(el => el.remove());

  // Reset steps 2-5 (Step 1 is already loaded)
  for (let i = 2; i <= 5; i++) {
    updateStep(i, "Waiting...");
  }

  // Reset verify button and proof state
  verifyBtn.disabled = true;
  lastProofBytes = null;

  let witnessTime = 0;
  let proofTime = 0;
  let witnessSize = 0;
  let proofSize = 0;
  let numConstraints = 0;
  let numWitnesses = 0;
  let inputs = {};
  let prover = null;
  try {
    // Step 2: Load prover/verifier artifacts and extract circuit
    updateStep(
      2,
      '<span class="spinner"></span>Loading artifacts...',
      "running"
    );
    const isCustom = window.activeCircuit === 'custom';

    if (isCustom && window.customFiles) {
      // Custom mode: read uploaded prover + verifier + inputs
      log("Loading uploaded prover and verifier artifacts...");
      logMemory("Before loading artifacts");
      proverBin = await window.customFiles.prover.arrayBuffer();
      verifierBin = await window.customFiles.verifier.arrayBuffer();

      log(
        `Prover artifact: ${(proverBin.byteLength / 1024 / 1024).toFixed(2)} MB`
      );
      log(
        `Verifier artifact: ${(verifierBin.byteLength / 1024 / 1024).toFixed(2)} MB`
      );
      logMemory("After loading artifacts", { proverBin, verifierBin });

      // Create Prover and extract embedded circuit
      log("Creating Prover instance...");
      prover = new provekit.Prover(new Uint8Array(proverBin));
      proverBin = null; // Free raw bytes

      numConstraints = prover.getNumConstraints();
      numWitnesses = prover.getNumWitnesses();
      log(`Circuit: ${numConstraints.toLocaleString()} constraints, ${numWitnesses.toLocaleString()} witnesses`);

      log("Extracting circuit from .wpkp...");
      const circuitBytes = prover.getCircuit();
      circuitJson = JSON.parse(new TextDecoder().decode(circuitBytes));
      log(`Circuit extracted from prover artifact`);
      logMemory("After creating Prover (freed proverBin)");

      updateStep(2, "Loaded", "success");

      // Load inputs
      updateStep(
        3,
        '<span class="spinner"></span>Generating witness...',
        "running"
      );
      const inputsFile = window.customFiles.inputs;
      let customInputs;
      if (inputsFile.name.endsWith('.toml')) {
        log("Parsing Prover.toml...");
        const tomlText = await inputsFile.text();
        customInputs = parseSimpleToml(tomlText);
      } else {
        const inputsText = await inputsFile.text();
        customInputs = JSON.parse(inputsText);
      }
      inputs = customInputs;
      log(`Inputs loaded (${Object.keys(inputs).length} top-level keys)`);
    } else {
      // Standard mode: fetch from artifacts directory
      const base = getArtifactBase();

      // Get circuit name from metadata.json
      let circuitName = "unknown";
      try {
        const metadataResponse = await fetch(base + "metadata.json");
        if (metadataResponse.ok) {
          const metadata = await metadataResponse.json();
          circuitName = metadata.name || "unknown";
        }
      } catch (e) {
        // Fallback to unknown if metadata.json doesn't exist
      }
      log(`Circuit: ${circuitName}`);

      log("Loading prover (.wpkp) and verifier (.wpkv) artifacts...");
      logMemory("Before loading artifacts");

      const [proverResponse, verifierResponse] = await Promise.all([
        fetch(base + "prover.wpkp"),
        fetch(base + "verifier.wpkv"),
      ]);

      proverBin = await proverResponse.arrayBuffer();
      verifierBin = await verifierResponse.arrayBuffer();

      log(
        `Prover artifact: ${(proverBin.byteLength / 1024 / 1024).toFixed(2)} MB`
      );
      log(
        `Verifier artifact: ${(verifierBin.byteLength / 1024 / 1024).toFixed(2)} MB`
      );
      logMemory("After loading artifacts", { proverBin, verifierBin });

      // Create Prover and extract embedded circuit
      log("Creating Prover instance...");
      prover = new provekit.Prover(new Uint8Array(proverBin));
      proverBin = null; // Free raw bytes

      numConstraints = prover.getNumConstraints();
      numWitnesses = prover.getNumWitnesses();
      log(`Circuit: ${numConstraints.toLocaleString()} constraints, ${numWitnesses.toLocaleString()} witnesses`);

      log("Extracting circuit from .wpkp...");
      const circuitBytes = prover.getCircuit();
      circuitJson = JSON.parse(new TextDecoder().decode(circuitBytes));
      log(`Circuit extracted from prover artifact`);
      logMemory("After creating Prover (freed proverBin)");

      updateStep(2, "Loaded", "success");

      // Step 3: Generate witness
      updateStep(
        3,
        '<span class="spinner"></span>Generating witness...',
        "running"
      );
      log("Loading inputs...");
      inputs = await loadInputs();
      log(`Inputs loaded (${Object.keys(inputs).length} top-level keys)`);
    }
    log("Generating witness using noir_js...");
    logMemory("Before witness generation", { circuitJson, inputs });

    // Allow UI to update before heavy computation
    await new Promise((r) => setTimeout(r, 50));

    const witnessStart = performance.now();
    const noir = new window.Noir(circuitJson);
    const { witness: compressedWitness } = await noir.execute(inputs);
    // Decompress witness stack and get the main witness (first element)
    const witnessStack = window.decompressWitness(compressedWitness);
    const witnessMap = witnessStack[0].witness;
    witnessTime = performance.now() - witnessStart;

    // Estimate witness size
    const witnessObjSize = witnessMap instanceof Map
      ? witnessMap.size * 64  // ~64 bytes per entry estimate
      : Object.keys(witnessMap).length * 64;
    log(`\u{1F4CA} Witness object: ~${(witnessObjSize / 1024).toFixed(0)} KB estimated`);
    logMemory("After witness generation");

    witnessSize =
      witnessMap instanceof Map
        ? witnessMap.size
        : Object.keys(witnessMap).length;
    log(`Witness size: ${witnessSize} elements`);
    log(`Witness generation time: ${witnessTime.toFixed(0)}ms`);

    updateStep(3, `Done (${witnessTime.toFixed(0)}ms)`, "success");

    // Step 4: Generate proof (reuse Prover created in step 2)
    updateStep(
      4,
      '<span class="spinner"></span>Generating proof...',
      "running"
    );
    log("Converting witness format...");

    const convertedWitness = convertWitnessMap(witnessMap);
    log(`Converted ${Object.keys(convertedWitness).length} witness entries`);

    log("Generating proof (this may take a while)...");
    logMemory("Before proveBytes");

    // Allow UI to update before heavy computation
    await new Promise((r) => setTimeout(r, 50));

    const proofStart = performance.now();
    log("Starting proof computation...");
    const heapBefore = getHeapMB();
    const proofBytes = prover.proveBytes(convertedWitness);
    const heapAfter = getHeapMB();
    const peakMemMB = Math.max(heapBefore, heapAfter);
    logMemory("After proveBytes");
    proofTime = performance.now() - proofStart;

    proofSize = proofBytes.length;
    log(`Proof size: ${(proofSize / 1024).toFixed(1)} KB`);
    log(`Proving time: ${(proofTime / 1000).toFixed(2)}s`);

    updateStep(4, `Done (${(proofTime / 1000).toFixed(2)}s)`, "success");

    // Store proof for verification
    lastProofBytes = proofBytes;

    // Show partial results (proof generation done)
    const totalTimeMs = witnessTime + proofTime;
    document.getElementById("totalTimeUi").textContent =
      `${(totalTimeMs / 1000).toFixed(2)}s`;
    document.getElementById("proofSizeUi").textContent =
      `${(proofSize / 1024).toFixed(1)} KB`;
    document.getElementById("constraintsUi").textContent =
      numConstraints.toLocaleString();
    document.getElementById("witnessesUi").textContent =
      numWitnesses.toLocaleString();

    // Show proof output (truncated)
    const proofText = new TextDecoder().decode(proofBytes);
    const truncated =
      proofText.length > 2000
        ? proofText.substring(0, 2000) + "..."
        : proofText;
    const proofOutputEl = document.getElementById("proofOutput");
    if (proofOutputEl) proofOutputEl.textContent = truncated;
    const proofCardEl = document.getElementById("proofCard");
    if (proofCardEl) proofCardEl.style.display = "block";

    // Enable verify button
    updateStep(5, "Ready \u2014 click Verify Proof");
    verifyBtn.disabled = false;
  } catch (error) {
    log(`Error: ${error.message}`, "error");
    console.error(error);

    // Update current step to show error
    for (let i = 2; i <= 4; i++) {
      const el = document.getElementById(`step${i}-status`);
      if (el && el.classList.contains("running")) {
        updateStep(i, "Failed", "error");
        break;
      }
    }
  } finally {
    runBtn.disabled = false;
  }
}

async function verifyProof() {
  if (!lastProofBytes || !verifierBin || !provekit) {
    log("No proof available. Generate a proof first.", "error");
    return;
  }

  verifyBtn.disabled = true;

  try {
    updateStep(5, '<span class="spinner"></span>Verifying...', "running");
    log("Creating verifier instance...");
    const verifier = new provekit.Verifier(new Uint8Array(verifierBin));
    log("Verifying proof...");

    // Allow UI to update
    await new Promise((r) => setTimeout(r, 50));

    const verifyStart = performance.now();
    verifier.verifyBytes(lastProofBytes);
    const verifyTime = performance.now() - verifyStart;
    log(`Verification time: ${verifyTime.toFixed(0)}ms`);
    log("Proof verified successfully!", "success");
    updateStep(5, `Verified ✓ (${verifyTime.toFixed(0)}ms)`, "success");

    // UI labels don't display verify status currently.
  } catch (error) {
    log(`Verification error: ${error.message}`, "error");
    console.error(error);
    updateStep(5, "Failed", "error");
  } finally {
    verifyBtn.disabled = false;
  }
}

/**
 * Called when the user switches circuits via the selector.
 * Resets proof state so the next Generate Proof uses the new circuit's artifacts.
 */
function onCircuitChanged(circuit) {
  // Reset proof state
  circuitJson = null;
  proverBin = null;
  verifierBin = null;
  lastProofBytes = null;

  // Reset steps 2-5
  for (let i = 2; i <= 5; i++) {
    updateStep(i, "Status: Waiting...");
  }

  // Reset metrics
  document.getElementById("totalTimeUi").textContent = "-";
  document.getElementById("proofSizeUi").textContent = "-";
  document.getElementById("constraintsUi").textContent = "-";
  document.getElementById("witnessesUi").textContent = "-";

  // Enable generate, disable verify
  if (provekit) {
    runBtn.disabled = false;
  }
  verifyBtn.disabled = true;

  log(`Switched to ${circuit.toUpperCase()} circuit`, "info");
}

// Initialize WASM on load
initWasm();

// Make functions available globally
window.runDemo = runDemo;
window.verifyProof = verifyProof;
window.onCircuitChanged = onCircuitChanged;
