/**
 * ProveKit WASM Browser Demo
 *
 * Demonstrates zero-knowledge proof generation using ProveKit WASM bindings in the browser:
 * 1. Load compiled Noir circuit
 * 2. Generate witness using @noir-lang/noir_js (local web bundles)
 * 3. Generate proof using ProveKit WASM
 */

// DOM elements
const logContainer = document.getElementById("logContainer");
const runBtn = document.getElementById("runBtn");

// Logging functions
function log(msg, type = "info") {
  const line = document.createElement("div");
  line.className = `log-line log-${type}`;
  line.textContent = msg;
  logContainer.appendChild(line);
  logContainer.scrollTop = logContainer.scrollHeight;
}

function updateStep(step, status, statusClass = "") {
  const el = document.getElementById(`step${step}-status`);
  if (el) {
    el.innerHTML = status;
    el.className = `step-status ${statusClass}`;
  }
}

/**
 * Convert a Noir witness map to the format expected by ProveKit WASM.
 */
function convertWitnessMap(witnessMap) {
  const result = {};
  if (witnessMap instanceof Map) {
    for (const [index, value] of witnessMap.entries()) {
      result[index] = value;
    }
  } else if (typeof witnessMap === "object" && witnessMap !== null) {
    for (const [index, value] of Object.entries(witnessMap)) {
      result[Number(index)] = value;
    }
  } else {
    throw new Error(`Unexpected witness map type: ${typeof witnessMap}`);
  }
  return result;
}

/**
 * Load circuit inputs from inputs.json (generated by setup from Prover.toml)
 */
async function loadInputs() {
  const response = await fetch("artifacts/inputs.json");
  if (!response.ok) {
    throw new Error("inputs.json not found. Run setup first.");
  }
  return response.json();
}

// Global state
let provekit = null;
let circuitJson = null;
let proverBin = null;

async function runDemo() {
  runBtn.disabled = true;
  logContainer.innerHTML = "";

  // Reset steps
  for (let i = 1; i <= 4; i++) {
    updateStep(i, "Waiting...");
  }

  // Hide previous results
  document.getElementById("summaryCard").classList.add("hidden");
  document.getElementById("proofCard").classList.add("hidden");

  let witnessTime = 0;
  let proofTime = 0;
  let witnessSize = 0;
  let proofSize = 0;

  try {
    // Step 1: Load WASM modules
    updateStep(1, '<span class="spinner"></span>Loading...', "running");
    log("Loading ProveKit WASM module...");

    const wasmModule = await import("../pkg/provekit_wasm.js");
    const wasmBinary = await fetch("pkg/provekit_wasm_bg.wasm");
    const wasmBytes = await wasmBinary.arrayBuffer();
    await wasmModule.default(wasmBytes);

    if (wasmModule.initPanicHook) {
      wasmModule.initPanicHook();
    }

    // Initialize thread pool for parallel proving
    // Use navigator.hardwareConcurrency or default to 4 threads
    const numThreads = navigator.hardwareConcurrency || 4;

    // Update UI with thread count
    const threadCountEl = document.getElementById("threadCount");
    if (threadCountEl) {
      threadCountEl.textContent = numThreads;
    }

    log(`Initializing thread pool with ${numThreads} workers...`);
    await wasmModule.initThreadPool(numThreads);
    log(`Thread pool ready (${numThreads} workers)`);

    provekit = wasmModule;

    log("ProveKit WASM loaded with parallelism");
    log("Initializing noir_js WASM modules...");

    // Wait for noir_js to be available (loaded via script tag)
    let attempts = 0;
    while (!window.Noir && attempts < 50) {
      await new Promise((r) => setTimeout(r, 100));
      attempts++;
    }

    if (!window.Noir) {
      throw new Error("Failed to load noir_js");
    }

    // Initialize noir WASM modules
    if (window.initNoir) {
      await window.initNoir();
    }

    log("noir_js initialized");
    updateStep(1, "Loaded", "success");

    // Step 2: Load circuit and prover artifact
    updateStep(
      2,
      '<span class="spinner"></span>Loading artifacts...',
      "running"
    );
    log("Loading circuit artifact...");

    const circuitResponse = await fetch("artifacts/circuit.json");
    circuitJson = await circuitResponse.json();

    // Get circuit name from metadata.json (generated by setup)
    let circuitName = "unknown";
    try {
      const metadataResponse = await fetch("artifacts/metadata.json");
      if (metadataResponse.ok) {
        const metadata = await metadataResponse.json();
        circuitName = metadata.name || "unknown";
      }
    } catch (e) {
      // Fallback to unknown if metadata.json doesn't exist
    }
    log(`Circuit: ${circuitName}`);

    // Update the page subtitle with circuit name
    document.getElementById("circuitName").textContent =
      `Circuit: ${circuitName}`;

    log("Loading prover artifact (this may take a moment)...");
    const proverResponse = await fetch("artifacts/prover.pkp");
    proverBin = await proverResponse.arrayBuffer();
    log(
      `Prover artifact: ${(proverBin.byteLength / 1024 / 1024).toFixed(2)} MB`
    );

    updateStep(2, "Loaded", "success");

    // Step 3: Generate witness
    updateStep(
      3,
      '<span class="spinner"></span>Generating witness...',
      "running"
    );
    log("Loading inputs from artifacts/inputs.json...");

    const inputs = await loadInputs();
    log(`Inputs loaded (${Object.keys(inputs).length} top-level keys)`);
    log("Generating witness using noir_js...");

    // Allow UI to update before heavy computation
    await new Promise((r) => setTimeout(r, 50));

    const witnessStart = performance.now();
    const noir = new window.Noir(circuitJson);
    const { witness: compressedWitness } = await noir.execute(inputs);
    const witnessMap = window.decompressWitness(compressedWitness);
    witnessTime = performance.now() - witnessStart;

    witnessSize =
      witnessMap instanceof Map
        ? witnessMap.size
        : Object.keys(witnessMap).length;
    log(`Witness size: ${witnessSize} elements`);
    log(`Witness generation time: ${witnessTime.toFixed(0)}ms`);

    updateStep(3, `Done (${witnessTime.toFixed(0)}ms)`, "success");

    // Step 4: Generate proof
    updateStep(
      4,
      '<span class="spinner"></span>Generating proof...',
      "running"
    );
    log("Converting witness format...");

    const convertedWitness = convertWitnessMap(witnessMap);
    log(`Converted ${Object.keys(convertedWitness).length} witness entries`);

    log("Generating proof (this may take a while)...");

    // Allow UI to update before heavy computation
    await new Promise((r) => setTimeout(r, 50));

    const proofStart = performance.now();
    const prover = new provekit.Prover(new Uint8Array(proverBin));
    const proofBytes = prover.proveBytes(convertedWitness);
    proofTime = performance.now() - proofStart;

    proofSize = proofBytes.length;
    log(`Proof size: ${(proofSize / 1024).toFixed(1)} KB`);
    log(`Proving time: ${(proofTime / 1000).toFixed(2)}s`);

    updateStep(4, `Done (${(proofTime / 1000).toFixed(2)}s)`, "success");

    // Show results
    document.getElementById("witnessTime").textContent =
      `${witnessTime.toFixed(0)}ms`;
    document.getElementById("proofTime").textContent =
      `${(proofTime / 1000).toFixed(2)}s`;
    document.getElementById("witnessSize").textContent =
      `${witnessSize.toLocaleString()}`;
    document.getElementById("proofSize").textContent =
      `${(proofSize / 1024).toFixed(1)} KB`;
    document.getElementById("summaryCard").classList.remove("hidden");

    // Show proof output (truncated)
    const proofText = new TextDecoder().decode(proofBytes);
    const truncated =
      proofText.length > 2000
        ? proofText.substring(0, 2000) + "..."
        : proofText;
    document.getElementById("proofOutput").textContent = truncated;
    document.getElementById("proofCard").classList.remove("hidden");

    log("Proof generated successfully!", "success");
  } catch (error) {
    log(`Error: ${error.message}`, "error");
    console.error(error);

    // Update current step to show error
    for (let i = 1; i <= 4; i++) {
      const el = document.getElementById(`step${i}-status`);
      if (el && el.classList.contains("running")) {
        updateStep(i, "Failed", "error");
        break;
      }
    }
  } finally {
    runBtn.disabled = false;
  }
}

// Make runDemo available globally
window.runDemo = runDemo;
