[package]
name = "provekit-fp-rounding"
version = "0.1.0"
description = "Floating-point rounding utilities for BN254 arithmetic"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dev-dependencies]
divan.workspace = true

[dependencies]
# Workspace crates
bn254-multiplier.workspace = true

[lints]
workspace = true

[[bench]]
name = "main"
harness = false
