//! Rust SIMD code generator for WASM targets
//!
//! Generates optimized Rust code using std::simd that preserves the instruction
//! interleaving and register allocation optimizations from the HLA framework.
//! This code compiles to efficient WASM SIMD (v128) instructions when built with
//! +simd128 target feature.

use {
    crate::{
        backend::AllocatedVariable,
        ir::{HardwareRegister, Instruction, Modifier, TypedHardwareRegister},
    },
    std::collections::HashMap,
};

/// Generate a complete Rust function with optimized SIMD operations
///
/// Takes HLA instructions with allocated registers and produces Rust code using
/// std::simd types. The generated code preserves instruction interleaving for
/// optimal performance.
pub fn generate_rust_portable_simd_with_name(
    function_name: &str,
    inputs: &[AllocatedVariable],
    outputs: &[AllocatedVariable],
    instructions: &[Instruction<HardwareRegister>],
) -> String {
    let mut code = String::new();

    // Header comment
    code.push_str("// GENERATED FILE, DO NOT EDIT!\n");
    code.push_str("// Generated by HLA framework for WASM SIMD optimization\n");
    code.push_str("// Note: Imports are in the parent module (mod.rs)\n\n");

    // Function signature
    code.push_str("#[inline(always)]\n");
    code.push_str(&format!("pub fn {}(\n", function_name));

    // Parameters
    code.push_str("    _guard: &RoundingGuard<Zero>,\n");

    for (i, input) in inputs.iter().enumerate() {
        let param_type = rust_type_for_variable(input);
        let comma = if i < inputs.len() - 1 { "," } else { "" };
        code.push_str(&format!("    {}: {}{}\n", input.label, param_type, comma));
    }

    code.push_str(") -> (");

    // Return type
    for (i, output) in outputs.iter().enumerate() {
        if i > 0 {
            code.push_str(", ");
        }
        code.push_str(&rust_type_for_variable(output));
    }

    code.push_str(") {\n");

    // Create register to variable name mapping
    let register_names = build_register_names(inputs, outputs, instructions);

    // Destructure array inputs into individual variables
    for input in inputs {
        if input.registers.len() > 1 {
            for idx in 0..input.registers.len() {
                code.push_str(&format!("    let {}_{} = {}[{}];\n",
                    input.label, idx, input.label, idx));
            }
        }
    }

    if inputs.iter().any(|i| i.registers.len() > 1) {
        code.push_str("\n");
    }

    // Function body - convert HLA instructions to Rust
    for instruction in instructions {
        let rust_line = hla_instruction_to_rust(instruction, &register_names);
        code.push_str("    ");
        code.push_str(&rust_line);
        code.push_str("\n");
    }

    // Reconstruct output arrays using the actual register names
    code.push_str("\n");
    for output in outputs {
        if output.registers.len() > 1 {
            code.push_str(&format!("    let {} = [", output.label));
            for (idx, reg) in output.registers.iter().enumerate() {
                if idx > 0 {
                    code.push_str(", ");
                }
                let hw_reg = reg.reg();
                let var_name = register_names.get(&hw_reg)
                    .cloned()
                    .unwrap_or_else(|| format!("r{}", hw_reg.0));
                code.push_str(&var_name);
            }
            code.push_str("];\n");
        }
    }

    // Return statement
    code.push_str("\n    (");
    for (i, output) in outputs.iter().enumerate() {
        if i > 0 {
            code.push_str(", ");
        }
        // For single-register outputs, return the register name directly
        if output.registers.len() == 1 {
            let hw_reg = output.registers[0].reg();
            let var_name = register_names.get(&hw_reg)
                .cloned()
                .unwrap_or_else(|| format!("r{}", hw_reg.0));
            code.push_str(&var_name);
        } else {
            code.push_str(&output.label);
        }
    }
    code.push_str(")\n");

    code.push_str("}\n");

    code
}

/// Determine the Rust type for a variable based on its register types
fn rust_type_for_variable(variable: &AllocatedVariable) -> String {
    if variable.registers.is_empty() {
        panic!("Variable {} has no registers", variable.label);
    }

    // Check first register to determine type
    // TypedHardwareRegister is an enum: General(HardwareRegister) or Vector(HardwareRegister)
    let is_vector = matches!(variable.registers[0], TypedHardwareRegister::Vector(_));

    if is_vector {
        // Vector register -> [Simd<u64, 2>; N]
        if variable.registers.len() == 1 {
            "Simd<u64, 2>".to_string()
        } else {
            format!("[Simd<u64, 2>; {}]", variable.registers.len())
        }
    } else {
        // Scalar general-purpose register -> [u64; N]
        if variable.registers.len() == 1 {
            "u64".to_string()
        } else {
            format!("[u64; {}]", variable.registers.len())
        }
    }
}

/// Build a mapping from hardware registers to Rust variable names
fn build_register_names(
    inputs: &[AllocatedVariable],
    outputs: &[AllocatedVariable],
    instructions: &[Instruction<HardwareRegister>],
) -> HashMap<HardwareRegister, String> {
    let mut names = HashMap::new();
    let mut temp_counter = 0;

    // Map input registers to parameter names
    // For array inputs, we use array syntax for reading (e.g., a[0])
    for input in inputs {
        for (idx, reg) in input.registers.iter().enumerate() {
            let hw_reg = reg.reg();
            if input.registers.len() == 1 {
                names.insert(hw_reg, input.label.clone());
            } else {
                // Use underscore notation for compatibility with let bindings
                names.insert(hw_reg, format!("{}_{}", input.label, idx));
            }
        }
    }

    // Map output registers (they're also local variables)
    for output in outputs {
        for (idx, reg) in output.registers.iter().enumerate() {
            let hw_reg = reg.reg();
            if !names.contains_key(&hw_reg) {
                if output.registers.len() == 1 {
                    names.insert(hw_reg, output.label.clone());
                } else {
                    names.insert(hw_reg, format!("{}_{}", output.label, idx));
                }
            }
        }
    }

    // Create temp variables for intermediate results
    for instruction in instructions {
        for result_reg in &instruction.results {
            let hw_reg = result_reg.reg;
            if !names.contains_key(&hw_reg) {
                let temp_name = format!("t{}", temp_counter);
                temp_counter += 1;
                names.insert(hw_reg, temp_name);
            }
        }
    }

    names
}

/// Convert a single HLA instruction to Rust code
fn hla_instruction_to_rust(
    instruction: &Instruction<HardwareRegister>,
    register_names: &HashMap<HardwareRegister, String>,
) -> String {
    use crate::reification::RegisterType;

    let opcode = instruction.opcode.as_str();

    // Get operand names
    let get_name = |reg: &HardwareRegister| -> String {
        register_names
            .get(reg)
            .cloned()
            .unwrap_or_else(|| format!("r{}", reg.0))
    };

    // Check if an operand is a vector/SIMD register
    let is_vector = |idx: usize| -> bool {
        if idx < instruction.operands.len() {
            matches!(instruction.operands[idx].r#type, RegisterType::V | RegisterType::D)
        } else {
            false
        }
    };

    match opcode {
        // Arithmetic operations
        "add" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {}.wrapping_add({});", dst, src1, src2)
        }
        "sub" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {}.wrapping_sub({});", dst, src1, src2)
        }
        "mul" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {}.wrapping_mul({});", dst, src1, src2)
        }
        "umulh" => {
            // Upper 64 bits of multiplication
            // Only valid for scalar values, not SIMD
            let dst = get_name(&instruction.results[0].reg);
            if is_vector(0) || is_vector(1) {
                // SIMD umulh is not directly supported - initialize to zero vector
                // This instruction shouldn't appear for SIMD values in properly generated code
                format!("let {} = Simd::splat(0);  // SIMD umulh not supported", dst)
            } else {
                let src1 = get_name(&instruction.operands[0].reg);
                let src2 = get_name(&instruction.operands[1].reg);
                format!(
                    "let {} = ((({} as u128) * ({} as u128)) >> 64) as u64;",
                    dst, src1, src2
                )
            }
        }
        "and" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {} & {};", dst, src1, src2)
        }
        "orr" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {} | {};", dst, src1, src2)
        }
        "eor" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {} ^ {};", dst, src1, src2)
        }

        // Shift operations
        "lsl" => {
            let dst = get_name(&instruction.results[0].reg);
            let src = get_name(&instruction.operands[0].reg);
            // Second operand is immediate value
            match &instruction.modifiers {
                Modifier::Lsl(imm) => {
                    format!("let {} = {} << {};", dst, src, imm)
                }
                Modifier::Imm(imm) => {
                    format!("let {} = {} << {};", dst, src, imm)
                }
                _ => {
                    if instruction.operands.len() > 1 {
                        format!("let {} = {} << {};", dst, src, get_name(&instruction.operands[1].reg))
                    } else {
                        format!("let {} = {};", dst, src)
                    }
                }
            }
        }
        "lsr" => {
            let dst = get_name(&instruction.results[0].reg);
            let src = get_name(&instruction.operands[0].reg);
            match &instruction.modifiers {
                Modifier::Imm(imm) => {
                    format!("let {} = {} >> {};", dst, src, imm)
                }
                _ => {
                    if instruction.operands.len() > 1 {
                        format!("let {} = {} >> {};", dst, src, get_name(&instruction.operands[1].reg))
                    } else {
                        format!("let {} = {};", dst, src)
                    }
                }
            }
        }
        "asr" => {
            // Arithmetic shift right
            let dst = get_name(&instruction.results[0].reg);
            let src = get_name(&instruction.operands[0].reg);
            match &instruction.modifiers {
                Modifier::Imm(imm) => {
                    format!("let {} = ({} as i64 >> {}) as u64;", dst, src, imm)
                }
                _ => {
                    if instruction.operands.len() > 1 {
                        format!(
                            "let {} = ({} as i64 >> {}) as u64;",
                            dst,
                            src,
                            get_name(&instruction.operands[1].reg)
                        )
                    } else {
                        format!("let {} = {};", dst, src)
                    }
                }
            }
        }

        // SIMD operations
        "fadd" | "fadd.2d" => {
            // SIMD add (f64x2)
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {} + {};", dst, src1, src2)
        }
        "fsub" | "fsub.2d" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {} - {};", dst, src1, src2)
        }
        "fmul" | "fmul.2d" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!("let {} = {} * {};", dst, src1, src2)
        }
        "fmla" | "fmla.2d" => {
            // Fused multiply-add: dst = dst + (src1 * src2)
            // ARM: fmla vd, vn, vm means vd = vd + vn * vm
            let dst = get_name(&instruction.results[0].reg);
            if instruction.operands.len() >= 2 {
                let src1 = get_name(&instruction.operands[0].reg);
                let src2 = get_name(&instruction.operands[1].reg);
                // mul_add(a, b) computes self * a + b, so for dst = dst + src1 * src2:
                // we need src1.mul_add(src2, dst)
                format!("let {} = {}.mul_add({}, {});", dst, src1, src2, dst)
            } else {
                format!("// TODO: fmla with insufficient operands")
            }
        }

        // Move operations
        "mov" => {
            let dst = get_name(&instruction.results[0].reg);
            if instruction.operands.is_empty() {
                // Immediate move
                match &instruction.modifiers {
                    Modifier::Imm(imm) => {
                        format!("let {} = {};", dst, imm)
                    }
                    _ => {
                        format!("let {} = 0;  // mov with unknown immediate", dst)
                    }
                }
            } else {
                let src = get_name(&instruction.operands[0].reg);
                format!("let {} = {};", dst, src)
            }
        }

        // Carry operations (adds/adcs/subs/sbcs)
        "adds" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            // For portable code, we track carries manually
            format!(
                "let ({}, _carry) = {}.overflowing_add({});",
                dst, src1, src2
            )
        }
        "adcs" => {
            let dst = get_name(&instruction.results[0].reg);
            let src1 = get_name(&instruction.operands[0].reg);
            let src2 = get_name(&instruction.operands[1].reg);
            format!(
                "let ({}, _carry) = {}.carrying_add({}, _carry);",
                dst, src1, src2
            )
        }

        _ => {
            // Fallback for unknown instructions
            format!("// TODO: Unsupported instruction: {}", instruction)
        }
    }
}
