name: Benchmark on Raspberry Pi 5

on:
  schedule: # Runs at midnight (0:00 UTC) every day
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:

env:
  DIVAN_MAX_TIME: 30
  CODSPEED_RUNNER_MODE: walltime

jobs:
  build:
    name: Build benchmark binaries
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly-2025-04-05
          cache-base: main
          cache-target: release
          bins: cargo-codspeed
      - name: Build the benchmark target(s)
        run: cargo codspeed build
      - name: Upload benchmark binaries and input files
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-binaries
          path: |
            target/codspeed
            noir-r1cs/benches/poseidon-1000.nps
            noir-r1cs/benches/poseidon-1000.np

  benchmark:
    name: Run benchmarks on Raspberry Pi 5
    runs-on: [self-hosted, rpi5]
    needs: build
    steps:
      # We need repo files for the benchmark input files
      - uses: actions/checkout@v4
      - name: Download benchmark binaries
        uses: actions/download-artifact@v4
        with:
          name: benchmark-binaries
          path: ./bench_bin
      - name: Setup Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly-2025-04-05
          cache: false # We don't actually use any build files, no need to restore cache
          bins: cargo-codspeed
      - name: Install codspeed-post-bench script
        run: |
          sudo mkdir -p /usr/local/bin
          sudo ln -s $(which cargo-codspeed) /usr/local/bin/codspeed-post-bench
          sudo chmod +x /usr/local/bin/codspeed-post-bench
      - name: Copy binaries and input files to target directories
        run: |
          mkdir -p target/codspeed
          cp -r bench_bin/target/codspeed/* target/codspeed/
          mkdir -p noir-r1cs/benches
          cp bench_bin/noir-r1cs/benches/poseidon-1000.* noir-r1cs/benches/
      - name: Make benchmark binaries executable
        run: chmod -R +x target/codspeed
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
