name: Kani model checking

on:
  push:
    paths:
      - "cm31/**"
  pull_request:
    paths:
      - "cm31/**"

jobs:
  kani:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Kani
        uses: model-checking/kani-github-action@v1
        with:
          # Whitelist directories that use Kani this prevents the entire project from being built.
          working-directory: "cm31"
